### ISSUE TITLE
ILS glide slope not shown on 1.3.10

### ISSUE THREAD

**Issue by baluba-sys** [magknight/787aviatorsTracker#100]
**Describe the bug**
When ILS app the LOC & G/S are not shown on the PFD, only the LOC and on the PFD the glide slope is not on the screen. Sometimes even the LOC is not aligned with the rwy (with a correct CRS of course)

**To Reproduce**
Init a flight from rwy head, tune the ILS freq and only the LOC is on the PFD.
Or in a flight enroute, when approach, tune the ILS freq and is the same behavior

**Expected behavior**
It´s expected the full LOC & G/S on the PFD

**Screenshots**
Here is a screenshot taken today on approach to MDSD, it´s supposed to be in this point at 3000 to be full stablished, no G/S is shown on the PFD

![Captura](https://user-images.githubusercontent.com/55158943/64642564-8fdc9100-d406-11e9-8320-e1b60aea4dc3.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 18362
 - X-Plane version 11.36r2
 - Version 1.3.10

**Additional context**
On 1.3.5 the ILS LOC & G/S work well, as I did not have any version from 1.3.5 to 1.3.10 I can´t confirm if others are affected (I mean 1.3.6, 7 and 8)

**Comment by aeroniemi** [comment]
The PFD shows that in that image the glideslope isn't armed, only LOC, which means that the VDEV indicator is not showing as expected - does it still happen if the APP button is in use?

**Comment by baluba-sys** [comment]
Hi aeroniemi, I tried to activate APP button when LOC was established and here we have the glide slope and the aircraft was following the G/S without problem until I deactivate the autopilot, then if I want to land manually the G/S signal is not shown, only LOC as you can check in the (sorry for the quality) pictures below.
Even this flight was streamed on youtube, you can check the exact moment when I was with autopilot and G/S and after deactivating AP then the G/S disappear.
https://youtu.be/49E7aenxWQM?t=6217


![Captura](https://user-images.githubusercontent.com/55158943/64926647-c6941c00-d7f7-11e9-99f0-f110ca133c06.PNG)

The picture above is whith AP, then you can check LOC & G/S

![Captura2](https://user-images.githubusercontent.com/55158943/64926656-dc094600-d7f7-11e9-886f-3aa7ccbc79ff.PNG)

The picture above is whithout AP; then you can check only LOC and NO G/S

Thanks for all

**Comment by aeroniemi** [comment]
In that case it's happening because the flight directors have gone off after you've turned off the autopilot
I've changed that in 1.4.0, but not 100% because x-plane still thinks they've fully gone off and then come back on, thus clearing the modes (FDIR doesn't save modes between "re-engages")

I'll see what can be done

**Comment by aeroniemi** [comment]
I've changed the logic on it for 1.4.0b1, so we'll see if it works any better
