### ISSUE TITLE
Free Text/Message Tab in FMC/ACARS

### ISSUE THREAD

**Issue by majorleonb** [magknight/787aviatorsTracker#101]
**Is your feature request related to a problem?**
Negatory

**Describe the solution you'd like**
An ACARS-Free Text Tab/Messages in the FMC

**Additional context**
The ACARS Free Text/Messages feature that almost all modern airliner's FMC have is used to pre-write ACARS messages or just to note down stuff. Its a minor feature of the FMC but it does contribute to the degree of realism and I know people that like to use it. Flight crews can use it to send and receive technical messages and reports to or from ground stations, such as a request for weather information or clearances or the status of connecting flights. The way how the ACARS Free Text/Message Tab looks is dependent on the airline but it generally looks similar like this: 

![image](https://user-images.githubusercontent.com/55296182/64888243-c0bd0000-d66a-11e9-8227-b69978f8e2c8.png)
![image](https://user-images.githubusercontent.com/55296182/64888281-ddf1ce80-d66a-11e9-9676-845f91585896.png)
![image](https://user-images.githubusercontent.com/55296182/64888290-e64a0980-d66a-11e9-9b87-4107f3c2e49f.png)

**Comment by aeroniemi** [comment]
can be added as part of the FMC/COMM stuff, and MFD/COMM stuff at a later date, once a firm decision on how to handle ACARS/CPDLC has been made
