### ISSUE TITLE
V/S MCP knob inverted

### ISSUE THREAD

**Issue by matthew007800** [magknight/787aviatorsTracker#103]
The Vertical Speed select wheel on the MCP (Autopilot panel) is inverted, Scrolling the knob down makes the number decrease and scrolling up makes the number grow, this should be the other way around as shown by the writing on the wheel.

**Comment by aeroniemi** [comment]
needs to be flipped in modelling

**Comment by aeroniemi** [comment]
@magknight1 needs to be fixed in modelling - just flip them over. temp fix will be doing it in cockpit obj

**Comment by aeroniemi** [comment]
should be fixed, needs testing
