### ISSUE TITLE
CDU 2 3d keyboard doesn't work

### ISSUE THREAD

**Issue by matthew007800** [magknight/787aviatorsTracker#104]
Unable to write in the scratchpad of CDU2 making it unuseable besides a reference piece

**Comment by aeroniemi** [comment]
does its popup entry work, or its 3d keyboard entry?

**Comment by aeroniemi** [comment]
@matthew007800 does it work using your physical keyboard on the popup

**Comment by aeroniemi** [comment]
right side buttons need to become FMS2 rather than just FMS
