### ISSUE TITLE
Strobe patterns are off and position of rear strobes is incorrectly placed.

### ISSUE THREAD

**Issue by majorleonb** [magknight/787aviatorsTracker#111]
Strobes are off with the blinking pattern, (Initial strobes as well as the default XP ones are blinking as it seems)
Also the position of the rear strobe lights aren't aligned with the new 3d Stobelights.
![B7879 - 2019-10-04 2 25 54 PM](https://user-images.githubusercontent.com/55296182/66207787-f5ddd080-e6b3-11e9-90ef-137268deda83.png)
![B7879 - 2019-10-04 2 26 03 PM](https://user-images.githubusercontent.com/55296182/66207788-f5ddd080-e6b3-11e9-9629-0365a7261d6b.png)
![B7879 - 2019-10-04 2 26 13 PM](https://user-images.githubusercontent.com/55296182/66207789-f5ddd080-e6b3-11e9-9fb0-7c615c8b3257.png)

![e1d6435fea1a14b112338ea0b940bdff](https://user-images.githubusercontent.com/55296182/66207531-4b65ad80-e6b3-11e9-875f-2502bd0cc8d2.gif)

OS: Windows 10 Pro
X-Plane version: XP 11.36r2, build 113601 64-bit, experimental flight model
Version 1.4.0-devBeta2

**Comment by magknight1** [comment]
Position of lights fixed.
