### ISSUE TITLE
APU Exhaust heat blur

### ISSUE THREAD

**Issue by majorleonb** [magknight/787aviatorsTracker#113]
Add a APU exhaust heat blur effect from the XP built-in heat blur effects. Would look great and add realism to it.
![155670236 dSENmjJV SC_5D_39227741](https://user-images.githubusercontent.com/55296182/66241324-2008b000-e6ff-11e9-9d37-bd3b069b9a9b.jpg)

Afaik its a simple job in Blender, thats what Matt told me, and depending on the possibilities, maybe the heat effect could last a few secs longer than the actual APU running time to simulate the heat coming from the turbine even after shutting down

**Comment by aeroniemi** [comment]
More than this, full particle effects, which are dependent on more modelling work than is available presently - it's on the list when the rest of the modelling work is done

**Comment by aeroniemi** [comment]
related to #60
