### ISSUE TITLE
IAS/MACH speed not decreasable

### ISSUE THREAD

**Issue by majorleonb** [magknight/787aviatorsTracker#114]
Knob to change speed only works partly, you can increase the MACH/IAS for A/T but you can't decrease it. It also doesnt matter if AT is on or turned off. Only way to reset the speed in the panel is resetting the aircraft (And I believe by mapping keys to keyboard/joystick for decreasing speed)

Turning on AP and then AT.

OS: Windows 10 Pro
X-Plane version: XP 11.36r2, build 113601 64-bit, experimental flight model
Version 1.4.0-devBeta2

A couple of beta versions earlier I had the same issue but only with MACH, I could just switch to IAS, then decrease speed value and then switch to MACH again, now neither works. Another Beta tester has the same exact bug so I doubt its just on my side. (Bill Clinton that is)

**Comment by aeroniemi** [comment]
should be fixed for 1.4.0db3
