### ISSUE TITLE
Screen tearing when selecting runway in the EFB

### ISSUE THREAD

**Issue by Bill-Clinton69** [magknight/787aviatorsTracker#117]
In the performance page when selecting a runway the screen tears. 

https://gyazo.com/c54088f0252d2a4d5b30a768b0b789f9

Xplane 11.40.b6

**Comment by aeroniemi** [comment]
There are more fields in the bug report form for a reason - please fill them out. I don't have any clue about your OS, or any of the other data that I need to actually do anything about it - it's highly unlikely that this is our fault directly, as we don't have a way to interact with the display output in that way

**Comment by Bill-Clinton69** [comment]
OS: Windows 10
X-Plane version: XP 11.40b6, experimental flight model on
Version 1.4.0-devBeta3

**Comment by aeroniemi** [comment]
log?

**Comment by Bill-Clinton69** [comment]
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/3703502/Log.txt)

**Comment by aeroniemi** [comment]
SASL is crashing because of the EFB not being able to find any runways for your airport - i've put a error message and check in for this - i don't know how that will affect them
