### ISSUE TITLE
Fwd ext and aft ext power light "avail" still on 

### ISSUE THREAD

**Issue by Bill-Clinton69** [magknight/787aviatorsTracker#120]
Ext power not connected but is still available. This screenshot was taken during cruise. 

![image](https://user-images.githubusercontent.com/56235285/66413916-a7ed0380-e9f8-11e9-91f3-0848fa18a7ad.png)

**Comment by Bill-Clinton69** [comment]
OS: Windows 10
X-Plane version: XP 11.40b6, experimental flight model on
Version 1.4.0-devBeta3

**Comment by aeroniemi** [comment]
should be fixed for DB4, along with the AFT EXT PWR not working bug
