### ISSUE TITLE
Doors are completely black at night

### ISSUE THREAD

**Issue by Bill-Clinton69** [magknight/787aviatorsTracker#121]
![image](https://user-images.githubusercontent.com/56235285/66415994-2481e100-e9fd-11e9-8a92-d6fef2ab2695.png)

OS: Windows 10
X-Plane version: XP 11.40b6, experimental flight model on
Version 1.4.0-devBeta3

All exit doors are completely black during night time.

**Comment by aeroniemi** [comment]
it's known and caused by the doors being attached to the fuse object, not going to be changed for 1.4.0, but maybe later in the run

**Comment by magknight1** [comment]
![X-Plane 2019-11-01 02-30-21-09](https://user-images.githubusercontent.com/49568118/68078096-66106c80-fdae-11e9-9b23-d80b8a7e0d85.png)
Issue solved.
