### ISSUE TITLE
EFB missing runways

### ISSUE THREAD

**Issue by GlitchedYT** [magknight/787aviatorsTracker#122]
On terminal charts, can no longer just enter icao to icao, have to search dep and arr airports
In performance when selecting runway for departure, error message comes up saying no runways found for this airport navdata may be out of date.

**Screenshots**
![X-Plane Screenshot 2019 10 11 - 11 55 20 75](https://user-images.githubusercontent.com/56449691/66670275-61c9b700-ec27-11e9-84e8-bc5c1092e4b1.png)

 - Windows 10
 - X-Plane Version 11.36
 - Version 1.4.0 Beta1

**Comment by aeroniemi** [comment]
see also #117

**Comment by GlitchedYT** [comment]
still happening on beta2 just to let you know

**Comment by martialblaizot** [comment]
I still cannot find a fix for this issue. Any idea what is causing this?
