### ISSUE TITLE
Hud Glass misplaced

### ISSUE THREAD

**Issue by tameraktasTU** [magknight/787aviatorsTracker#123]
**Describe the bug**
HUD-glass is misplaced (to the right)

**To Reproduce**
Just start a flight with the 787

**Expected behavior**
Should be more to the left

**Screenshots**
![B7879 - 2019-10-11 19 44 52](https://user-images.githubusercontent.com/46034843/66672881-a5401780-ec5f-11e9-8f5d-aef8baee3a8d.png)

**Desktop (please complete the following information):**
 - W10
 - X-Plane version 11.36
 - Version 1.4.0

**Additional context**

**Comment by matthew007800** [comment]
https://cdn.discordapp.com/attachments/372388610189557760/632319357388587028/unknown.png

Captain side Yes
FO side No

**Comment by magknight1** [comment]
Position corrected.
