### ISSUE TITLE
Many bugs

### ISSUE THREAD

**Issue by Atlanticreal** [magknight/787aviatorsTracker#124]
So, At first i was having SASL bugs, Where it would insta crash, Now im getting more bugs like buttons not working and screens not working 

Just load in

Should work like the last version
 
https://www.youtube.com/watch?v=fwjm1AGKalw&feature=youtu.be

 - OS: Windows 10
 - X-Plane version: 11.32 (pretty sure)
 - Version: 1.4 beta

[Log.txt](https://github.com/magknight/787aviatorsTracker/files/3718949/Log.txt)

**Comment by AviationGoalie** [comment]
I have had some bugs today. First off. Where ever I click somewhere I get a man saying “Tcas Test, Failed”. Another bug is that I get is that my displays are flashing on and off. The fmc, when I have my mouse over it. It changes with a halved display. And also the last thing is grey wheels. And also when I press in the efb I hear that guy again

**Comment by aeroniemi** [comment]
SASL is crashing due to failed activation - delete all *.key files in plugins/sasl/data/modules/main.key and reactivate
