### ISSUE TITLE
Pressing "Info" button = tcas test fail sound

### ISSUE THREAD

**Issue by tameraktasTU** [magknight/787aviatorsTracker#126]
**Describe the bug**
If you press the "Info" button the "Tcas Test fail" sounds plays

**To Reproduce**
press "Info" button and listen to the sound

**Expected behavior**
Should just play the button sound
![B7879 - 2019-10-11 19 59 14](https://user-images.githubusercontent.com/46034843/66673778-9c504580-ec61-11e9-88d1-26c030963997.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: W10
 - X-Plane version 11.36
 - Version 1.4.0

**Additional context**

**Comment by aeroniemi** [comment]
SND file must have spaces at end - @audiobirdxp

**Comment by audiobirdxp** [comment]
should be fixed now - test pending
