### ISSUE TITLE
F/D ON Switch has no sound

### ISSUE THREAD

**Issue by tameraktasTU** [magknight/787aviatorsTracker#128]
**Describe the bug**
If you flip the F/D ON switch

**To Reproduce**
Flip the switch guys

**Expected behavior**
A flip sound should play

**Screenshots**
![B7879 - 2019-10-11 20 36 46](https://user-images.githubusercontent.com/46034843/66676000-dc65f700-ec66-11e9-8517-3b7294f37031.png)

**Desktop (please complete the following information):**
 - OS: W10
 - X-Plane version 11.36
 - Version 1.4.0

**Additional context**

**Comment by aeroniemi** [comment]
potentially rolling with the wrong dataref - sound to investigate

**Comment by audiobirdxp** [comment]
Missing tangible sounds first appeared with with the update that had the incomplete cockpit. If datarefs/commands have changed, please inform or edit on change.

**Comment by tameraktasTU** [comment]
can confirm fixed in 1.4.0b2
