### ISSUE TITLE
CDU not working, Radio panel (all buttons) say Tcas Failed and more 

### ISSUE THREAD

**Issue by brownbear118** [magknight/787aviatorsTracker#129]
**Describe the bug**
CDU not working please see photo attached, Radios when pressing any button say TCAS failed, EFB not powering on at all. 

**To Reproduce**
not sure as some peoples are working looking on discord 

**Expected behavior**

**Screenshots**
https://images-ext-1.discordapp.net/external/Y_ZPuueIM0wXVwHrQEZx53CuSFQuoJqmVX0-S2R8Pr4/https/image.prntscr.com/image/ze9Pu_BhRLiQ6VFkHJYHPA.png?width=634&height=650

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.32]
 - Version [e.g. 1.4.0B1]

**Additional context**

**Comment by aeroniemi** [comment]
Log file?

**Comment by brownbear118** [comment]
Log File is 103 MB not sure how to upload it

**Comment by aeroniemi** [comment]
copy the repeated lines towards the end - it's erroring every frame

**Comment by brownbear118** [comment]
[New Text Document (2).txt](https://github.com/magknight/787aviatorsTracker/files/3719925/New.Text.Document.2.txt)

**Comment by brownbear118** [comment]
not sure if that is ok, but I have Win Rar it down and can discord it to you
