### ISSUE TITLE
Unusable

### ISSUE THREAD

**Issue by DeltaYankee2** [magknight/787aviatorsTracker#131]
**Describe the bug**
EFB, FO side, AP displays blank. Unable to turn on EFB. Radio panels do not work
![787](https://user-images.githubusercontent.com/56453879/66679593-7b3e2380-ec66-11e9-91c2-fdf815a1833c.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.34r1]
 - Version [e.g. 113400  64bit]

**Additional context**

**Comment by aeroniemi** [comment]
Log file? probably related to #129 (neither have logs)

**Comment by brownbear118** [comment]
I have the same issue

**Comment by aeroniemi** [comment]
I need a log to find out what is going on

**Comment by brownbear118** [comment]
We are both just doing a Zibo flight and then will upload one for you :)

**Comment by DeltaYankee2** [comment]
Log file is 80MB -  How can I transfer it?

**Comment by aeroniemi** [comment]
copy the repeated lines at the end and upload them

**Comment by DeltaYankee2** [comment]
https://1drv.ms/u/s!AoWFZ4KFQIEmgZlWKwXuTH4cWnBq5g?e=DIzD38

Log is in the zip file on this one drive link

**Comment by aeroniemi** [comment]
@DeltaYankee2 you're using 11.34, and the plane is dependent on a minimum of 11.35 - you need to update you're x-plane
