### ISSUE TITLE
Tons of bugs.

### ISSUE THREAD

**Issue by flfy** [magknight/787aviatorsTracker#132]
**Describe the bug**
Bug 1 - Aircraft strobe/nav lights come on after a/c reload through developer menu

Bug 2 - `JUMP` in the CDU breaks screens.

Bug 3 - EICAS button triggers an audible `TCAS Test Fail` warning.

**POSSIBLE BUG 4** - Buttons have no sound. This could be due to an incomplete soundpack, though.

Bug 5 - NAV Lights flash multiple colors on multiple areas of wing.

**To Reproduce**
Bug 1 - Load a/c. Battery on. Reload a/c through developer menu and observe.

Bug 2 - Power on a/c, select `JUMP` in the CDU and hover over the CDU. Navigation is impossible.

Bug 3 - Power on a/c. Hit the EICAS button on the MFD control panel. Observe.

**POSSIBLE BUG 4** - Press any button. Observe.

Bug 5 - Power on a/c to GPU power. Toggle NAV lights, observe the NAV lights strobing, flashing red/green/white etc.

**Expected behavior**
Bug 1 - All lights should be off.

Bug 2 - CDU should perform expected `JUMP` action, and the screens should not break.

Bug 3 - EICAS button should make a button press sound, not trigger a TCAS test sound.

**POSSIBLE BUG 4** - Buttons should have sound. All knobs do.

Bug 5 - NAV lights should have a constant steady color.

**Desktop (please complete the following information):**
 - OS: W10
 - X-Plane version 11.36r2
 - Version 1.4.0b1

**Comment by aeroniemi** [comment]
ideally put each bug into a seporate issue

**Comment by flfy** [comment]
I won't go through and rewrite 5 issues.. I hope you understand.

**Comment by aeroniemi** [comment]
issue closed as contains more than one bug - impossible to track
