### ISSUE TITLE
Aircraft strobe/nav lights

### ISSUE THREAD

**Issue by matthew007800** [magknight/787aviatorsTracker#133]
Aircraft strobe/nav lights come on after a/c reload through developer menu

**Comment by matthew007800** [comment]
to reproduce
Load a/c. Battery on. Reload a/c through developer menu and observe.

**Comment by matthew007800** [comment]
to reproduce
Power on a/c, select JUMP in the CDU and hover over the CDU. Navigation is impossible.

**Comment by aeroniemi** [comment]
suggests that it's starting with engines running, at least from a dataref perspective

**Comment by flfy** [comment]
negative, tested from a cold and dark state, all the way up to a GPU power state with lights on. Reloaded the a/c, lights remained on and no power source was connected

**Comment by aeroniemi** [comment]
resolved by #181
