### ISSUE TITLE
JUMP in the CDU breaks screens.

### ISSUE THREAD

**Issue by matthew007800** [magknight/787aviatorsTracker#134]
JUMP in the CDU breaks screens.

**Comment by matthew007800** [comment]
To reproduce
Power on a/c, select JUMP in the CDU and hover over the CDU. Navigation is impossible.

**Comment by aeroniemi** [comment]
does jump work if your scratchpad is empty, or if you have a valid waypoint in it?

**Comment by matthew007800** [comment]
No scratchpad present

**Comment by aeroniemi** [comment]
there is - it reads directly from the main CDU scratchpad

**Comment by flfy** [comment]
Empty scratchpad or with a waypoint, it does it. This is only an issue with an empty flightplan, from what I've gathered. Seems like there is a missing check on if there is an active flightplan or not

**Comment by AviationGoalie** [comment]
FIX! If your screens are flashing then go into plugins/PluginAdmin and then turn off SASL and and then turn it on again. 

The issue happens when you go to init ref page and press "Jump". Sooo, do not press "Jump" on Init ref page! :)

**Comment by flfy** [comment]
I have come across another workaround. NOT a fix, just like above is a temporary work around. If you end up in this situation, try to hit the `THRUST LIM` button on the CDU and it fixes it.. why? Don't know. But it does.

**Comment by AviationGoalie** [comment]
OOh okay

**Comment by aeroniemi** [comment]
should be fixed in b2, reopen if not
