### ISSUE TITLE
Landing Physics are a bit wonky

### ISSUE THREAD

**Issue by GlitchedYT** [magknight/787aviatorsTracker#138]
**Describe the bug**
I dont know if this is just me or if anyone else has had this issue yet but the landing physics are a little bit off. And by a little bit i mean a good amount. Coming in to land at lax, final speed around 147 knots flaps 30 and the plane was pitching down which i thought was very weird. had to land with the nose wheel first or else i would've had to do a go around. 

**Screenshots**
![X-Plane Screenshot 2019 10 11 - 21 08 13 73](https://user-images.githubusercontent.com/56449691/66692431-4a60ed00-ec6c-11e9-8484-ec17e2b012f7.png)
![X-Plane Screenshot 2019 10 11 - 21 08 21 90](https://user-images.githubusercontent.com/56449691/66692432-4a60ed00-ec6c-11e9-9954-09e7fce0302f.png)
![X-Plane Screenshot 2019 10 11 - 21 08 33 47](https://user-images.githubusercontent.com/56449691/66692433-4a60ed00-ec6c-11e9-831f-19a65048c898.png)
![X-Plane Screenshot 2019 10 11 - 21 09 10 50](https://user-images.githubusercontent.com/56449691/66692434-4af98380-ec6c-11e9-9055-b615a02cf0e5.png)
![X-Plane Screenshot 2019 10 11 - 21 09 28 39](https://user-images.githubusercontent.com/56449691/66692435-4af98380-ec6c-11e9-86a6-6fd42793a3d0.png)
![X-Plane Screenshot 2019 10 11 - 21 09 45 02](https://user-images.githubusercontent.com/56449691/66692436-4af98380-ec6c-11e9-8e54-550b59755543.png)

Specs
 - Windows 10
 - X-Plane 11.36
 - 1.4.0 beta1

**Comment by aeroniemi** [comment]
experimental on?

**Comment by GlitchedYT** [comment]
yes experimental flight model is confirmed on. i'm going to do a few flights today and see if the trim has anything to do with it... will report back

**Comment by Sdozer** [comment]
I have the same behaviour, the plane flies with nosedown attitude at several conditions. Video: https://drive.google.com/open?id=15_vYAb2gPqzlFtkx3a6xtGsCl_XKpFVn

**Comment by ZeeMuffenMan** [comment]
I also agree about the flight model. As much as the team try to say its right and within 5% of the real deal, I can't understand how that can be right. Hope the FM is adjusted!
