### ISSUE TITLE
Unable to turn left mid cruise

### ISSUE THREAD

**Issue by Noodle13** [magknight/787aviatorsTracker#139]
When mid cruise the plane is unable to turn left, both with autopilot engaged and disengaged.
Joystick works fine as the yoke in the plane moves with my inputs. All other movements work fine (up, down and right)

This occured after 2 hours in the flight, no turbulence or movements reported before the issue

OS: Windows 10
Using the 1.4.0 Beta 1 version

**Comment by aeroniemi** [comment]
has anyone else seen this issue?
