### ISSUE TITLE
Non-Matching Fuel Readings

### ISSUE THREAD

**Issue by Fergy323** [magknight/787aviatorsTracker#14]
**Describe the bug**
Two different FOB readings

**To Reproduce**

**Expected behavior**
For both fuel readings to be the same, the left one to read the total amount of fuel from all 3 tanks.

**Screenshots**
http://prntscr.com/nezcnc

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version: 11.32
 - Version: Latest

**Comment by aeroniemi** [comment]
Caused by the fuel efis page in the release version only working in lbs. It's replaced by 1.2.0
