### ISSUE TITLE
TCAS test fail

### ISSUE THREAD

**Issue by GlitchedYT** [magknight/787aviatorsTracker#140]
**Describe the bug**
Not sure if this has been reported yet but when a button is pressed on the joystick or yoke that isn't mapped to anything, a tcas test failed message will be read. for example, im on vatsim rn and whenever i transmit on the freq a voice says tcas test failed.

Video of the bug/issue:
https://imgur.com/xMR9TJd

**Expected behavior**
Tcas test fail should not be read when a button on a joystick or yoke that isn't mapped to anything is pressed

**Desktop (please complete the following information):**
 - Windows 10
 - X-Plane version 11.36
 - 787 version 1.4.0 beta1

**Comment by aeroniemi** [comment]
duplicate of #126
