### ISSUE TITLE
mapping error (ants) 1.4

### ISSUE THREAD

**Issue by jnmg2014** [magknight/787aviatorsTracker#141]
Hi, I discovered a mapping error (ants), this one is located in the rear landing gear gate and can be seen from the cabin

![Caiijptura](https://user-images.githubusercontent.com/50252943/66705891-e63d3800-ed02-11e9-8ae0-524356be0024.PNG)

OS:  Windows 10
X-Plane version 11.36
Version 1.4.0B1

**Comment by aeroniemi** [comment]
there's ants in the engines and main gear also

**Comment by tameraktasTU** [comment]
> there's ants in the engines and main gear also

can confirm

**Comment by jnmg2014** [comment]
yes
![Captlklura](https://user-images.githubusercontent.com/50252943/66709591-dbec5f80-ed3d-11e9-8659-e6abf5d08e36.PNG)

**Comment by flfy** [comment]
That top bit of ants in the screenshot of the engine is the landing light cover, FYI

**Comment by magknight1** [comment]
Landing gear doors didn't have the texture assigned. Ants have been exterminated.
