### ISSUE TITLE
Fix the Fuse AO; Just for the completeness

### ISSUE THREAD

**Issue by tameraktasTU** [magknight/787aviatorsTracker#143]
**Describe the bug**
The AO is clearly improvable on the fuse

**To Reproduce**
look at the fuse 

**Expected behavior**
should not look like you sprinkled pepper on the fuse 

**Screenshots**
![B7879 - 2019-10-12 02 13 49](https://user-images.githubusercontent.com/46034843/66708396-35f62080-ed50-11e9-8d24-3181778bc89d.png)
![B7879 - 2019-10-12 17 42 54](https://user-images.githubusercontent.com/46034843/66708397-368eb700-ed50-11e9-9896-8026fcd91135.png)

**Desktop (please complete the following information):**
 - OS: W10
 - X-Plane version 11.36
 - Version 1.4.0
**Additional context**

**Comment by magknight1** [comment]
The "chef" in charge of the pepper has been reprimanded. Sampling on the baking process was on a low level. Shadows have been added to create more realism.
