### ISSUE TITLE
Plane is always loading up with elevators/ailerons/flaperons up

### ISSUE THREAD

**Issue by tameraktasTU** [magknight/787aviatorsTracker#144]
**Describe the bug**
Plane is always loading up with elevators/ailerons/flaperons up

**To Reproduce**
Start up the plane 

**Expected behavior**
should be centered

**Screenshots**
![B7879 - 2019-10-12 21 28 42](https://user-images.githubusercontent.com/46034843/66708520-ced96b80-ed51-11e9-9e24-64b0be0d1f4f.png)
![B7879 - 2019-10-13 00 35 03](https://user-images.githubusercontent.com/46034843/66708521-ced96b80-ed51-11e9-9410-cb4f735cffca.png)

**Desktop (please complete the following information):**
 - OS: w10
 - X-Plane version 11.36
 - Version 1.4.0

**Additional context**

**Comment by aeroniemi** [comment]
expected behaviour, as these are the default positions when the plane doesn't have any hydraulics power (surfaces are often FCTL locked when on the ground for long periods, or the hydraulics pressure is enough to keep the system up for a few hours)
