### ISSUE TITLE
animation bug

### ISSUE THREAD

**Issue by jnmg2014** [magknight/787aviatorsTracker#145]
With the cargo door open, I called the pushback, it connected and this started to happen

https://youtu.be/xcAcBPIXqsk

 - OS: Windows 10
 - X-Plane version 11.36
 - Version 1.4.0B1

**Comment by aeroniemi** [comment]
anyone else seeing this?

**Comment by KXRicciardo3** [comment]
### **Issue with the aircraft**
After I took off, and while I am climbing, the airplane suddenly started to stall. And on the MFD, there is a yellow word saying 'MAIN BATTERY DISCH' and then with the stall, the plane just crashed.
![image](https://user-images.githubusercontent.com/56505492/66714704-88851a80-edec-11e9-8f3e-8af4421a1ef1.png)
My gens are on
![image](https://user-images.githubusercontent.com/56505492/66714710-9a66bd80-edec-11e9-81cd-e285c3446445.png)

OS: Windows 10
X-Plane version: 11.36
Magknight 787 version: 1.4.0 Beta
Fuel onboard: 49.7

**Comment by aeroniemi** [comment]
That's not a animation bug - it needs to be in a new issue

**Comment by aeroniemi** [comment]
is this only happening during pushback? - did you close the doors beforehand, did you set the beacon, did you start an engine?

**Comment by jnmg2014** [comment]
I remember not, I just started the pushback and started that, but what I remember is that I didn't close the cargo door

**Comment by aeroniemi** [comment]
nobody has reported this since, closing as stale
