### ISSUE TITLE
Warning label on the FO side is the wrong way around

### ISSUE THREAD

**Issue by tameraktasTU** [magknight/787aviatorsTracker#149]
**Describe the bug**
Warning label on the FO side is the wrong way around

**To Reproduce**
look at the FO side 

**Expected behavior**
Should be readable without a mirror lol

**Screenshots**
![B7879 - 2019-10-14 01 36 59](https://user-images.githubusercontent.com/46034843/66724321-dddd1e00-ee24-11e9-8a92-a664428554cb.png)

**Desktop (please complete the following information):**
 - OS: W10
 - X-Plane version 11.36
 - Version 1.4.0b2

**Additional context**

**Comment by magknight1** [comment]
Texture corrected.
