### ISSUE TITLE
Heater control FO side isnt working correctly

### ISSUE THREAD

**Issue by tameraktasTU** [magknight/787aviatorsTracker#150]
**Describe the bug**
Heater control on captain side function correctly, FO side is kinda buggy (shoulder and foot)

**To Reproduce**
try to turn the knob on the heaters of  the FO side and compare to captain side

**Expected behavior**
Should work like on the the captain side

**Screenshots**
![B7879 - 2019-10-14 01 37 07](https://user-images.githubusercontent.com/46034843/66724339-314f6c00-ee25-11e9-9ab2-841011e60fa0.png)

**Desktop (please complete the following information):**
 - OS: w10
 - X-Plane version 11.36
 - Version 1.4.0b2

**Additional context**

**Comment by aeroniemi** [comment]
temp fix in b4

**Comment by aeroniemi** [comment]
resolved in b7
