### ISSUE TITLE
Left and right wipers are moving both when moving either of the wiper knobs

### ISSUE THREAD

**Issue by tameraktasTU** [magknight/787aviatorsTracker#151]
**Describe the bug**
Left and right wipers are moving both when moving either of the wiper knobs

**To Reproduce**
Turn the wiper knob, both will move

**Expected behavior**
Left and right side should move individually

**Screenshots**
![B7879 - 2019-10-14 01 40 46](https://user-images.githubusercontent.com/46034843/66724362-84c1ba00-ee25-11e9-820e-28dbd0df8163.png)

**Desktop (please complete the following information):**
 - OS: w10
 - X-Plane version 11.36
 - Version 1.4.0b2

**Additional context**

**Comment by aeroniemi** [comment]
expected, as xp only supports one wiper by default - maybe changed with librain implimentation
