### ISSUE TITLE
LOC capturing issues

### ISSUE THREAD

**Issue by GlitchedYT** [magknight/787aviatorsTracker#152]
**Describe the bug**
I'm not completely sure if this is just due to the fact that this plane uses the default fmc or not, but for the last 4 ILS landings i've done, the LOC capture keeps the plane way to the left or the right at about a 45 degree angle to the runway instead of lining it up with the center lines. The plane captures the LOC fine but doesn't line it up well at all. Like i said not sure if the is just because it's using the default fmc or just a bug altogether.. From what i've seen, the system is just lining it up with the direction of the runway in general rather than the heading/center line of the actual runway

**Expected behavior**
When the LOC captures it should line the plane up with the runway's heading/center line rather than stay way to the left or the right pointing at a 45 degree angle to the runway.

**Screenshots**
Didn't take any screenshots prior to posting this but i'll add some the next time i try an ILS landing

**Desktop (please complete the following information):**
 - Windows 10
 - X-Plane 11.36
 - Version 1.4 beta2

**Comment by daza10** [comment]
Had the same behaviour on approach to 07R KLAX.

**Comment by aeroniemi** [comment]
is the plane switching to NAV1/NAV2 correctly?
to find out, check the status of ``sim/cockpit2/radios/actuators/HSI_source_select_pilot``

**Comment by GlitchedYT** [comment]
Am I able to just send you that file, or do I have to do an old approach for it to show in the file

**Comment by daza10** [comment]
Tried 2 more approaches to KLAX 07R. 1 was to the right of the centre line - just on the runway. 2nd was way to the right - missing the runway. Both had nav1 & 2 dialled to ILS and both courses using runway direction (071). 
Need to try different airport to see if it’s just KLAX.

**Comment by aeroniemi** [comment]
> 
> 
> Tried 2 more approaches to KLAX 07R. 1 was to the right of the centre line - just on the runway. 2nd was way to the right - missing the runway. Both had nav1 & 2 dialled to ILS and both courses using runway direction (071).
> Need to try different airport to see if it’s just KLAX.

is the plane switching to NAV1/NAV2 correctly?
to find out, check the status of sim/cockpit2/radios/actuators/HSI_source_select_pilot

**Comment by daza10** [comment]
The above value in datareftool shows 0. Took off and landed at KLAX and at no point did it change.

**Comment by daza10** [comment]
Just an update. Can see HSI_Source_Select is switching correctly. Shows 2 when on FMC navigation then switches to zero when approach selected. Still doesn’t come in on centre line though - usually left or right off the runway (just on).
