### ISSUE TITLE
Cockpit View Disappears While Adjusting Pilot Seating Position

### ISSUE THREAD

**Issue by Viper787** [magknight/787aviatorsTracker#153]
**Describe the bug**
I'm having an issue with the cockpit: On the ground at any airport - where as I place my position in the left seat, and then as I use the </> keys to move fwd and back, the "sky" scenery outside the cockpit windows overtakes the entire view and you cannot see any of the airport structures. If it hasn't been addressed, I'll try to do a video and post it. Looks like maybe the headrests have something to do with it?  (1.4.0b1) https://youtu.be/uvXnhB6TwOM

**To Reproduce**
Load 1.40b1 on a Mac 10.12.6, Enter Cockpit in 3D mode, use < or > keys to position yourself in pilot's left seat, then using the same keys manipulate your view around the cockpit as shown in the YouTube Video

**Expected behavior**
Airport objects and tarmac _should **NOT** disappear_, and your view should remain consistent.

**Screenshots**
https://youtu.be/uvXnhB6TwOM

**Desktop (please complete the following information):**
 - OS: MacOS 10.12.6
 - X-Plane version 11.36R2
 - Version 1.0.4b1

**Additional context**
Thank you!

**Comment by aeroniemi** [comment]
It's an x-plane shader issue, feel free to file a bug with LR, but i don't expect it to change any time soon

**Comment by Viper787** [comment]
Hi Alex, Thank you but can you explain:

a) Why It does NOT happen in any previous version of the 787-9?

b) Why I don’t see the type of occurrence on any other plane (almost 50 aircraft) that I own/fly?

c) If it IS indeed an X-Plane issue can you point me the culprit in you code that causes it to happen?

Thanks!

**Comment by aeroniemi** [comment]
I've been told it's an issue with the xplane shaders - I tried it with
1.3.5 and the same thing happens - when you go inside a obj in interior
view externals disappear - we don't have any code that affects the views. A
potential fix might be to move the headrest/seat further back, but i don't
see it as a worthwhile option

**Comment by Viper787** [comment]
Thanks again, I guess that I’m lucky with 1.35 :) not seeing that at all.

Cheers!
