### ISSUE TITLE
RA callout for 2500 feet goes off at 500 feet, alongside the 500 feet callout

### ISSUE THREAD

**Issue by MirageSieben** [magknight/787aviatorsTracker#154]
**Describe the bug**
When descending, the radio altimeter callout for 2500 feet does not trigger on the correct altitude, and instead goes off at 500 feet alongside the the 500 feet callout.

**To Reproduce**
Descend the aircraft from any altitude higher than 500 feet. The radio altimeter callout for 2500 feet and 500 feet should trigger at the same time.

**Expected behavior**
The radio altimeter callout for 2500 feet should trigger at 2500 feet.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.36r2
 - Version 1.4 Beta 2

**Comment by aeroniemi** [comment]
should be fixed for the next version
