### ISSUE TITLE
Wrong spot (or missing spot) for rear strobes

### ISSUE THREAD

**Issue by Sdozer** [magknight/787aviatorsTracker#156]
Link to the video: https://drive.google.com/open?id=1jg1B4rjFlIKS2veH_uUN5B4E5LKPz9Mq

**Describe the bug**
We have one strobe flashing out of nowhere

**To Reproduce**
Get strobes on and take a look at the tail near the APU exhaust

**Expected behavior**
You'll see flashing strobes out of the fuselage

**Screenshots**
Video below

**Desktop (please complete the following information):**
 - OS: Win8.1
 - X-Plane version 11.36
 - Version Mag 787 beta1

**Comment by magknight1** [comment]
Lights have been relocated to correct position.
