### ISSUE TITLE
Sink rate alarm with AP when descending

### ISSUE THREAD

**Issue by Sdozer** [magknight/787aviatorsTracker#158]
Link to the video: https://drive.google.com/open?id=1IFMqFNdAB2O-WDu1wtU9R2r6oX1QwD7f

EXPERIMENTAL FLIGHT MODEL: ON

**Describe the bug**
When descending with AP the planes gives a high descent rate, about -4000 fpm, the planes get much nose down attitude and we get sink rate alarm

**To Reproduce**
Do a flight, get your cruise altitude, then start descending with AP

**Expected behavior**
Sink rate alarms 

**Screenshots**
Video above

**Desktop (please complete the following information):**
 - OS: Win 8.1
 - X-Plane version 11.36
 - Version Mag787 beta1

**Comment by aeroniemi** [comment]
You've asked the plane to descend on FLCH; the definition of FLCH is "hold current speed with MIN/MAX throttle using pitch", and that's exactly what it's doing. If you don't want to have such a high VS, just take manual throttle control. The sink rate alarm activates at around 4000fpm as expected
