### ISSUE TITLE
Overlapping objects/textures

### ISSUE THREAD

**Issue by Sdozer** [magknight/787aviatorsTracker#159]
Link to the video: https://drive.google.com/open?id=1zqqneCZ0LGNdHqcMRrM6ND5-r_VPjnYX

**Describe the bug**
When you look at the intersection between flaperon and inner flap you'll see that they are overlapping each other, specially on landings

**To Reproduce**
Do a landing with everything set up (full flaps, autobrakes e spoilers armed) and take a look at the flaperon and inner flap, I only observed this at the right wing, don't know if we get that at the other side

**Expected behavior**
flaperon goes up and down, and when gets down it collides with flaps

**Screenshots**
Video above

**Desktop (please complete the following information):**
 - OS: [Win 8.1]
 - X-Plane version [11.36]
 - Version [Mag 787 beta1]

**Comment by aeroniemi** [comment]
Known to exist in 1.3.x also, no real change to the wings in 1.4.0, but they will probably get looked at in 1.5.0
