### ISSUE TITLE
Elevators are backwards

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#16]
**Describe the bug**
Elevators move in opposite direction.

**To Reproduce**
Look at elevators when moving joystick.

**Expected behavior**
Push the joystick forward and elevators move down. <-- but atm this is opposite

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.32
 - Version 1.20b

**Additional context**

**Comment by aeroniemi** [comment]
Modelling issue only, it works in the flight model, but not 3d
