### ISSUE TITLE
Sounds overall

### ISSUE THREAD

**Issue by DeltaYankee2** [magknight/787aviatorsTracker#161]
**Describe the bug**
overall sounds inside the cockpit is very low. Sound levels are max in Xplane, and XPlane volume mixer is set to max.  Speaker control is almost to max - This is where the sounds are at a good level but then all other sounds are extremely high

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.36r2]
 - Version [e.g. 113601]

**Additional context**

**Comment by aeroniemi** [comment]
which sounds specifically are you talking about? In my install the sounds are all at a reasonable volume when all the sliders are central

**Comment by audiobirdxp** [comment]
cant reproduce at all..?

**Comment by OldGroof** [comment]
Sounds are at the correct levels for me?
