### ISSUE TITLE
Pause at Top of Descent

### ISSUE THREAD

**Issue by DeltaYankee2** [magknight/787aviatorsTracker#162]
**Describe the bug**
Paused at TOD, with setting turned OFF.

Cannot unpaused until going to Xplane menu options and entering the settings page or similar and "returning to flight"

From the log:
[AERO787 INFO]: [LUA]: "module"	was true
[AERO787 INFO]: [LUA]: "module"	now true
[AERO787 INFO]: [LUA]: "module"	Paused 37.248016357422 before top of descent
[AERO787 INFO]: [LUA]: "module"	was true
[AERO787 INFO]: [LUA]: "module"	now true
[AERO787 INFO]: [LUA]: "module"	Paused 37.248016357422 before top of descent
[AERO787 INFO]: [LUA]: "module"	was true
[AERO787 INFO]: [LUA]: "module"	now true
[AERO787 INFO]: [LUA]: "module"	Paused 37.248016357422 before top of descent
![787 TOD](https://user-images.githubusercontent.com/56453879/66873994-c6776f80-efa1-11e9-9f40-6570e506e643.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.2.0B1]

**Additional context**

**Comment by aeroniemi** [comment]
Please send the whole log, it's gonna prove important here

**Comment by aeroniemi** [comment]
When the pause at TOD event occurs it automatically turns pause at TOD off, so it's likely it was turned on before it actually happened - it's not been reportered elsewhere to be happening by chance

**Comment by DeltaYankee2** [comment]
No issue on a flight I made last night. I checked the EFB settings before the preflight, it was set to off. Maybe just a gremlin?    It's not an option I turn on and use.
