### ISSUE TITLE
No autopilot disconnect sound

### ISSUE THREAD

**Issue by DeltaYankee2** [magknight/787aviatorsTracker#163]
**Describe the bug**
No AP disconnect sound 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.2.0B1]

**Additional context**

**Comment by aeroniemi** [comment]
is this the case in b2? - please fill out all of the fields
How are you disconnecting the autopilot?
does it happen in all disconnect scenarios, including when the autopilot automatically disconnects due to out-of-range inputs?

**Comment by aeroniemi** [comment]
suggests there is an issue if clicking the APP button is disconnecting the autoflight
