### ISSUE TITLE
IAS ( )MACH button

### ISSUE THREAD

**Issue by DeltaYankee2** [magknight/787aviatorsTracker#164]
**Describe the bug**
The IAS () MACH button above the speed selector presses in and out when decreasing the selected speed - Does not do this when increasing selected speed 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.2.0B1]

**Additional context**

**Comment by aeroniemi** [comment]
should be fixed for b3

**Comment by DeltaYankee2** [comment]
Beta 3 - Fixed!  thanks
