### ISSUE TITLE
Plane Stalls after takeoff

### ISSUE THREAD

**Issue by KXRicciardo3** [magknight/787aviatorsTracker#165]
**Describe the bug**
After I took off, at 4000ft I turned on autopilot and while after climbing through 6XXX ft, the airplane suddenly started to stall. And on the MFD, there is a yellow word saying 'MAIN BATTERY DISCH' and then with the stall, the plane had no more power and the I crashed.

**To Reproduce**
I have no idea of how to reproduce this bug again. As I took off from EGLL, climbing at 6000ft, the plane suddenly stalled, engines went to idle, no power from the engine.

**Screenshots**
**MFD saying 'MAIN BATTERY DISCH'**
![image](https://user-images.githubusercontent.com/56505492/66909784-f07f6f00-f03f-11e9-81ca-1e9b76d67349.png)
**All my GENS are on**
![image](https://user-images.githubusercontent.com/56505492/66909845-0bea7a00-f040-11e9-979b-73a00bee8355.png)

**Desktop**
 - OS: Windows 10
 - X-Plane version 11.36
 - Version 1.4 Beta 1

**Additional context**
That was my first beta flight, and I got this after takeoff. I was doing a test flight from EGLL and doing a 30 minute cruise and land back at EGLL. Nearly reaching 8000ft, I just crashed......

**Comment by aeroniemi** [comment]
fuel flow is nil - have the cutoff switches decided to set to cutoff?
either way, neither of your engines are running, so it doesn't surprise me that it's stalling

**Comment by KXRicciardo3** [comment]
Nah, fuel pumps are on and fuel switches are on run.
