### ISSUE TITLE
Linux COMM file missing

### ISSUE THREAD

**Issue by Ace1772** [magknight/787aviatorsTracker#167]
**Describe the bug**
On Linux with java 11.0.3 - the latest beta when I push the battery button it goes on but nothing happens.  I turn the APU to start - it stays on start and nothing happens.  EFB won't come on and not of the screens come on.  I still have 1.3.10 loaded - with this same configuration that version loads properly - this was my test to ensure it wasn't a faulty java install.  Running under Ubuntu 19.10 (released this week).  With earlier beta's I had an issue where it crashed before loading the plane.  It complained about lin.xpl.   With the latest beta that is not happening for some reason as I get into the cockpit - just not functional.  Log (attached) appears to show the javaxp plugin loading successfully from the entries I saw.

**To Reproduce**
Happens every time I load the latest 1.4 beta.

**Expected behavior**
Was hoping the plane would start :)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - X-Plane version 11.40b8
 - Version [e.g. 1.4.0b4

**Additional context**
Attached is the log file from my last attempt and a screen shot of the only relevant part my non-Xplane developer eyes noticed - maybe you'll notice more.   Note: I've not used github before - these attachments are showing as links - hope that works - if it doesn't let me know and I'll try again.
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/3746871/Log.txt)
![image](https://user-images.githubusercontent.com/56766928/67147970-f5bf0280-f267-11e9-92ec-4eb0a6b2600a.png)

Note:  With the exception of these periodic issues - thanks for the wonderful work on this aircraft!  Dying to take the beta up and see what's new.

**Comment by aeroniemi** [comment]
do you have a file at plugins/sasl/data/modules/mfd/types/comm/left/commPageATCcore.secured?

**Comment by aeroniemi** [comment]
i don't see why there would be any difference between b3 and b1 because none of the core SASL files, or any of the COMM page calling/MFD calling has changed - the files won't have been replaced

**Comment by Ace1772** [comment]
Yes - and the case appears to match what you indicated below.  As linux
is case sensitive - if the case you indicate below is correct then it
matches.  Are these files new with 1.4?


-----Original Message-----

**Comment by Ace1772** [comment]
That is quite likely me.   I initially had issues with Java where
1.3.10 wouldn't load either.  While trying to sort that I had I had
changed the mag787.config file to point to the path to the java jar
file (Omar added that feature for me a while back - I have so much
ortho I filled my drive so to save space I put my payware aircrafts on
another drive and created a symbolic link in linux from the aircraft
folder so they are found.  Apparently when trying to locate that jar
file the code was not properly following the link and finding it so he
gave me the option of specifying the actual path to the jar which
resolved my issues in previous versions.  Then - Omar suggested I put
the lin.xpl from the previous version in as well which didn't help.  I
tried java 11.0.4 which actually caused the same issue I'm having now -
Omar said on Linux it should be only 11.0.3 but that was causing the
crash.  I believe at that point I removed 11.0.4 AND 11.0.3 and
reinstalled 11.0.3 from scratch AND put the 1.4 lin.xpl back in (I
assume it didn't change though since Omar suggested using the other
one) - and that got it loading again.  but The battery won't turn on
anything now just like when I had 11.0.4.  Sorry for the wordy response
- Just  wanted to point out perhaps I shouldn't have mentioned my
earlier issues as there is a good chance they were self induced while I
tried to debug - I broke my rule against making too many changes at
once. ☹

One important point though - on the off chance the symbolic link was
causing issues with the file you asked about in the previous message I
copied the whole aircraft to my Aircraft folder which has NO symbolic
link.   I changed mag787.config back to the default and I get in the
cockpit - was hoping that would turn on but same issue.  In case the
sym link did cause issue I'll include the new log file here as
well.  It looks about the same to my untrained eyes though ☺

Note I checked the permissions as well on that file in plugins from the
last email - I have read access to the file so it's not that.


-----Original Message-----

**Comment by aeroniemi** [comment]
The COMM pages are new in 1.4.0, but as they are cased correctly and run by SASL and not Java there shouldn't be any cross-platform compatiblity issues, especially as it appears to be working on macOS which follows the same naming policy - have you tried re-downloading 1.4.0 and replacing the files, in case that file has become corrupted?

**Comment by Ace1772** [comment]
I will redownload 1.4b1 and then 1.4b3 over it in the aircraft folder
so the symbolic link doesn't come into play and report back shortly.

Thanks, 

-----Original Message-----

**Comment by Ace1772** [comment]
Alex, 

Reloaded everything - 1.4b1 then 1.4b3.  Took me this long to get it
loading again for some reason.   Couldn't get it to load the java2xp
plugin on the non symlink folder so put it back in the folder with the
link - mag787.config points to the jar file.  Load up the aircraft -
had to reactivate (which also reassured me I'm using the correct re-
installed version) - restarted again same issue.



-----Original Message-----

**Comment by aeroniemi** [comment]
potential issue in code resolved and releasing in b4

**Comment by Ace1772** [comment]
Wonderful - I'll watch for it - Thanks Alex!

-----Original Message-----

**Comment by Ace1772** [comment]
Alex, 

Thanks - that resolved that issue.  Everything turned on as
expected.  Took it up for a short flight - love what you guys have done
with it.   I have just one issue remaining - the PFD shows no speed
rather then the v speeds even though the EFB calculated the
VSpeeds.  It's late tonight but I'll enter another bug for that one
tomorrow.  This one can be closed - do I do that or do you?

Appreciate the quick response on this!

Mike

-----Original Message-----
