### ISSUE TITLE
Beta 3 CTD

### ISSUE THREAD

**Issue by YYZatcboy** [magknight/787aviatorsTracker#168]
**Describe the bug**
On pushback from EGKK with a flight plan loaded to CYYC I started the engines. The overhead engine start switches engaged but when i turned on the fuel levers for autostart I had a CTD.

**To Reproduce**
Load at EGKK
Load the WJA livery
Load a flight plan to CYYC
Complete performance data (rwy 26L and full aircraft)
Set up better pushback
begin pushback
Turn on engine start swtiches overhead
Turn on left and right fuel cutout switches. 
observe CTD.

[Log.txt](https://github.com/magknight/787aviatorsTracker/files/3747320/Log.txt)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Mac os 10.14 (latest)
 - X-Plane version Latest full version
 - Version 1.40 B3

**Additional context**

**Comment by aeroniemi** [comment]
It looks to be a sound driver issue
Does the same thing happen if you unplug the USB audio device?

**Comment by YYZatcboy** [comment]
I will look and see if I can get it to happen again and if I do I will unplug my audio interface and report back either way.

**Comment by YYZatcboy** [comment]
Was able to reproduce the crash on pushback, though this time the engines were half way started. Trying again with no audio interface this time.
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/3747798/Log.txt)

**Comment by aeroniemi** [comment]
Ok, we're getting somewhere
That crash is caused by a different issue, which is either betterpushback (which wrote the last lines of the log) or Java2XP, which is unhappy because of the conflict with the AFL X-Jets global plugin - try removing the latter and seeing if this still happens

**Comment by YYZatcboy** [comment]
Audio devices unplugged and still a CTD.
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/3747804/Log.txt)

**Comment by YYZatcboy** [comment]
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/3748387/Log.txt)
CTD Again. I am going to try a different gate because the only thing so far that I can find in common is the gate and the pushback.

**Comment by YYZatcboy** [comment]
Different gate, CTD. It appears that the CTD is happening when the aircraft starts its turn using better pushback. In both cases we wanted to turn nose right. I haven't tried nose left yet.
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/3748406/Log.txt)

**Comment by YYZatcboy** [comment]
CTD still. This is the only aircraft where I get a CTD while pushing back. I am going to try one more time before bed but this time I am going to turn the opposite way and see if that is the issue.
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/3750405/Log.txt)

**Comment by YYZatcboy** [comment]
Was able to push back with the same turn direction in YYC. Whatever it is seems to be related to EGKK.
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/3750447/Log.txt)

**Comment by aeroniemi** [comment]
> 
> 
> CTD still. This is the only aircraft where I get a CTD while pushing back. I am going to try one more time before bed but this time I am going to try from a different airport and see if that is the issue.
> [Log.txt](https://github.com/magknight/787aviatorsTracker/files/3750405/Log.txt)

The only logging that seems to exist in all cases appears to be from betterpushback: 
```2019-10-21 05:19:27 BetterPushback[tug.c:1545]: assertion info.normalY > 0.0 failed (0.000000 > 0.000000)
Backtrace is:
1   mac.xpl                             0x000000007f1ec313 tug_draw + 739
2   mac.xpl                             0x000000007f1c3f3a draw_tugs + 474
3   XPLM                                0x0000000011262bd5 _ZL23XPLMDispatchDrawingHookiii + 127
4   XPLM                                0x0000000011262a6d _Z24XPLMDisplayDoDrawingHookiiPv + 81
5   X-Plane                             0x00000001044e6760 _Z16XPPDoDrawingHooki + 1136
6   X-Plane                             0x0000000103891b62 _Z29OGL_scenery_per_dome_3d_solidP10xcam_class14rendering_passRK14render_setup_ti + 146
7   X-Plane                             0x0000000103d4c14b _ZL22WORLD_scene_per_renderP15OGL_framebufferi14rendering_passRK15ZOOM_platform_tifffPKfPiPff + 16987
8   X-Plane                             0x0000000103d4eee7 _Z21WORLD_scene_per_frameP13xplane_windowP15OGL_framebuffer + 2407
9   X-Plane                             0x00000001041ceacc _Z10APP_updatev + 4780
10  X-Plane                             0x0000000103710483 _Z22MACIBM_post_event_procv + 819
11  X-Plane                             0x00000001045c04fb WIN_run_app + 43
12  X-Plane                             0x00000001041d0799 main + 73
13  libdyld.dylib                       0x00007fff5c2da3d5 start + 1```
If I were to guess, it's probably a issue with betterpushback's saved routes for EGKK getting a bit corrupted - I think it saves routes in the scenery folder, try removing that file and giving it another go

**Comment by aeroniemi** [comment]
I assume this is no longer happening?

**Comment by Viper787** [comment]
Still happening for me even w b5 and a new key from the store.
