### ISSUE TITLE
400 feet Radio Altimeter (RA) callout goes off during climb

### ISSUE THREAD

**Issue by MirageSieben** [magknight/787aviatorsTracker#169]
**Describe the bug**
The 400 ft RA callout goes off during climb while passing said altitude.

**To Reproduce**
Climb past 400 feet, the RA callout will be audible.

**Expected behavior**
The RA callout should only occur during descent and approach.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.36r2
 - Version 1.4 Beta 3

**Comment by aeroniemi** [comment]
is it only the 400ft callout?
If so, it's expected if it's enabled in the liverySettings.json file (which it is by default)

**Comment by MirageSieben** [comment]
> is it only the 400ft callout?
> If so, it's expected if it's enabled in the liverySettings.json file (which it is by default)

Yes, it is only for the 400 feet callout.
I didn't find any lines related to the Radio Altimeter callouts in the json file. Do I have to add that myself?

**Comment by aeroniemi** [comment]
They're in the GPWS section; if you're using a config from before 1.4.0 you'll need to copy the GPWS section from the default config, or just delete the file and let it regenerate automatically

**Comment by OldGroof** [comment]
I found the callout setting in the json called like 400up or something. Toggling it to false turned this call out off as expected. However I get the feeling the sound is supposed to be the FO saying it, not GPWS?
