### ISSUE TITLE
Ailerons Move to far 'up'

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#17]
**Describe the bug**
The ailerons move way too far 'up', however they move the correct amount 'down'

**To Reproduce**
Steer with a joystick or with mouse whilst looking at the ailerons.

**Expected behavior**
Less movement

**Screenshots**
![B7879_7](https://user-images.githubusercontent.com/39658757/56867755-215fdf00-69e1-11e9-90bc-573de4302764.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.2.0B1]

**Additional context**

**Comment by aeroniemi** [comment]
Hydraulics set max up to 35 and max down to -45, expected +20 and -40

**Comment by aeroniemi** [comment]
I can fix it in modelling as i have right now, or make a better fix in hydra
