### ISSUE TITLE
Nose wheel spinning too fast

### ISSUE THREAD

**Issue by ZeeMuffenMan** [magknight/787aviatorsTracker#170]
**Describe the bug**
V/S nob is inverted. Scrolling downwards makes it go up (+ V/S) and vice versa....
Front wheel moves before the plane moves (rip physics lol). 

**To Reproduce**
Steps to reproduce the behavior: Move V/S wheel 
Taxi and you'll see the wheel move strangely.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - X-Plane version [11.40B8]
 - Version [e.g. 1.4B3]

**Comment by aeroniemi** [comment]
VS knob is acting in the right direction as per the arrows next to it

**Comment by ZeeMuffenMan** [comment]
> VS knob is acting in the right direction as per the arrows next to it

It seems to be fine in B4 - strange. 
Thank you

**Comment by TheAustralianAviator** [comment]
Same here, I get this issue even when the park brake is on, it's got me puzzled

**Comment by magknight1** [comment]
Dataref wasn't set to the correct degrees.
