### ISSUE TITLE
Terrain Radar button

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#172]
**Is your feature request related to a problem? Please describe.**
TERR Button not working

**Describe the solution you'd like**
The Terrain Radar plugin https://forums.x-plane.org/index.php?/files/file/37864-terrain-radar-vertical-situation-display/ is working fine with the Magknight! It is even displayed in the ND!
Would it be possible to set the TERR Button functional too turn on and off terrain radar?

**Additional context**
![B7879 - 2019-10-20 13 43 37](https://user-images.githubusercontent.com/56799893/67163819-c72e4e00-f373-11e9-8ba7-84124bc570bd.png)

**Comment by aeroniemi** [comment]
can be done post 1.4.0
