### ISSUE TITLE
Some Issues with 1.4 BETA3

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#173]
I hope this helps improve the Aircraft
**Describe the bug**
1. EFB ist cut at the Bottom and has a big input delay
2. The right FMC Keyboard only inputs into the left one. Input only works with pop out FMC
3. Looking inside the Cabin is killing FPS when main Power is turned on (Video)
4. The A/T switches disconnects when breaking or turning while taxi.
5. The Croosfeed seems not to work, on my 4 testfligts it has no effect(no problem in BETA2)
6. V/S does not activate right (Video) No problems in BETA2
7. When activating VNAV the aircrafts start to climb very fast, and overrun the speed restrictions. (Video) (no problem in BETA2)
8. The Aircraft turns way to soon, doesnt matter what turn angle I set. No problem in cruise but a big problem when aligning RWY (Video) (No Problem in BETA2)
9. LOC dont work correct it alway´s is way of the RWY Center. Tryed with different wheater and even withoute any wind! (Video) (no problem in BETA2, doing the same thing as alway´s)
10. When disengaging A/P no sound is played, doesnt matter if using BAR or Button (Video) 

**To Reproduce**
pleas watch the Videos

**Expected behavior**
1. Display should be fixed and the delay should be fixed
2. right keyboard should input into right FMC
3. looking into teh Cabin should not Kill teh FPS, when its not doing so when no main power is turned on.
4. They should not turn off I think? No other Aircraft shows this behavior!?
5. Crossfeed should balance fuel tanks
6. Should be possible to activate V/S after 400ft or 1000ft climb after Takeoff
7. VNAV A/T should not overspeed and climb rate should be realistic. VNAV behavior should be tweaked or the Aircraft perfromance
8. Aicraft should follow the magenta line in ND
9. LOC should aligne centered for ILS etc...
10. disengage sound should be played

**Screenshots**
![B7879 - 2019-10-12 08 35 45](https://user-images.githubusercontent.com/56799893/67164381-30b15b00-f37a-11e9-88f7-09e7c641c875.png)
![B7879 - 2019-10-18 13 59 14](https://user-images.githubusercontent.com/56799893/67164382-3149f180-f37a-11e9-9b5e-9d0e31c8bed1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 1.36
 - Version 1.4 BETA3

**Additional content**
LOG Files:
[Cycle Dump.txt](https://github.com/magknight/787aviatorsTracker/files/3748222/Cycle.Dump.txt)
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/3748223/Log.txt)

Videos:
1. Video Cabin FPS and VNAV
https://youtu.be/nyNM_wOmhac

2. Video longer with Issues
https://youtu.be/YcTgdmLFt0U

**Comment by aeroniemi** [comment]
added a condition to not disengage autothrottle if below 40kts
