### ISSUE TITLE
Information on ND (Navigation Display)

### ISSUE THREAD

**Issue by rubencaldas** [magknight/787aviatorsTracker#174]
**Describe the bug**
All information on Navigation Display is very very small (tall of fonts), and it's impossible read wich is each fix, or any information over display.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.40b9

**Comment by aeroniemi** [comment]
No change expected before the release of the fully custom CDU/FMS as it's not possible to draw default routes using custom technologies

**Comment by aeroniemi** [comment]
kinda fixed with cygnus 1.7.18
