### ISSUE TITLE
Impossible navigate aproach non preccision

### ISSUE THREAD

**Issue by rubencaldas** [magknight/787aviatorsTracker#175]
Navigation display, no show a "wind rose" or HSI, for intercept VOR radials or  NDB tracks.

**Comment by aeroniemi** [comment]
Is this any different to 1.3.10?

**Comment by rubencaldas** [comment]
Yes any versio. But I think I've explained myself wrong, If I want fly follow radials or courses VOR, I select on FMS (Radio Pages)  course but I have not how to do, because on Navigation Display don't appear a HSI for say to me where I am from VOR radial. do you understand to me? I you want I explain to you with disscord. I am Ruben-AEA682

**Comment by aeroniemi** [comment]
HSI is on the ND
