### ISSUE TITLE
A/T Arm switches

### ISSUE THREAD

**Issue by Sdozer** [magknight/787aviatorsTracker#177]
This maybe just a question. The switches look out of level, both armed but the right one looks a bit down comparing to the left one. Is it your plans to make them look like that?
![B7879 - 2019-10-20 23 29 11](https://user-images.githubusercontent.com/56571798/67253998-0e3e4100-f451-11e9-8782-aeac92dcd7b9.png)

**Comment by aeroniemi** [comment]
made close enough that it's not really noticable
