### ISSUE TITLE
EFB keyboard a bit out of screen

### ISSUE THREAD

**Issue by Sdozer** [magknight/787aviatorsTracker#178]
**Describe the bug**
See attached image 

**To Reproduce**
Go to any screen inside the EFB and open the keyboard

**Expected behavior**
You'll see the lower part a little bit out of screen

**Screenshots**
![B7879 - 2019-10-20 23 13 09](https://user-images.githubusercontent.com/56571798/67254335-d9cb8480-f452-11e9-9029-0fe9b38439c0.png)

**Desktop (please complete the following information):**
 - OS: [Windows 8.1]
 - X-Plane version [11.36]
 - Version [e.g. 1.4.0B4]

**Comment by aeroniemi** [comment]
temporarily fixed in b5, needs modelling/mapping change

**Comment by magknight1** [comment]
Texture moved to alocate the keyboard.
