### ISSUE TITLE
Plane bounces when flaps are added

### ISSUE THREAD

**Issue by Sdozer** [magknight/787aviatorsTracker#179]
This was catched within beta2 with Experimental Flight Model ON, but I've confirmed the same situation with beta4 and Experimental OFF

Video link: https://drive.google.com/open?id=1kqemChfchfp1mFbewwaS-JPpr8AtHfz3

**Describe the bug**
The plane bounces up and down when you add flaps

**To Reproduce**
Get a leveled flight with A/P on and start to add some flaps

**Expected behavior**
The plane will bounce up and down a couple of times struggling to maintain it's flight level

**Screenshots**
Video above

**Desktop (please complete the following information):**
 - OS: [Windows 8.1]
 - X-Plane version [11.36]
 - Version [1.4.0 b2 and b4]

**Comment by aeroniemi** [comment]
does it still happen post b3?

**Comment by Sdozer** [comment]
> does it still happen post b3?

As I've said in the post, I catched this at beta4 too, but now at beta6 this is way better! The plane still bounces a bit, but I think its normal behavior, but I'm not a real pilot (yet) to confirm that this behavior is realistic or not

**Comment by matthew007800** [comment]
Yes, that is normal. Planes do bounce slightly when flaps are added. They don't maintain an exact course. Flaps increases the lift, it causes it to go up slightly.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
