### ISSUE TITLE
Throttle levers don't move

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#18]
**Describe the bug**
Throttle levers don't move
**To Reproduce**
Use throttles

**Expected behavior**
They should move.

**Screenshots**
![B7879_9](https://user-images.githubusercontent.com/39658757/56867946-f5922880-69e3-11e9-83dc-38e20dcd9100.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.32
 - Version 1.2.0B

**Additional context**

**Comment by aeroniemi** [comment]
potentially an issue for @magknight1 or @mob9221 (if you had changed the logic there for the spoilers)

**Comment by aeroniemi** [comment]
The throttles 3d are attached to a separate dataref to the flightmodel ones; they're not linked either way
