### ISSUE TITLE
Bank angle alerts within 30 degree

### ISSUE THREAD

**Issue by Sdozer** [magknight/787aviatorsTracker#180]
Catched with betas 1 and 4, exp model ON and OFF, manually or A/P flying

Video link: https://drive.google.com/open?id=117uHlH7stWvA1Ml90Zu_Eurc40wU29Aw

**Describe the bug**
The plane gives Bank Angle alerts within 30 degree turn limits

**To Reproduce**
Do a flight make some turns within 30 degree or less

**Expected behavior**
You'll have bank angle alerts 

**Screenshots**
Video above

**Desktop (please complete the following information):**
 - OS: [Win 8.1]
 - X-Plane version [11.36]
 - Version [1.4.0 b's 1 and 4]

**Comment by aeroniemi** [comment]
below 1500ft the bank angle warnings occur at lower angles (15, 20, 30) - i've set that for 20, 25, 30 in b5
above 1500ft it's set to 35, 40 45
