### ISSUE TITLE
Cold and Dark external lights on

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#181]
**Describe the bug**
When reloading the Aircraft, Landing lights, strobe, NAV and taxi lights are turned on?
Also the engines are spooling down?
After reloading the Aircraft the Battery on Switch sound isn't played anymore?
After reloading there Aircraft all Displays keeps black?

**To Reproduce**
Start a new flight with Cold and Dark settings and reload the Aircraft (Video)

**Expected behavior**
When reloading the Aircraft it should be in Cold and Dark status again!
Haven´t checked what happens if I turn on start with engines running!?

**Video**
https://youtu.be/c5H-TzY481Y

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.36r2
 - Version 1.4 BETA4

**LOG File**
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/3754660/Log.txt)

**Comment by aeroniemi** [comment]
the engines spooling down is the nature of how the soft reload process works, you just change the state of stuff, and wait for the physics to catch up.
I'm not able to reproduce the lights being on - for me they are set off if engines running is unchecked

**Comment by KBNOtaku** [comment]
This only happens when using the reload option in the menü!
when I load a other aircraft and then again load the 787 everything is fine!
So what could be the problem?
What about the other problems, Batter switch sound, and dark display´s?

**Comment by aeroniemi** [comment]
On battery power you aren't able to change the states of the lights, they act in a locked low-power configuration. i've added a config for b6 to turn off the default x-plane lights when starting without engines running. I can't reproduce the displays not working when reloading, even after watching the video

**Comment by aeroniemi** [comment]
fixed for b6
