### ISSUE TITLE
EFB says you're using RR engines but they're actually GE

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#185]
**Describe the bug**
In the performance calculate on the EFB it says "787-9/TR1000-C2" Which I assume are the engines for that airframe. However atm only GE engines are available.

**To Reproduce**
Look at the perf page of the EFB

**Expected behavior**
I guess it should say the same as the engines fitted.

**Screenshots**
![B7879 - 2019-10-23 14 47 31](https://user-images.githubusercontent.com/39658757/67432224-cef12b00-f5dd-11e9-94b9-4bffe3165458.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.35?(not the latest update but only a version behind)
 - Version 1.4.0b4

**Comment by aeroniemi** [comment]
dynamic from B6
