### ISSUE TITLE
Engine Oil Temperature

### ISSUE THREAD

**Issue by YYZatcboy** [magknight/787aviatorsTracker#188]
**Describe the bug**
The oil temperature goes into the amber on Taxi. The oil temperature shouldn't be that high unless using max thrust for extended periods.

**To Reproduce**
Taxi and observe the oil temperature

**Expected behavior**
The Oil temperature should not go into the amber band

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 10.14
 - X-Plane version latest stable
 - Version 1.40 B5

**Additional context**

**Comment by matthew007800** [comment]
Not something I can edit

**Comment by aeroniemi** [comment]
rc1
