### ISSUE TITLE
Optimum cruise is in the overspeed warning band

### ISSUE THREAD

**Issue by YYZatcboy** [magknight/787aviatorsTracker#189]
**Describe the bug**
Cruising at mach.85 is in the high speed amber band. this is the normal cruise speed and shouldn't be in the overspeed band. 

**To Reproduce**
Cruise at M.85 and observe the speed tape

**Expected behavior**
Should not be in the amber

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 
 - X-Plane version Latest stable
 - Version 1.40 B4

**Additional context**

**Comment by YYZatcboy** [comment]
![B7879 - 2019-10-24 03 26 56](https://user-images.githubusercontent.com/56776929/67472331-2d360200-f60e-11e9-9c31-c798c8507b18.png)

**Comment by matthew007800** [comment]
Not something I can edit, That is on Aeroniemi

**Comment by aeroniemi** [comment]
yellow boundary increased at higher altitudes
