### ISSUE TITLE
Slats Don't Extend

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#19]
**Describe the bug**
Slats don't extend.

**To Reproduce**
Extend flaps and look outside.

**Expected behavior**
They should extend.

**Screenshots**
![B7879_8](https://user-images.githubusercontent.com/39658757/56867977-4144d200-69e4-11e9-8e43-d9ffe242ef5c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.32
 - Version 1.2.0B

**Additional context**

**Comment by mob9221** [comment]
Added slat support 👍
