### ISSUE TITLE
Strobe sequence wrong

### ISSUE THREAD

**Issue by YYZatcboy** [magknight/787aviatorsTracker#190]
**Describe the bug**
The strobes regularly short flash instead of the long LED pulse. It's more like an airbus than a 787. For note of how the LED strobes are supposed to be, check out the zibo LED strobe option.

**Comment by aeroniemi** [comment]
They're doing both in the current release copy as the default ones are on unintentionally

**Comment by aeroniemi** [comment]
duplicate of #111
