### ISSUE TITLE
Flap extension and retraction speeds seem fast

### ISSUE THREAD

**Issue by YYZatcboy** [magknight/787aviatorsTracker#191]
**Describe the bug**
The flaps and slat retraction and extension speeds seem really fast. Almost instant.

**To Reproduce**
Extend and retract the slats

**Expected behavior**
The flaps should extend over a longer period of time and produce more drag at higher flap settings to allow for the aircraft to pitch nose up.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 10.14
 - X-Plane version Latest stable
 - Version 1.40 B4
**Additional context**

**Comment by matthew007800** [comment]
Speed is not an issue
Drag coefficients still in the works.

**Comment by YYZatcboy** [comment]
Not sure why you think the flaps are not moving too fast. I've never seen a Boeing airplane be able to drop from flaps zero to flaps full in under 30 seconds like this airplane does. I will ask crews to time it next time I'm at work if that's helpful but I think the flap extension speed is also a large factor in the bounces we are seeing when dropping flaps.

**Comment by aeroniemi** [comment]
speeds modified a part of flap redesignation
