### ISSUE TITLE
V speeds not uplinking to aircraft

### ISSUE THREAD

**Issue by YYZatcboy** [magknight/787aviatorsTracker#192]
**Is your feature request related to a problem? Please describe.**
It's harder to takeoff properly when the V speeds are not displayed on the PFD. I can't really keep looking down at the EFB to see what the speeds are.

**Describe the solution you'd like**
Have a way to either copy the data directly to the PFD via a button or have a menu on the PFD somewhere to add in the Speeds by hand until the FMC PERF pages are implemented. 

**Describe alternatives you've considered**

**Additional context**

**Comment by YYZatcboy** [comment]
Correct. I calculate them and get no V speed flag on the PFD. No speeds go over either.

**Comment by aeroniemi** [comment]
what is the status of ``mag787/calc/v1`` after you've calculated the vspeeds?

**Comment by aeroniemi** [comment]
@YYZatcboy

**Comment by YYZatcboy** [comment]
I haven't had the time to install data ref editor yet.

**Comment by YYZatcboy** [comment]
They are all 1

**Comment by YYZatcboy** [comment]
1 with NO VSPEED displayed on the PFD
