### ISSUE TITLE
No door frame around FD door when viewed from Cabin

### ISSUE THREAD

**Issue by YYZatcboy** [magknight/787aviatorsTracker#193]
**Describe the bug**
There is no frame around the flight deck door when viewed from the Cabin.
![B7879 - 2019-10-24 03 25 17](https://user-images.githubusercontent.com/56776929/67472232-0b3c7f80-f60e-11e9-839f-771bb22fdf61.png)

**Comment by aeroniemi** [comment]
duplicate of #127
