### ISSUE TITLE
Plane producing too much lift

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#195]
**Describe the bug**
Since the change from Experimental Flight Model to Normal the plane seams to produce too much lift or is too light,
ZFW: 163,995kgs
Fuel: 8,100kgs
Flaps: 30
Vref: 140-150 (I search last night the usual speed for a 789 is around 152kts.)

**To Reproduce**
Perform and approach and watch how the plane handles.

**Expected behavior**
More nose up attitudes in the flare and approach is what I expect at these weights and speeds.

**Screenshots**
https://www.youtube.com/watch?v=igjgp_7LN78&feature=youtu.be
(edit: Wrong video oops)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.40b1
 - Version 1.4.0b5

**Comment by matthew007800** [comment]
known issue, flap drag is incorrect
