### ISSUE TITLE
Flaps one deploys flaps not just slats

### ISSUE THREAD

**Issue by YYZatcboy** [magknight/787aviatorsTracker#196]
**Describe the bug**
Flaps 1 should only deploy the slats, not the flaps.
<img width="528" alt="Screen Shot 2019-10-24 at 1 28 05 PM" src="https://user-images.githubusercontent.com/56776929/67518485-1de0a400-f662-11e9-921c-63e608b9b231.png">

**Comment by aeroniemi** [comment]
This was done in 1.3.0; is there a difference between position 1 on the ground and position 1 above 80kts?

**Comment by aeroniemi** [comment]
flaps redesignation in rc1
