### ISSUE TITLE
Door Window Glass not moving correct

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#199]
**Describe the bug**
When opening only 1 or 2 doors the Windowglass from the Doors are not moving along with it!
When opening all doors the glass moves too.

**To Reproduce**
open only one doore and look at the Door from the outside
look at the video

**Expected behavior**
Window glass moving with each door

**Screenshots**
![B7879 - 2019-10-26 21 08 04](https://user-images.githubusercontent.com/56799893/67625120-15db5c80-f83a-11e9-9b5c-e94c45a603a1.png)
![B7879 - 2019-10-26 21 08 19](https://user-images.githubusercontent.com/56799893/67625121-15db5c80-f83a-11e9-9bb8-32dc315aaf41.png)
Video:
https://youtu.be/6Yx9Dg5K9tc

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.36r2
 - Version 1.4 Beta5

**Comment by magknight1** [comment]
Issue fixed, all windows are in place.
