### ISSUE TITLE
APU door

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#203]
Have the APU door open in the back when the APU switch is on ON/START and close again on OFF. A smooth opening and closing animation would be nice too!

**Comment by aeroniemi** [comment]
distinct link to using the 11.35 apu model, could be done now with some modifications

**Comment by aeroniemi** [comment]
should be done for b6
it involves substantial changes to the apu system which may break other stuff, needs monitoring
