### ISSUE TITLE
Slat Extension 

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#204]
**Describe the bug**

The slats on the Magknight are not extending enough 

**To Reproduce**
Steps to reproduce the behaviour:

Set full slats and cross-reference with real 787 picture 

**Expected behavior**

Slat that extends further to match the real plane 

**Screenshots**

https://i.thick.at/RedeemableSeaSlug.png

https://www.boldmethod.com/images/blog/lists/2015/01/14-facts-about-the-boeing-787-dreamliner/2-small.jpg

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.2.0B1]

N/A

**Additional context**

**Comment by aeroniemi** [comment]
Have you been checking against flaps 20+? The slats don't extend fully till 20 i think

**Comment by OldGroof** [comment]
I have found the same thing however I thought it was to do with the modelling. But having seen the those pictures it's clear that the extension in sim is too small.

**Comment by aeroniemi** [comment]
the position of the flaps in 3d doesn't affect the flight model; they are not directly linked
