### ISSUE TITLE
Paper Style Checklist

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#205]
**Is your feature request related to a problem? Please describe.**

It would be nice if we had a paper-style pull-out checklist like they have in the zibo. 

**Describe the solution you'd like**

Once the cockpit is remodeled. Have it so if you click the shelf area https://i.thick.at/ModeratedClarence.png a checklist pops up like in the zibo https://i.thick.at/MediumSizedDukeOfClarence.png

**Describe alternatives you've considered**

I know the 787 as a digital checklist, but this would be a nice addition. 

**Additional context**

Here is Boeing's 787 paper checklist https://forums.x-plane.org/screenshots/monthly_2018_03/5a9c98720ad7b_B789NORMALCHECKLIST_01Capture.PNG.ed214f4a57ed24e236f776d9f1cd44e3.PNG

**Comment by aeroniemi** [comment]
Not something that will be done for multiple reasons. It'll be unnecessary once integrated checklists are added in the future.
