### ISSUE TITLE
Beacon splash 

### ISSUE THREAD

**Issue by CharlieAlphaLima** [magknight/787aviatorsTracker#207]
I'd like to see the beacon light splash upon the engine cowling, as this is currently not seen at night nor day time.
![image](https://user-images.githubusercontent.com/57408399/68225673-b246f100-ffe8-11e9-8037-f7b1ee9aae28.png)

**Comment by aeroniemi** [comment]
We haven't worked out a way to make it look semi-realistic, so it won't be done before that is figured out. Not gonna change for 1.4.0

**Comment by magknight1** [comment]
Size and magnitude of beacons lights has been increased to generate more spill. It is noticeable at night, some at dusk/dawn, but can't be seen on daylight.

![X-Plane 2019-12-01 19-12-49-40](https://user-images.githubusercontent.com/49568118/69921274-1daca300-146f-11ea-82a6-c6ea1035355d.png)
![X-Plane 2019-12-01 19-12-56-14](https://user-images.githubusercontent.com/49568118/69921275-1daca300-146f-11ea-84f5-1ec9d120875b.png)
![X-Plane 2019-12-01 19-13-02-97](https://user-images.githubusercontent.com/49568118/69921276-1e453980-146f-11ea-9fc4-75d338567f3c.png)

**Comment by CharlieAlphaLima** [comment]
Hi,
Glad to see progress being made. Have to say it is a step in the right direction. Now that you've implemented the beacon splash, would it at all be possible to have the beacon splash cover the bottom half of the cowling as seen in the attachment?
Kind regards
![2019-12-11_10-7-53-718](https://user-images.githubusercontent.com/57408399/70669172-8107b380-1c6d-11ea-8510-8fe0860f3abc.png)
