### ISSUE TITLE
Moving Yoke on Autopilot and Working Tiller

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#208]
**Is your feature request related to a problem? Please describe.**
Yoke and toller does not move

**Describe the solution you'd like**
Yoke to move when autopilot in command. And Tiller to move upon pilot's control. 

**Describe alternatives you've considered**
N/A

**Additional context**

https://i.thick.at/BushierDemetrius.png 

You must push this button to disconnect the nose wheel steering while testing the rudder before taxi.
Some seem to be under the impression that you can “hold the tiller in position to keep the nose wheel centered” ... no, you can’t. The tillers aren’t mechanically linked, and they are not backdriven. The position of the tiller does not reflect the position of the nose wheel.

https://i.thick.at/UncharyLordStanley.png

**Comment by aeroniemi** [comment]
The EFB provides the option to use the roll axis for NWS, for people such as me that don't want an independent yaw/tiller axis
