### ISSUE TITLE
Custom Cursor on Systems page

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#209]
**Is your feature request related to a problem? Please describe.**
Custom cursor on Systems page

**Describe the solution you'd like**
Custom cursor follows mouse like on the EFB

**Describe alternatives you've considered**
N/A

**Additional context**
https://i.thick.at/ChaffierDercetus.png

**Comment by aeroniemi** [comment]
need to identify how to custom cursor is done on legacy style displays, and whether it is feasable to port directly to modern MFD system - not sure
