### ISSUE TITLE
Autopilot is crazy

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#21]
**Describe the bug**
https://gyazo.com/86cded9fb9277fb9f583bc35a6779a66

**To Reproduce**
Fly on autopilot

**Expected behavior**
Not what is shown in GIF

**Screenshots**
See GIF

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.32
 - Version 1.2.0

**Additional context**

**Comment by aeroniemi** [comment]
Autopilot doesn't cope very well with the hydraulic's systems limits on the elevator rate
