### ISSUE TITLE
Air Systems

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#210]
Pressurization is controlled by regulating the two outflow valves. The system is fully automatic (cruise and landing altitude is taken from the FMC), and handles valve positions even during loss of cabin pressure.
In normal operation, cabin altitude remains at or below 6000 feet ...which is lower than, well, any other airliner currently flying, if I’m not mistaken?
The 787 sales pitch is that the lower cabin altitude makes a difference on longer flights, reducing fatigue. Oxygen content remains at 21% and doesn’t vary with altitude, but lower pressure means fewer oxygen molecules for every breath at 8000 versus 6000 feet. So 76% vs 81% respectively, compared to sea level.

https://i.thick.at/IsidorianDiana.png

https://i.thick.at/RedoubledDiomedes.png

**Comment by aeroniemi** [comment]
Air is entirely left up to x-plane's default automatic system, which i think pressurises to a linear point somewhere around 8000. A custom system is on the plan, but not in a hurry
