### ISSUE TITLE
Engine-Anti Ice and Wing-Anti Ice 

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#212]
https://i.thick.at/LobularDoctor.png 

The 787 engine anti-ice system uses bleed air, but the wing-anti ice system is electric.
EAI is shown when the engine anti-ice valve is open, and WAI when the wing anti-ice system is powered.
Automatic engine anti-ice operation is available in flight. Automatic wing anti-ice operation is available in flight, and also on the ground at speeds above 75 knots.
Remember that the WAI indication can remain for quite some time after leaving the icing area as the system goes through the clean up cycle. This removes any residual ice. Leave it in AUTO and it will take care of itself.

I dont think the WAI and EAI on the EICAS is displaying correctly.

**Comment by aeroniemi** [comment]
I don't think it's system-based at present, it's just either on or off based on temperature

**Comment by Viper787** [comment]
In a bleedless aircraft such as the Boeing 787, each engine has two variable-frequency electrical generators to compensate for not providing compressed air to external systems. Eliminating bleed air and replacing it with extra electric generation is believed to provide a net improvement in engine efficiency, lower weight, and ease of maintenance. Source: https://en.wikipedia.org/wiki/Bleed_air
