### ISSUE TITLE
EFB says the airport does not appear to have any runways

### ISSUE THREAD

**Issue by martialblaizot** [magknight/787aviatorsTracker#213]
**Describe the bug**
I am trying to open the airport runways section in the performance tab but a message appears saying that the airport does not appear to have any runways.

**To Reproduce**

**Expected behavior**
A drop down list should normally appear with the list of runways available at the airport.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.36
 - Version 1.4 Beta 1

**Additional context**

**Comment by aeroniemi** [comment]
Please fill out the version information - it's very important

**Comment by martialblaizot** [comment]
Hi sorry about that this is my first time using this platform so I am not yet familiar with it. Thank you so much for looking into it. I saw some people did open an issue about this before but I don't seem to be finding any comment or link solving the issue.

Martial

**Comment by martialblaizot** [comment]
I have now updated the form by the way.

**Comment by aeroniemi** [comment]
Update to 1.4.0beta 6 - this issue was fixed in b3

**Comment by martialblaizot** [comment]
Thank you so much for your help! I will do
