### ISSUE TITLE
Autobrake Settings

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#214]
**Is your feature request related to a problem? Please describe.**
Autobrake settings are missing

**Describe the solution you'd like**
autobrake - RTO, OFF, ARMED, 1, 2, 3, 4, and MAX-AUTO

**Describe alternatives you've considered**
N/A

**Additional context**
https://i.thick.at/UnrequiredGuiderius.png

**Comment by aeroniemi** [comment]
autobrake settings work as close to the real ones as possible using default technology (only missing state 4) - no intention to change before it is possible to do brake-to-exit
