### ISSUE TITLE
Control surfaces bug at pause

### ISSUE THREAD

**Issue by Sdozer** [magknight/787aviatorsTracker#216]
**Describe the bug**
When you pause during flight the control surfaces change angle

**To Reproduce**
I was flying low, at autopilot with full flaps, spoilers armed, gears down, so fly this way then look at wings and pause

Unfortunatelly I could not made a video shot, but I've made some screensshots

**Expected behavior**
You'll see the surfaces changing their angles

**Screenshots**
Unpaused
![Unpause](https://user-images.githubusercontent.com/56571798/68563884-cd24c580-042d-11ea-9bcd-232f46ae59a9.jpg)

Paused
![Pause](https://user-images.githubusercontent.com/56571798/68563947-fb0a0a00-042d-11ea-8979-84f16ce0487e.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 8.1]
 - X-Plane version [11.40r2]
 - Version [1.4.0B6]

**Comment by aeroniemi** [comment]
switches between custom and default datarefs when entering pause to allow for surfaces to work in replay mode. expected behaviour
