### ISSUE TITLE
Plane shadow lacks flying surfaces

### ISSUE THREAD

**Issue by Sdozer** [magknight/787aviatorsTracker#217]
**Describe the bug**
The shadow of the plane looks like a cuban cigar at the ground, it lacks wings, elevators, rudder

**To Reproduce**
Fly low in a sunny day and look at the ground

**Expected behavior**
You'll see the funny shadow 

**Screenshots**
![shadow](https://user-images.githubusercontent.com/56571798/68564380-3a852600-042f-11ea-8e7c-aa10a0b7c8a0.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 8.1]
 - X-Plane version [11.40r2]
 - Version [1.4.0B6]

**Comment by aeroniemi** [comment]
for performance reasons the exterior surfaces (other than the wings) are disabled when indoors - may be able to be changed once fuse rate issue is fixed, likely with CR2
