### ISSUE TITLE
EFB Performance Page - Runway Selection via Scroll Fail

### ISSUE THREAD

**Issue by Viper787** [magknight/787aviatorsTracker#218]
**Describe the bug**

Example Airport: KLAX / cannot choose RNY 24L,24R or 25L,25R
As I understand the intended operation, I should be able to scroll with with my mouse wheel to the desired runway if I cannot see it in the initial choices displayed. When I try to scroll on the runway choices, the EFB changes the airport location instead, and planning is toast.

**To Reproduce**
Steps to reproduce the behavior: I use a Logitech Performa Mouse. Choose airport as described above and try to scroll to westbound departure runways.

**Expected behavior**
I should be able to easily choose any runway at the airport even if I'm departing with a tailwind etc.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac 10.12.6
 - X-Plane version 11.36r2/11.40r2
 - Version 1.4.0b6

**Additional context**

**Comment by aeroniemi** [comment]
https://i.imgur.com/OiTE18D.png
Appears to work fine for me, able to scroll

**Comment by Viper787** [comment]
No sir.. it’s broken please look closely. Thanks!


---------------------------------------------
ACMESTUDIOS | los angeles 
Photo • Video • Aerial (FAA #3975389)
acmestudios.com | acmestudiosla@gmail.com | (C) 424.225.2506
see <http://www.acmestudios.com/> ▴ like <http://facebook.com/acmestudiosla> ▴ tweet <http://twitter.com/acmestudiosla> ▴ pin <http://www.pinterest.com/acmestudios> ▴ gram <http://instagram.com/acmestudiosla>

**Comment by aeroniemi** [comment]
> No sir.. it’s broken please look closely. Thanks!

We can't fix something that we can't reproduce - not an item that will be changed for 1.4.0, but if we get other reproduction instructions from other users we may be able to fix it in the future (code runs in Java, not editable in 1.4.0)

**Comment by aeroniemi** [comment]
nobody has mentioned this since, so assumed no longer an issue - reopen if still existent in latest version
