### ISSUE TITLE
Bank Angle Selector Improvement/ Enhancement

### ISSUE THREAD

**Issue by Viper787** [magknight/787aviatorsTracker#219]
**Is your feature request related to a problem? Please describe.**
Very difficult to set correct Bank Angle due to the way the art is represented on the MCP the knob is at an angle that makes it impossible to be accurate

**Describe the solution you'd like**
A re-design of the knob to make it easier for the pilot to make a quick and correct selection

**Describe alternatives you've considered**
None at the moment

**Additional context**

**Comment by aeroniemi** [comment]
Identified and fixed an issue with the knob showing 30 deg past the end of the cycle, and having an option for 5 deg - no intention to make further cockpit changes before CR2
