### ISSUE TITLE
Gear are stuck

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#22]
**Describe the bug**
Gear don't move when you toggle them via keyboard of via lever in cockpit

**To Reproduce**
Try using gear

**Expected behavior**
They should extend/retract

**Screenshots**
![B7879_12](https://user-images.githubusercontent.com/39658757/56868134-4efb5700-69e6-11e9-8282-0b1fd6a640c0.png)
![B7879_13](https://user-images.githubusercontent.com/39658757/56868140-57ec2880-69e6-11e9-9306-587744bc79c0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.32
 - Version 1.2.0B

**Additional context**

**Comment by aeroniemi** [comment]
Should be fixed in 1.2.0C

**Comment by OldGroof** [comment]
This is fixed in 1.2.0C. Thanks!
