### ISSUE TITLE
fuselage and landing gear bug

### ISSUE THREAD

**Issue by jnmg2014** [magknight/787aviatorsTracker#220]
hello, I found the following errors in beta 7
First, the rear landing gear has no textures, it is only silver
and second, I found a foreign object in the fuselage that would not have to be there, and it is only seen being in that position, in addition to that also from that position the half-dented and deformed fuselage is also seen

![Captura](https://user-images.githubusercontent.com/50252943/69278918-05609c80-0bc2-11ea-9bbd-5af90dc38675.PNG)
![Capturafgh](https://user-images.githubusercontent.com/50252943/69278919-05609c80-0bc2-11ea-9361-b2e616ea0b74.PNG)
![Capturaygyu](https://user-images.githubusercontent.com/50252943/69278920-05609c80-0bc2-11ea-9000-d785b94c5a43.PNG)

**Comment by magknight1** [comment]
Fuselage had the wrong shape around the front lavatory. There were incomplete normal mappings on the fuselage and wing textures, which included landing gear.
