### ISSUE TITLE
Beta7 APU Master Still Does Not Spring Back To On After Starting

### ISSUE THREAD

**Issue by Viper787** [magknight/787aviatorsTracker#221]
**Describe the bug**
APU Master Still Does Not Spring Back To On After Starting Unit

**To Reproduce**
Turn APU to Start - it will remain in Start even after reaching 100% with a stable EGT reading

**Expected behavior**
After startup conditions are met, switch should "snap back" to the ON position.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 10.12.6
 - X-Plane version 11.40r2
 - Version 1.40b7

**Additional context**

**Comment by aeroniemi** [comment]
has anyone else seen this?

**Comment by Viper787** [comment]
Fixed in RC-1 Thank you!
