### ISSUE TITLE
Door interior texture bugs

### ISSUE THREAD

**Issue by Sdozer** [magknight/787aviatorsTracker#222]
**Describe the bug**
Both doors looks like they have pepper sprinkled on it, and the right doors are blue.

**To Reproduce**
Look inside the cabin

**Expected behavior**
You'll see peppered and blue doors :)

I was using default blank livery at 4k resolution 

**Screenshots**
![B7879 - 2019-11-19 18 40 17](https://user-images.githubusercontent.com/56571798/69591136-88be2b80-0fd0-11ea-9a03-9906b8796650.png)
![B7879 - 2019-11-19 18 40 31](https://user-images.githubusercontent.com/56571798/69591149-91166680-0fd0-11ea-965f-3f003bdf8cec.png)

**Desktop (please complete the following information):**
 - OS: [Windows 8.1]
 - X-Plane version [11.40]
 - Version [Mag Beta7]

**Comment by magknight1** [comment]
Normals create different lighting on the doors. Cabin does not have normals yet to compensate.
Pepper effect has been fixed with better baking sampling.
