### ISSUE TITLE
Popup FMC not workin in outside View

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#229]
**Describe the bug**
It is not possible to make any input into the Popup FMC when at the outside view.

**To Reproduce**
Open the Popup FMC and try to use it while in the outside view.

**Expected behavior**
The Popup FMC should always be useable!

**Video**
https://youtu.be/P_nrZDExfWI

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.41r1
 - Version Magknight  1.4.RC1

**Comments***
It is working with the default one in every plane!
It works in all 3rd party Aircrafts
It did with 1.3.10

**Comment by aeroniemi** [comment]
I'd assume the issue is more related to the issue with mouse input not
working when the 3d one is in focus, rather than being external

**Comment by KBNOtaku** [comment]
It is also not able to enter anything with the keybord.
And as you can see in the Video Data on the FMC is also not updating. The clock isnt running anymore and NM etc.. nothing is changing and updating when in outside view!?
