### ISSUE TITLE
EFB derate errors multiplying

### ISSUE THREAD

**Issue by SCooke050** [magknight/787aviatorsTracker#23]
**Describe the bug**
In the performance tab keep inputting an incorrect derate temperature.  The EFB produces a new error window, but each time you add another figure it keeps adding lines of error messages without clearing any
 
**To Reproduce**
As above

**Expected behavior**
A single error message that gets cleared once OK is hit or some form of scrolling so that the errors don't go beyond the bounds of the error window

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.32
 - 787 Version 1.1.12

**Screenshots**
![X-Plane_2019-04-28_18-17-46](https://user-images.githubusercontent.com/50083389/56868530-66890e80-69eb-11e9-86f0-209d710f238a.png)

**Comment by aeroniemi** [comment]
Limit the number of derate messages that can be used/ clear messages on ok from the cache

**Comment by aeroniemi** [comment]
Fixed by #62

**Comment by aeroniemi** [comment]
Should be fixed in 1.2.0C
