### ISSUE TITLE
Spoilers don't move with flaps like they're supposed to

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#230]
As the flaps are extended the spoilers should move downwards to create a smooth transition from wing to flap as to reduce drag.

With 1.4.0RC2 they don't act in this way:
![B7879 - 2019-12-22 21 07 58](https://user-images.githubusercontent.com/39658757/71327341-28eb6f80-24ff-11ea-89da-c93302e577a0.png)
![image](https://user-images.githubusercontent.com/39658757/71327342-2c7ef680-24ff-11ea-9418-4f6569140053.png)

**Comment by aeroniemi** [comment]
I've not seen this in my testing of versions (probably latest b6) - are you sure the spoilers are in an appropriate state to do it (ie set to either 0 or arm with appropriate hydraulics)?
It appears the outboard flaperon isn't doing it either

**Comment by OldGroof** [comment]
> I've not seen this in my testing of versions (probably latest b6) - are you sure the spoilers are in an appropriate state to do it (ie set to either 0 or arm with appropriate hydraulics)?
> It appears the outboard flaperon isn't doing it either

I was set up for departure, hydraulics set to auto and speed breaks armed. I’d imagine that’d be the correct configuration to trigger the spoilers to retract like this. I’d imagine they’d retract automatically regardless of the config as it probably reduces drag quite a bit.

**Comment by OldGroof** [comment]
I extended the flaps to full after realising the spoilers weren’t moving to see maybe I had to be in landing config for the spoilers to move.

**Comment by mob9221** [comment]
Seems to be a modelling issue since the model dref for the spoilers reflect them moving with the flaps.
