### ISSUE TITLE
Ailerons are used in cruise when they shouldn't be.

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#231]
**Describe the bug**
The ailerons are used, by the autopilot, during the cruise phase of the flight when they shouldn't be.

**To Reproduce**
Watch the airplane perform turns at high speed and altitude.

**Expected behavior**
As far as I am aware, due to the forces felt at high speed, the 787 will disable the ailerons above a certain speed or altitude. Beyond that point only the flaperons are used. This is so that the ailerons don't rip off or rip the wing off due to the amount of force they produce.

**Screenshots**
![B7879 - 2019-12-22 21 43 07](https://user-images.githubusercontent.com/39658757/71327791-c85f3100-2504-11ea-8aa6-3b14acf2fd7d.png)
The best video I could find is this one: https://youtu.be/Unft77fRi6w?t=1139 It really hard to see but as the plane exits the turn you can see the aileron stays still and if you look real hard you can just see the flaperon reappear at the back of the wing.

**Desktop (please complete the following information):**
 - OS: Window 10
 - X-Plane version 11.40
 - Version 1.4.0RC2

**Additional context**
I'll try and find a better camera angle to demonstrate what I am looking at.

**Comment by OldGroof** [comment]
This is the exact thing I'm talking about: https://youtu.be/OqqdA-USfZI?t=27584

**Comment by aeroniemi** [comment]
They don't do anything at cruise in the flightmodel, and apparently only do it in 3d on one side, implying the 3d has incorrect dataref assignment - @mob9221

**Comment by OldGroof** [comment]
Also if you’re looking at datarefs the left inboard flaperon still never fully returns to 0 in straight and level flight, or even on the ground. Constantly points up slightly.
