### ISSUE TITLE
Screen brightness is not correct

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#235]
**Describe the bug**
The two screen brightness knobs by the EFB control all the wrong parts of each screen.
And when the lower MFD's brightness is adjusted there's a mini status page that appears.

**To Reproduce**
Use the brightness knobs and see what the screens do.

**Expected behavior**
The OUTBD DISPL knob controls just the outboard MFD, the INBD DISPL knob controls just the inboard MFD.

**Screenshots**
https://youtu.be/chq4H8ZPDb0?t=3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.40
 - Version 1.4.0rc2

**Additional context**
As a side note it'd be good to have captain and copilot brightness knobs control the respective displays independently.

**Comment by OldGroof** [comment]
Same goes for the Lower DISPL knob on the overhead. It controls the copilot's outboard MFD.

**Comment by aeroniemi** [comment]
Can't do independent dimming at present due to mixed mapped (old) displays, hence why they are cross-linked
probably issue with the array order or something being commented and untested - @mob9221
