### ISSUE TITLE
Ability to control the light on the EFB

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#236]
**Is your feature request related to a problem? Please describe.**
Just a feature request

**Describe the solution you'd like**
The ability to control the light shining on the EFB with the correct brightness light which I'm assuming it's either CHART or MAP?

**Describe alternatives you've considered**
Or have it dim with the dome light as a temporary solution?

**Additional context**
![B7879 - 2019-12-22 23 07 50](https://user-images.githubusercontent.com/39658757/71328524-54c32100-2510-11ea-9e41-f8ea9f28f1fb.png)

**Comment by aeroniemi** [comment]
I thought it had been removed from the cockpit.obj in the cockpit a while back - @mob9221  - check you're using the latest cockpit assets (ie from drive release)

**Comment by aeroniemi** [comment]
temp fix of removing it
