### ISSUE TITLE
EFB ERROR ENCOUNTERED

### ISSUE THREAD

**Issue by AviaHenrik** [magknight/787aviatorsTracker#237]
When I wanted to choose the departure runway a window popped up with the title "EFB ERROR ENCOUNTERED" - Airport appears to not have any runways Check nav data and file a bug at magknight.org/bugs.  I also cant click the message away. I flew the 787 for months and this never happend to me until I updated on 1.4.0

**Comment by aeroniemi** [comment]
Hi,
Log? Version? What navdata are you using? What airport?
