### ISSUE TITLE
Having two GPUs connected powers aircraft

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#238]
**Describe the bug**
When connecting the GPUs, the aircraft will power up when two GPUs are connected

**To Reproduce**
Connect the GPUs one by one and you'll see the aircraft power up when two GPUs are attached.

**Expected behavior**
I think the aircraft isn't supposed to be supplied by the GPUs unless the buttons are switched on.

**Screenshots**
https://youtu.be/VfP-TRwaX_8?t=4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.40
 - Version 1.4.0RC2

**Comment by aeroniemi** [comment]
power is provided by gpus when they aren't enabled on the overhead, but it is used for core systems only, although the number of core systems used increases with number of gpus - not sure if the extra lighting is one of these things though

**Comment by OldGroof** [comment]
ah I see. didn't realise they powered core systems when connected. I guess this behaviour is expected then
