### ISSUE TITLE
ELEC page does not show GPUs R and AFT connected

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#239]
**Describe the bug**
The ELEC page on the EFIS only shows the L GPU connected even though the R and AFT are connected to. The page does, however, show the GPUs available.

**To Reproduce**
Connect the GPUs and toggle the GPUs and see the ELEC page.

**Expected behavior**
All the GPU's lines should turn green like the L GPU.

**Screenshots**
L+R+AFT GPUs available:
![B7879 - 2019-12-23 16 19 05](https://user-images.githubusercontent.com/39658757/71368551-30af2080-25a0-11ea-942d-b579fd761f16.png)

L+R+AFT GPUs on [ELEC PAGE]:
![B7879 - 2019-12-23 16 19 11](https://user-images.githubusercontent.com/39658757/71368631-5b00de00-25a0-11ea-98c1-58f82744986a.png)

Electrical panel:
![B7879 - 2019-12-23 16 19 14](https://user-images.githubusercontent.com/39658757/71368658-66540980-25a0-11ea-8793-a785f0479d2e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.40
 - Version 1.4.0RC2

**Comment by aeroniemi** [comment]
likely to be a post-1.4.0 issue
