### ISSUE TITLE
Left aileron deflects more than the right

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#243]
**Describe the bug**
Left aileron deflects more than the right aileron

**To Reproduce**
Fly around, have some fun but watch the ailerons as you perform turns.

**Expected behavior**
They should deflect by the same amount

**Screenshots**
https://youtu.be/sQcmBycSXbM

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.40
 - Version 1.4.0rc2

**Additional context**
I believe this is just a 3d error as in the EFIS the FCTL page says the controls are operating normally. I think I got this in the video

**Comment by aeroniemi** [comment]
think either left or right is attatched to the wrong datarefs

**Comment by mob9221** [comment]
Seems to be a 3D modelling bug since the ailerons are moving exactly the same flight model wise.
