### ISSUE TITLE
Flaperon movement during landing

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#244]
**Describe the bug**
The flaperons move to the flap position during the ground roll of the landing when they should stay deployed with the spoilers

**To Reproduce**
Land in full landing config.

**Expected behavior**
The flaperons should stay deployed with the spoilers until the spoilers are disarmed.

**Screenshots**
https://youtu.be/TlpxijO28L0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.40
 - Version 1.4.0rc2

**Additional context**
You can also see the flaps jump up a bit as well as I slow down. Which is odd.

**Comment by aeroniemi** [comment]
post-1.4.0 issue

**Comment by mob9221** [comment]
Seems to be fixed as of now. Condition for the Left and Right flaperon were different. Now they will always deploy with spoilers.
