### ISSUE TITLE
Ambient Outside Noise Depleted 

### ISSUE THREAD

**Issue by CharlieAlphaLima** [magknight/787aviatorsTracker#246]
**Describe the bug**
There currently is zero outside noise from the aircraft apart from the gpu when you zoom in close to it. There is no noise produced from the apu either.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version [e.g. 11.41r1
 - Version 1.40 rc2

**Comment by aeroniemi** [comment]
All that is expected is the apu - potentially apu sound issue with change of datarefs
