### ISSUE TITLE
1.4.0RC-3 Mac Librain Default Settings

### ISSUE THREAD

**Issue by Viper787** [magknight/787aviatorsTracker#251]
**Describe the bug**
globalSettings.json on Mac version has raineffects set to :true which causes a slideshow of aprox 3FPS vs. my normal at 50FPS At 3FPS you cannot even get to the menus in x-plane to quit, so you have force quit via keyboard strokes

**To Reproduce**
Steps to reproduce the behavior: Launch RC-3 on Mac and check framerate

**Expected behavior**
Default setting for the Mac should be at :false until a viable solution is found.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 10.12.6
 - X-Plane version 11.41r1
 - Version 1.4.0 RC-3

**Additional context**

**Comment by aeroniemi** [comment]
remove globalsettings.json from the release - we shouldn't be shipping it anyway
it's correct in defaultGlobalSettings

**Comment by Viper787** [comment]
Got it.
