### ISSUE TITLE
Flaperon and Flaps *Again*

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#253]
**Describe the bug**
Could've sworn this was fixed last I reported it? But yet again the flaperons retract back to the flap position during the ground roll of the landing when they should stay deployed until the spoilers retract. 

As a part two the flaps and flight controls seam to jump up a position or two below a certain speed. If I'm not mistaken you use your custom controls above a certain speed so it might by this kicking in so maybe there's discrepancies between the systems or maybe there's something just completely wrong here? See the end of the video to see what I mean. This also happens on take off, basically anytime you pass a certain speed the flight controls move to a new position, around 50 knots. 

**To Reproduce**
Land in normal config and observe

**Expected behavior**
As described above they stay extended with the spoilers and the flight controls should stay still.

**Screenshots**
https://youtu.be/jaTKWVKnGyE

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.40
 - Version 1.4.0

**Comment by aeroniemi** [comment]
rather than creating a new one, you can just reopen the old one if you think the issue isn't fixed - it's much easier to track

**Comment by OldGroof** [comment]
> rather than creating a new one, you can just reopen the old one if you think the issue isn't fixed - it's much easier to track

Oh I didn’t know I could do that. I’ll remember that for next time.
