### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by datatom737** [magknight/787aviatorsTracker#261]
Imagine getting towards the end of a flight from london to perth only to get a CTD during the descent. ToLiss has implemented an autosave and flight recovery feature (which I have had to use on a couple of occasions) on their a319. This would be very useful for the 787 considering the types of flights it does.

**Comment by aeroniemi** [comment]
i had a look into saving state - we can do it for our stuff, but we can't save the default FMS state without using the x-plane sit system, which we don't have much control over - post CDU2 issue

**Comment by datatom737** [comment]
so maybe something for when we have  a full custom FMC?
