### ISSUE TITLE
EFB's  ARPT INFO page glitching

### ISSUE THREAD

**Issue by matteolosardo** [magknight/787aviatorsTracker#264]
in the EFB if you go to the ARPT INFO page (the one inside the performance page) the whole aircraft starts glitching and the EFB screen starts blinking along with other aircraft instruments.
 
<img width="2048" alt="Schermata 2020-01-21 alle 13 35 30" src="https://user-images.githubusercontent.com/56519272/72810568-2430ed00-3c5e-11ea-88cb-b60eea73101d.png">

**Comment by aeroniemi** [comment]
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/4092440/Log.txt)
