### ISSUE TITLE
1.4.2b4 Heading Knob Adjust =CTD

### ISSUE THREAD

**Issue by Viper787** [magknight/787aviatorsTracker#268]
**Describe the bug**
Trying to adjust heading knob = CTD

**To Reproduce**
Start Sim, Turn on Battery,GPU etc. during pre-flight adjust the knob - X-Plane crashes

**Expected behavior**
Should be able to adjust

**Screenshots**
None
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/4104080/Log.txt)

**Desktop (please complete the following information):**
 - OS: Mac 10.2.6
 - X-Plane version 11.41r1
 - Version 1.4.2b4

**Additional context**

**Comment by aeroniemi** [comment]
I guess the command handler must reference itself, although sasl shouldn't allow this to happen at all, under any circumstances

**Comment by aeroniemi** [comment]
Fixed for B5
