### ISSUE TITLE
APP does not work in 1.4.2Beta4

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#270]
**Describe the bug**
APP Button does not work, ILS Approach will not work, G/S dont gets captured, No G/S Indicators.

**To Reproduce**
Fly an ILS approach

**Expected behavior**
G/S Indicators shoudl be shown
APP Button should not kill the approach
G/S should be captured
When APP Button is pressed it should light up

**Video**
https://youtu.be/H9OSPu--xlY

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.41r1
 - Version 1.4.2B4

**Comment by aeroniemi** [comment]
Fixed for B5
