### ISSUE TITLE
Fuel Qty Low even with hours of fuel

### ISSUE THREAD

**Issue by RGaming007** [magknight/787aviatorsTracker#276]
the screen says low fuel even with enough for a 10 hour flight 

![Capture](https://user-images.githubusercontent.com/60050366/73124508-1fc04900-3f6a-11ea-8753-3582becf0644.PNG)

**Comment by aeroniemi** [comment]
Can you reliable reproduce this?

**Comment by RGaming007** [comment]
I can try It sometimes does it even with a lot of fuel which is weird
sometimes it gets triggered by removing and adding fuel but I will have to
check

I’ll get back to you.

**Comment by aeroniemi** [comment]
the error is specifically designed not to go away without reloading the plane, as per the real reset params, so if you remove fuel and get to the min point, no matter how much fuel you add, it won't go away

**Comment by RGaming007** [comment]
Oh that’s interesting that might be why
I think that needs to be removed for simulator purposes in my opinion
