### ISSUE TITLE
GPU Shutting Down Arbitrarily

### ISSUE THREAD

**Issue by Viper787** [magknight/787aviatorsTracker#279]
**Describe the bug**
The GPU's will shutdown by themselves aprox 3-5 min after starting during preflight.

**To Reproduce**
Turn on Battery, Turn on EFB, Ground Service, Activate GPUs, Overhead set for GPU operation (all three), continue setting up plane, flightplan, then you'll notice after a bit "Main Battery Discharge" warning. Checking the EFB you'll see that the GPUs have shutdown on their own.

**Expected behavior**
GPUs should operate until Pilot releases them.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.2.0B1]

**Additional context**

**Comment by Viper787** [comment]
Further investigation shows that it seems to shutdown upon pressing the Calc button for EFB W/B performance results.

**Comment by aeroniemi** [comment]
i've just tried this, and can't replicate it (at least using the above steps)

**Comment by aeroniemi** [comment]
unrelated to gpus - looks to be just a symptom of efb soft crashes in general.
Specific crash here - 
[Log-33.txt](https://github.com/magknight/787aviatorsTracker/files/4667706/Log-33.txt)
