### ISSUE TITLE
Liftoff MCP Speed Issue

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#283]
**Describe the bug**
After Liftoff the speed in the MCP alway´s change to 175.

**To Reproduce**
Takeoff in any situation you like, right after liftoff the value will change to 175.

**Expected behavior**
The Speed Value I set for Takeoff should remain!

**Video**
https://youtu.be/Iig_5hn1NuI

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version  11.41r1
 - Version 1.4.4

**Additional context**
I tested this in many situations as you also can see in the Video, alway´s with the same result!
I also adding the last XP11 log.txt
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/4260874/Log.txt)

**Comment by aeroniemi** [comment]
it should not keep the value set before takeoff roll - it should set to 175 or v2+10, whichever is greater

**Comment by KBNOtaku** [comment]
Ok but what about the two heavy loaded situations , where in one V2 is 177. In this situation it also turns back too 175?

**Comment by aeroniemi** [comment]
it means that the latter condition isn't working properly
