### ISSUE TITLE
GPU Issue

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#284]
**Describe the bug**
Only when using the left side GPU the Main Battery Discharge Alert disapear!

**To Reproduce**
Use any other GPU then the left sided one.

**Expected behavior**
All GPU´s should have the same effect!

**Video**
https://youtu.be/-DepBAxn1sc

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.41r1
 - Version 1.4.4

**Comment by aeroniemi** [comment]
It's acting as expected, because the main battery is discharging. the right (and aft) gpu ports can't be used to power the core system base

**Comment by KBNOtaku** [comment]
Ok did not know that, if everything is working as it should that's ok for me!
Thank you!
