### ISSUE TITLE
Aircraft reload Issue

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#285]
**Describe the bug**
When reloading the Aircraft with the developer menu, nothing is clickably anymore.

**To Reproduce**
Laod the Aircraft then reload it with the reload option in the dev. menu.

**Expected behavior**
It shoudl be possible to reload the Aircraft without any Issue.

**Video**
Will add one later

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.41r1
 - Version 1.4.4

**Additional context**
This Issue only can be solved after loading any other aircraft and then again load the Magknight!
XP11 log.txt
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/4260945/Log.txt)

**Comment by KBNOtaku** [comment]
I found out the problem was a liverysettings.json file with wrong code in it!

**Comment by aeroniemi** [comment]
added more logging/error checking for settings
