### ISSUE TITLE
Knops turning option

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#286]
**Is your feature request related to a problem? Please describe.**
Before 1.4.xx it was possible to turn the knops in the MCP by pressing and holding.
Now it only will do so by using the mousewheel or continues pressing it.

**Describe the solution you'd like**
Pleas make the knops possible to turn by cklicking and holding again.
This will make setting the values easier!
It is still working for the Baro and the minumum ALT Knops

**Comment by aeroniemi** [comment]
doesn't really make sense, as it doesn't really alow for fine control. mousewheel is the primary input method.
