### ISSUE TITLE
Flaps incredibly slow, won't retract and wrong sounds playing

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#288]
**Describe the bug**
The flaps are way too slow with FCLT2a. Slats are fine I think but the actual flaps are too slow.
Also whilst I was writing this I have realized the flaps wont retract, lever on zero and flaps still fully extended. And they are also playing the wrong sound, the hydraulic sound has been replaced by the flap extender (the drill sound)

**To Reproduce**
I set flaps 5 about 2 minutes ago and they are still going down, I imagine it'd be the same for all flap settings tho.

**Expected behavior**
They should extend faster, pre fclt2 I think they were the correct speed. They should also retract and the hydraulic sound should be the hydraulic pump.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.41r1
 - Version fctl2a

**Additional context**

**Comment by OldGroof** [comment]
Also the flap position doesn't show on the EICAS

**Comment by aeroniemi** [comment]
flaps sped up be ~10% for fctl2b
they are definitely retracting - i've just tried it out

**Comment by OldGroof** [comment]
Ok that's weird, they're working now. No idea what was wrong before

**Comment by OldGroof** [comment]
To add onto the retraction bug here's some screenshots demonstrating it.
![B7879 - 2020-02-29 17 42 56](https://user-images.githubusercontent.com/39658757/75612464-89101a80-5b1b-11ea-8bff-27032ba87cb9.png)
![B7879 - 2020-02-29 17 43 04](https://user-images.githubusercontent.com/39658757/75612467-8d3c3800-5b1b-11ea-93fc-e6f2fec591aa.png)

**Comment by OldGroof** [comment]
And a quick comparison of flap speeds: https://youtu.be/YIBEiCOBjp8
