### ISSUE TITLE
APU powers electricals at low N1

### ISSUE THREAD

**Issue by aeroniemi** [magknight/787aviatorsTracker#29]
APU powers electricals at 3% N1

**Comment by aeroniemi** [comment]
It's adding to totalWatts really early, rather than when it reaches 95%

**Comment by mob9221** [comment]
This is as expected. That dref is supposed to show total power capacity in the system. The APU doesn't shed the power it generates at low N1s and then suddenly add a huge load of power into the system suddenly. The power slowly increases and its not instantaneous.

**Comment by aeroniemi** [comment]
Could you make it so it just doesn't give anything till like 30%, because it means that everything powers on like a few seconds after you turn the APU on
