### ISSUE TITLE
Auto-retract only works on the first time

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#290]
**Describe the bug**
Auto-retract only works of the first time you try it.

**To Reproduce**
speed brake lever beyond "armed" as instructed and advance the throttles. The first time it will work but if you try it a second time it won't.

**Expected behavior**
It should work every time.

**Screenshots**
N?A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.41r1
 - Version fctl2b

**Comment by aeroniemi** [comment]
issue occurs when the thr axis moves too quickly at low(ish) framerates, conditions changed for 2c
