### ISSUE TITLE
Left Aileron deflection in Cold and Dark

### ISSUE THREAD

**Issue by tailwest** [magknight/787aviatorsTracker#296]
Left Aileron is deflected up when the aircraft is cold and dark with no hydraulic.

Version: FCTL2B
Windows Xplane 11.41

![image](https://user-images.githubusercontent.com/62467289/77225441-11fcfd80-6b80-11ea-8191-88ad5c2425fb.png)

**Comment by tailwest** [comment]
It is also there in Version 1.4.9

**Comment by aeroniemi** [comment]
it's only an issue in 1.4.x - it's not an issue in any of the fctl* releases
