### ISSUE TITLE
Realistic Display Lag Option

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#301]
**Is your feature request related to a problem? Please describe.**
I guess it is but with the new masking on the PFD it lags a little which, to me, adds a nice realistic touch to the screen as the real thing would also lag as well.

**Describe the solution you'd like**
As that is probably changing soon I think it'd be cool to have an induced lag that you can toggle in the settings page in the EFB. Maybe called: "Realistic Displays" or "Display Lag"?

**Describe alternatives you've considered**
Haven't thought of an alternative instead of just inducing lag globally.

**Comment by aeroniemi** [comment]
something to this effect already exists in the EFB/CDU, so it'd just be extrapolating out to full MFD sys and PFDs (potential performance improvement?)

**Comment by aeroniemi** [comment]
tempted to just remove the effect from the right PFD, and revert to standard left-side display - seems like a bit too much effort for low-reward
