### ISSUE TITLE
Year is cut off on CDU

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#302]
**Describe the bug**
The year of the date on the CDU is cut off, perhaps as a side effect of the new font?

**To Reproduce**
No steps, just look at the CDU

**Expected behavior**
It shouldn't be cut off the way it is.

**Screenshots**
![B7879 - 2020-03-23 16 06 40](https://user-images.githubusercontent.com/39658757/77337206-7d7dd100-6d20-11ea-9607-8ad0135edda2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.41
 - Version 1.4.7

**Comment by aeroniemi** [comment]
it's been happening for a while, despite not actually fiddling with anything there. i don't really want to look to find out though
