### ISSUE TITLE
Fuel Crossfeed

### ISSUE THREAD

**Issue by tailwest** [magknight/787aviatorsTracker#305]
**Describe the bug**
Fuel Crossfeed is not working. 

**To Reproduce**
0 fuel in the center.
Switch off the left fuel pumps while right fuel pumps and open the crossfeed valve.
Engines are still being fed by the left tank.

**Expected behavior**
If I switch off the left fuel pump and keep the right fuel pump on. Then open the crossfeed I expect that fuel will be fed to both engines by the right tank. The right tank will deplete and the left tank should remain the same. Usually used for fuel balance.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.4.1
 - Version 1.4.9

**Comment by aeroniemi** [comment]
See issue #303 - crossfeed is currently set to activate unltd fuel mode
if your bug is an issue with the activation of unltd fuel mode, feel free to reopen it

**Comment by tailwest** [comment]
Oh, so you can’t balance the fuel like the real plane?

**Comment by aeroniemi** [comment]
If you needed to balance fuel, both in ours and the real plane, you would
use Balance mode. Crossfeed is only designed to be used in the case of
single engine operations or a fuel leak
