### ISSUE TITLE
Flaperon deflects too far down when in flaps up

### ISSUE THREAD

**Issue by aeroniemi** [magknight/787aviatorsTracker#31]
When the flaps are up, it should only deflect by about the same amount down as up - with flaps down it looks fine, although it might be deflecting too far up

**Comment by mob9221** [comment]
The flaperons deploy alongside the flaps, but deflect the same amount so the positioning might look messed up modelling wise. Can I get an example of how its supposed to look like

**Comment by mob9221** [comment]
The flaperon movement doesn't change with flaps extension in terms of up and down maximum deflection. It extends along with the flaps but is able to go full up and down regardless. Not sure if this is expected behavior and i'll need a real life example to see how it really looks like.

**Comment by aeroniemi** [comment]
I doubt that is how the real one works, as it shouldn't need to deflect much to have quite high roll authority due to itssize

**Comment by mob9221** [comment]
Has been fixed
