### ISSUE TITLE
Weight and Balance Tab on EFB Home Page

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#322]
**Is your feature request related to a problem? Please describe.**
Not related to an issue

**Describe the solution you'd like**
As the title suggests I think it'd be useful to have a button to the Weight and Balance page on the home page of the EFB that way you don't have to go through terminal charts, enter in the airport then go to the performance page and then click W&B. 

**Describe alternatives you've considered**
N/A

**Additional context**
This is just an ease of access feature for when you want to just fly about without any route.

**Comment by aeroniemi** [comment]
I guess I could use this as an excuse to do a efb sprint
