### ISSUE TITLE
TCP doesn't like some frequencies

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#328]
**Describe the bug**
As the title says the TCP does not like certain frequencies:
1. TCP doesn't like frequencies with .600.
2. TCP also doesn't like frequencies with .700 from 127MHz onward.
3. Sometimes the entered frequency reduced by 0.001.

**To Reproduce**
Have a go at tuning frequencies ending with .6 or .7 and it'll show "FORMAT ERROR".

**Expected behavior**
It should accept any frequency from 118.000 to 137.000.
It should also not be reducing some frequencies by 0.001.

**Screenshots**
1. Trying to Enter frequency with .6:
https://youtu.be/NR83ZyFZ9j8
2. Entering .700 frequency above and below 128MHZz:
https://youtu.be/NyvIdyhMVv8
3. Frequecy reducing by 0.001MHz:
https://youtu.be/73w_5_oKuh8

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.51b3
 - Version 1.4.14fctl

**Additional context**
This issue was present in 11.41 as well

**Comment by OldGroof** [comment]
TCP also doesn't like frequencies with .100 as I have just found

**Comment by aeroniemi** [comment]
can't replicate 1, 3 or (4), although i've fixed 2
