### ISSUE TITLE
Strobes flashing weird (like early betas of 1.4)

### ISSUE THREAD

**Issue by PEGASUS0117** [magknight/787aviatorsTracker#334]
**Describe the bug**
The strobes are flashing more than one long flash.

**Expected behavior**
A one long flashing strobe (---- ---- ---- etc.) not like ( ---- -- ---- -- ---- -- )

**Desktop (please complete the following information):**
 - Windows 10
 - X-Plane version 11.41
 - Version 1.5 beta 1

**Comment by aeroniemi** [comment]
Default strobes are also present in b1 - resolved for b2

**Comment by PEGASUS0117** [comment]
Thank you :)
