### ISSUE TITLE
Legs page Numbers

### ISSUE THREAD

**Issue by PEGASUS0117** [magknight/787aviatorsTracker#335]
**Describe the bug**
After going through all pages (20) and than clicking to "NAXT PAGE" the Next page was not 1 (it went to 21).

**To Reproduce**
Dont know haha

**Expected behavior**
It should be page 1

**Screenshots**
https://cdn.discordapp.com/attachments/508016604454322176/703392224637091920/unknown.png

**Desktop (please complete the following information):**
 - Win 10
 - X-Plane version 11.41
 - Version 1.5 beta 1

**Additional context**
When clicking further and the number is over 29 it will now show 10 so its correct.

**Comment by aeroniemi** [comment]
It shouldn't return to page 1 - neither by LR's default FMS manual, or boeing's 787 docs. Doing that creates a risk of making you not realise it's the end of the flightplan
