### ISSUE TITLE
Force reset weight and balance values on loading

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#337]
**Is your feature request related to a problem? Please describe.**
Yes, as some people seem to feel the necessity to use the default menu to load the payload and fuel which messes with the inbuilt system.

**Describe the solution you'd like**
When the aircraft loads it could be a good idea to reset the weight to the OEW and reset the fuel to either a small amount, say 2,000kg, or the last known fuel weight from the last time the plane was used.

**Describe alternatives you've considered**
Another way of working with the default menus is to somehow detect if the values have been changed and if they have automatically adjust them to last known values, or using the values in the default menu and applying them correctly to the aircraft (correct CG etc).

**Comment by aeroniemi** [comment]
done for b7
