### ISSUE TITLE
Disappearing VSpeed Indicator (PFD) & Stab Setting Indicator (PFD)

### ISSUE THREAD

**Issue by Viper787** [magknight/787aviatorsTracker#339]
**Describe the bug**
Disappearing VSpeed Indicator (PFD) & Stab Setting Indicator (PFD)

**To Reproduce**
After entering EFB Calculations, the VSpeeds are indicated on the EFB, but the recommended Stab Settings are no longer displayed. However on the PFD "there are signs of life" - The VSpeed indicator in green is at the bottom of the tape, and drifts down out of sight as ground speed increases and is not visible to the pilot.
The Stab settings will only be reflected in the Green Box when trim is set "exactly" at 1.00 regardless of weight and CG - otherwise all other setting are simply reflected as white with no box.

**Expected behavior**
VSpeed Indicator should be properly aligned on the speed tape so that is does roll off before V2. Stab Indicator should produce correct results in the box, not always suggest 1.00 as the correct setting.

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: MacOs 10.12.6
 - X-Plane version 11.41r1
 - Version 1.50b4
![Screen Shot 2020-05-03 at 8 41 24 AM](https://user-images.githubusercontent.com/56449761/80918949-59001600-8d1c-11ea-8189-7275c0f06e68.png)
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/4570905/Log.txt)

**Additional context**

**Comment by Viper787** [comment]
Something I just also noticed in the log.txt file - When I changed my flap setting from 5 to 15 and recalculated the performance, the log.txt seems to indicate that I selected 20deg of flaps which is not true.

**Comment by aeroniemi** [comment]
it's probably a bug, but nobody else has reported it and i can't replicate it on windows, so until we have more user data, not much we can do

**Comment by aeroniemi** [comment]
the tech was replaced (ish) as part of 1.6.0, so if a similar issue exists now it is likely of new cause - create a new issue if you still have issues
