### ISSUE TITLE
Not able to change views when clicking EFIS display (1.5 b5)

### ISSUE THREAD

**Issue by Rubenzxl** [magknight/787aviatorsTracker#342]
**Describe the bug**
When you click on a page, for example the fuel page, you can't change camera views by pressing keys on the numpad. I think it's because of the added ACARS feature where you can type in the box at the bottom of the screen.

**To Reproduce**
Described above: when clicking on one of the EFIS pages. I noticed same behavior on the EFB. When you click on something on the EFB (not a box where you can type) you aren't able to change views as well.
EDIT: It's actually the same for all of the displays in the cockpit (PFD, ND, EICAS, EFIS, MFD, EFB). When clicking somewhere else in the cockpit, you're able to change views again.

**Expected behavior**
To be able to change views when not on the ACARS page or typing someting in a box. 

**Screenshots**
Not needed I think.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version: 11.41
 - Version: 1.5 b5

**Additional context**

**Comment by aeroniemi** [comment]
I've found a middle-ground solution to this for b7

**Comment by Rubenzxl** [comment]
Works very well now, thank you very much
