### ISSUE TITLE
Master Alarm and SPEEDBRAKES EXTENDED warning on landing

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#343]
**Describe the bug**
When landing at the Touchdown SPEEDBRAKES EXTENDED message appaers and Master Alarm sound is playing.

**To Reproduce**
Do an landing.

**Expected behavior**
No Master Alarm on Touchdown.

**Video**
Video1: https://youtu.be/x8Vo-TM2xio
Video2: https://youtu.be/Sn2_FLiSe30

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.50b6
 - Version 1.5b6

**Additional context**
LOG file is from second video if helpfull.
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/4605854/Log.txt)

**Comment by aeroniemi** [comment]
Master caution is expected with SPEEDBRAKES EXTENDED, but message shouldn't fire on touchdown unless you apply extra power during rollout

**Comment by KBNOtaku** [comment]
As you can see in the Video it happens right at the touchdown moment, and I am landing with Thrust on Idle.
