### ISSUE TITLE
Contrails on RR engines sometimes appear in front of the engine

### ISSUE THREAD

**Issue by edvinasandr** [magknight/787aviatorsTracker#349]
**Describe the bug**
Contrails on RR engines sometimes appear in front of the engine during descent.

**To Reproduce**
Try descending from high FL.

**Expected behavior**
For it to show contrails behind the engine not in front of it.

**Screenshots**
![B7879 - 2020-05-11 22 34 34](https://user-images.githubusercontent.com/65218335/81655087-aa0bba80-943e-11ea-939e-9fab0076df9c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.41]
 - Version [e.g. 15.0B8]

**Additional context**

**Comment by Sp33dM** [comment]
This happens on the FF757, and A320, and most other aircrafts. I'm most certainly sure it's a laminar bug. correct me if I'm wrong @aeroniemi

**Comment by aeroniemi** [comment]
related to #60 
It can be fixed with custom particles
