### ISSUE TITLE
Improving the RR spinners to be more cone shaped 

### ISSUE THREAD

**Issue by Bill-Clinton69** [magknight/787aviatorsTracker#351]
**Is your feature request related to a problem? Please describe.**
Current RR spinners shaped more like a rounded dome instead of cone shaped.

**Describe the solution you'd like**
Cone shaped RR spinners like in real life.

**Describe alternatives you've considered**
Remake the spinner model to make them more cone shaped. 

**Additional context**
![Screenshot (4454)](https://user-images.githubusercontent.com/56235285/81742193-fe935200-949f-11ea-8ee6-813584a4ab1d.png)
![a-rolls-royce-trent-1000-turbofan-engine-mounted-on-a-new-boeing-787-E9TRYR](https://user-images.githubusercontent.com/56235285/81742295-297da600-94a0-11ea-840c-8ba8f84d0205.jpg)

**Comment by aeroniemi** [comment]
doesn't really look fixed in new assets:
![image](https://user-images.githubusercontent.com/13006900/81810483-ed3b5b80-951a-11ea-81ca-4f8c46e9b5c9.png)
