### ISSUE TITLE
[1.5.0 Beta 8] flaps do not move on replay

### ISSUE THREAD

**Issue by ALiteralChild** [magknight/787aviatorsTracker#354]
**Describe the bug**
The flaps do not move in replay mode.

**To Reproduce**
Set the flaps to various settings while running the sim, then re-watch in replay. The flaps will remain at the position they were in when replay started.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.41]
 - Version [e.g. 1.5.0B8]

**Comment by aeroniemi** [comment]
It's not a bug, it's how they work
