### ISSUE TITLE
[1.5.0 beta 8] Autobrakes do not work.

### ISSUE THREAD

**Issue by ALiteralChild** [magknight/787aviatorsTracker#355]
**Describe the bug**
Autobrakes seem to not work.

**To Reproduce**
Load the simulator on a final approach, set auto brakes to 2, and land the plane.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.41]
 - Version [e.g. 1.5.0B8]

**Comment by aeroniemi** [comment]
replaced by custom autobrakes in b10
