### ISSUE TITLE
Overspeed warning >250 kts flaps retracted.

### ISSUE THREAD

**Issue by Shrekpool** [magknight/787aviatorsTracker#356]
**Describe the bug**
 Overspeed warning passing ~260 control surfaces
**To Reproduce**
Climb, set 290-300 knots climb speed with 250/10000 restriction. Overspeed warning will follow

**Expected behavior**
A normal climb and cruise at ~300 knots at >FL100 -FL330

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version [v 11.4]
 - Version [e.g. 1.5.0B8/9]

**Comment by aeroniemi** [comment]
specifically a B9 issue, beta revoked
