### ISSUE TITLE
Wings

### ISSUE THREAD

**Issue by Shrekpool** [magknight/787aviatorsTracker#357]
**Is your feature request related to a problem? Please describe.**
Excessive wingflex that is unrealistic. Bends way too much.

**Describe the solution you'd like**
Dampened wingflex, flex that only really starts at the second outboard flap fairing
**Describe alternatives you've considered**
Don't know know how and am not allowed to edit files.

**Comment by aeroniemi** [comment]
Under excessive conditions, perhaps, but under normal flight the wingflex is underdone, rather than overdone.
