### ISSUE TITLE
Thrust reverse can be deployed in midair

### ISSUE THREAD

**Issue by jaytseng** [magknight/787aviatorsTracker#363]
**Describe the bug**
The thrust reversers can deploy even with now weight on wheels/in flight. 

**To Reproduce**
Take off, wheels off ground, deploy reverse to "hold thrust reverse at max thrust" using throttle preset. "Toggle reverse thrust" is correctly locked out. 

**Expected behavior**
Thrust reverse should be locked out in flight.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.41 & 11.5b6
 - Version 1.41 & 1.5b9x

**Additional context**

**Comment by aeroniemi** [comment]
the issue appears to exist with single-engine reverse commands

**Comment by aeroniemi** [comment]
fixed for next beta, also added engines-off reverse inhibiting
