### ISSUE TITLE
ACD is not working correctly and when attempting to enter a registration number and other info it says FORMAT ERROR. X plane 11.41 Windows 10

### ISSUE THREAD

**Issue by F4Z4D** [magknight/787aviatorsTracker#364]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.2.0B1]

**Additional context**

**Comment by aeroniemi** [comment]
please fill out the whole thing in future, there's a reason the template exists. "and other things" - such as?

**Comment by aeroniemi** [comment]
nil idea of exactly what the problem is - i've changed the conditions on the registration to allow 7A-LYC etc.
