### ISSUE TITLE
Autothrottle issue on RR engines B11

### ISSUE THREAD

**Issue by Edrmzc** [magknight/787aviatorsTracker#368]
**Describe the bug**
I arm the AT switch and TPR and N1 go low, N1 go to 60% and doesn't maintain the selected airspeed on the MCP tried, VNAV but It has the same problem./

**To Reproduce**
Reaching cruise, climbing on LNAV/VNAV when changes to Cruise Speed, that happened, I turned off the AT switches and I can control the power manually, but turn the switches on and the TPR and N1 go like to idle.

**Expected behavior**
TPR and N1 go to idle and doesn't follow the selected speed. 

**Screenshots**
![X-Plane Screenshot 2020 05 18 - 19 47 18 72](https://user-images.githubusercontent.com/65576197/82272565-92519c00-9940-11ea-9196-ae987938fad5.png)
AT switch OFF manual throttle 

![X-Plane Screenshot 2020 05 18 - 19 47 43 05](https://user-images.githubusercontent.com/65576197/82272582-9e3d5e00-9940-11ea-881f-df00c29333c1.png)
AT switch ON

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro latest update
 - X-Plane version 11.41 steam
 - Version 1.50b11

**Additional context**

**Comment by aeroniemi** [comment]
same thing as #361 
reverting to n1 limiter with RR engines, probably for a long time
