### ISSUE TITLE
Roll spoilers on approach

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#370]
**Describe the bug**
At the moment roll spoilers are not disabled and performing similar inputs seen in the video below causes the roll spoilers to react.

**To Reproduce**
have a play around with the controls whilst in approach config.

**Expected behavior**
By the looks of it roll spoilers are disabled during the approach, not sure if this is something to do with flight phases or whether it's just a case of disabling roll spoilers in landing config or beyond a certain flap setting.

**Screenshots**
https://youtu.be/TmZnXVaein8?t=275

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - X-Plane 11.50b9
 - Version 1.5.0b11

**Comment by aeroniemi** [comment]
i'll set it for landing flaps+ now, but it looks like it happens on takeoff too - it could have some sort of altitude or speed fadeout (yay)
