### ISSUE TITLE
Fuel stuck at 33.4

### ISSUE THREAD

**Issue by JoeW904** [magknight/787aviatorsTracker#372]
**Describe the bug**
I was flying with the Version 1.5 of the 787 and noticed when I got to 33.4 tonnes of fuel it stopped going down and I didn't lose anymore. When I then edited the fuel in the XPLANE MENU to 30 tonnes it continued to go down again. 

**To Reproduce**
Flying with over 33.4 tonnes of fuel and you will find it stops going down.

**Expected behavior**
For the fuel to go down

**Screenshots**
https://gyazo.com/ba2a4b9c69d5be10eac3905fcd5d9aff

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.41
 - Version 1.5

**Additional context**
Didn't have the issue before 1.5

**Comment by aeroniemi** [comment]
you have crossfeed on, which activates unltd fuel mode - everything is
working correctly

**Comment by JoeW904** [comment]
Will it be changed in "future" update?

**Comment by JoeW904** [comment]
Because if I don't have it on then the fuel goes imbalanced

**Comment by aeroniemi** [comment]
No - if your fuel is imbalancing, it's probably because you've got the APU on - if you need to balance fuel, just use BALANCE mode

**Comment by JoeW904** [comment]
ah right okay cheers for the info
