### ISSUE TITLE
Flashing Screens 

### ISSUE THREAD

**Issue by DevonBoy87** [magknight/787aviatorsTracker#373]
**Describe the bug

Screens flash in a strobing pattern within the cockpit, this is intermittent and unpredictable, occasionally they flash to the point that the click spots on the simulated touchscreens don’t work. 

**To Reproduce**
Unpredictable occurrences however it may involve pausing (making it worse) or the fact I am running an AMD card on Vulkan 

**Expected behavior**
I expected all screens to be stable the same as prior to the update. 

**Screenshots**

Unable to add video. Will place in Discord 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.5 B9 
 - Version  1.5

**Additional context**
I believe since vulkan. Started there have been some issues for users of AMD cards in glass cockpits

**Comment by aeroniemi** [comment]
Does it happen in 11.50b9 GL, or 11.41?

**Comment by DevonBoy87** [comment]
I shall double check later today. I’ve attached a video of what it is doing now in 11.50b9 vulkan. This came much worse after taking an external view and then returning to the cockpit view. I’m on a VA flight so have to stick with it but essentially it’s unusable at this point.  Interacting with the CDU is nearly impossible.

**Comment by aeroniemi** [comment]
probably caused by erroring
