### ISSUE TITLE
Logitech Xtreme 3D pro

### ISSUE THREAD

**Issue by Darwinfr** [magknight/787aviatorsTracker#374]
Hey guys, ever since I bought the Magknight 787 half a year ago, I’ve been using my Logitech Extreme 3D pro as my rudder and front-wheel pedal. I’ve noticed that even by turning it a little bit, the plane’s wheels turn so much. During landing its a big challenge, any fix? I’d be glad to show a demonstration if needed.

This occurs simply by rotating the Yoke left and right.

It is the only plane by far that has this behavior while trying to taxi, takeoff or land. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11

**Comment by aeroniemi** [comment]
Check your EFB settings for NWS - there are options for roll, yaw and tiller. It's likely you've selected the wrong one.
