### ISSUE TITLE
Bank angle warning sounding

### ISSUE THREAD

**Issue by GiacomoLaw** [magknight/787aviatorsTracker#375]
**Describe the bug**
The bank angle warning sounds after passing 600 feet, and does not stop for the entire flight.

**To Reproduce**
GASGU2K departure out of EGLL. Following the LNAV, the warning sounded when the turn started. It does not turn off the entire flight. Even if a hard turn is done, the bank angle warning simply restarts, and does not stop.

**Expected behavior**
Bank angle warning to stop sounding once the angle has reduced.

**Screenshots**
![B7879 - 2020-06-01 10 09 38](https://user-images.githubusercontent.com/9038673/83394231-236c4c80-a3f0-11ea-97f8-df7856eebeb1.png)
Warning still sounding.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version: 11.41r4 (latest release)
 - Version: 1.5

**Additional context**
Turning UI volume stops it, which is a temp fix. However, this also mutes minimum callouts, as well as radio alts etc.

**Comment by aeroniemi** [comment]
Log?
https://docs.magknight.org/troubleshooting/#someone_asked_for_my_log_-_what_is_it

**Comment by GiacomoLaw** [comment]
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/4710518/Log.txt)
Sound is still playing despite the last four lines

**Comment by GiacomoLaw** [comment]
I think this is an issue with my soundpack - doing a 10+ hour flight tomorrow so shall check without one.
