### ISSUE TITLE
FMC In flight Waypoint change

### ISSUE THREAD

**Issue by DevonFly** [magknight/787aviatorsTracker#378]
When flying, it is often required to replace the current "fly to" waypoint with a later one, particularly when being instructed to fly direct to x by a Vatsim controller. While it is possible to move a later waypoint "up the ladder" to another later waypoint not currently in use, this does not work if you are trying to replace the waypoint in use (coloured purple). As this is usually the one you want to replace and it can be done on x-plane & Zibo a/c, this would seem to be a bug. It is also not possible to delete any waypoint that has been passed, nor to delete the waypoint being flown to. FMC txt "Invalid Entry" appears.

**To Reproduce**
Create FP EGCC/05L - EGKK/08RT : LIST2S-LISTO-HON-KIDLI-WILO3B
Fly the route & when just passed LISTO, click on KIDLI and attempt to replace HON
When I try this, I get a message on th FMC "Invalid Entry -clear"

**Expected behavior**
KIDLI should replace HON on the FMC

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.41
 - Magknight 789 1.50

**Additional context**
Have tried it several times

**Comment by aeroniemi** [comment]
Go to the DIRECT page, and move it to the dashed line

**Comment by DevonFly** [comment]
thanks I will try it and report back
