### ISSUE TITLE
Map/Plan screens

### ISSUE THREAD

**Issue by DevonFly** [magknight/787aviatorsTracker#379]
**Is your feature request related to a problem? Please describe.**
When choosing Map or Plan screen display, both the Pilot's and co-pilot's screen change. There does not seem to be a method of allowing independent change.

**Describe the solution you'd like**
It should be possible to change the Map or Plan screen of both pilots independently.

**Describe alternatives you've considered**

**Additional context**

**Comment by aeroniemi** [comment]
it isn't so simple, but effective ND operation can be added with the custom ND

**Comment by aeroniemi** [comment]
same  thing as FR #647 , which is a bit better placed to deal with this
