### ISSUE TITLE
Autobrake goes past RTO

### ISSUE THREAD

**Issue by theparaodxdoge** [magknight/787aviatorsTracker#380]
**Describe the bug**
When you set the auto brake to RTO it goes past it but its still on RTO

**To Reproduce**
Steps to reproduce the behavior: Just set to RTO

**Expected behavior**
Does as expected, just a small visual glitch

**Screenshots**
https://prnt.sc/swz30g

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version: 11.41r1
 - Version: 1.5.1

**Additional context**

**Comment by aeroniemi** [comment]
you haven't got the up-to-date cockpit textures that match the new autobrake knob - try deleting them and getting the updater to redownload them
