### ISSUE TITLE
Cabin Announcements

### ISSUE THREAD

**Issue by DevonFly** [magknight/787aviatorsTracker#382]
**Is your feature request related to a problem? Please describe.**
It took me a few days to realise that the cabin announcements can only be heard by the pilot if the view is rotated around to face the cabin door. As soon as I rotate back to forward the sounds disappear

**Describe the solution you'd like**
I can understand that the announcements should be muffled if the door is shut and may be lessened if facing forward.
1. Even if facing forward and with the door shut, it should be possible to hear the cabin announcements to some extent, otherwise there is no point in having this file at all
2. The default soundpack file should have a note advising users that no announcements will be heard unless facing the cabin door - if that situation is to continue. I would rather that an upgrade took my option 1

**Describe alternatives you've considered**

**Additional context**

**Comment by aeroniemi** [comment]
you can control the volume as you desire in the TCP CABIN page - at default volume i can hear the default soundpack pretty easily with the engines at idle facing forwards

**Comment by DevonFly** [comment]
I cannot find a TCP cabin page anywhere. Please advise where I can find it.

**Comment by DevonFly** [comment]
Sorry, I have now found the cabin vol on the radio panel. It is set at 100% and I still cannot hear announcements when facing forward and with the door open.

**Comment by DevonFly** [comment]
Having installed the BA & KLM sound packages, I can now hear their announcements
