### ISSUE TITLE
Possibly bug with engine one not starting on second flight

### ISSUE THREAD

**Issue by antonvons** [magknight/787aviatorsTracker#384]
Don’t know if this is a bug. I found that engine one would not start on a second flight in the one session. All went well with the first flight, then I started the APU, put the APU gens on, then shut down both engines. I then loaded a new flight into the EFB and FMS, then proceeded to start the engines again. Engine two started with no problem. Engine one however started spooling N2 but saw nothing for N1. The oil pressure rose a little then faded in red. I repeated the start process several times, even stopping Engine two. Engine two would always start up but not one. Only when I closed x-plane and started it again did the issue stop. In the new flight both engines started ok

**Comment by aeroniemi** [comment]
Did you get an AUTOSTART L/R EICAS message?

**Comment by antonvons** [comment]
not that I can remember



Sent from myMail for iOS


Tuesday, 30 June 2020, 04:52 +1000 from notifications@github.com  <notifications@github.com>:

**Comment by aeroniemi** [comment]
Can't replicate this using a valid start config, only with config errors that result in AUTOSTART errors
