### ISSUE TITLE
Fuel Load Conflict EFB vs. EFIS vs. X-Plane & EFB Crash Data

### ISSUE THREAD

**Issue by Viper787** [magknight/787aviatorsTracker#386]
**Describe the bug**
Is there a discussion about an anomaly in the Fuel Load calculations in 1.51? I have not flown the Mag in awhile but today I loaded 49,500 lbs of fuel for my trip and the EFB shows that. However EFIS is showing 63,500 - On a whim, I checked X-Plane WT/Bal and it matched EFIS - but... as soon as I closed the X-Plane interface the EFB and EFIS suddenly matched @ 49,500 lbs  -- On a side note the EFB crashed on departure airport calculations, hopefully the log captured the data you need for that issue as well. Screenshots attached - Cheers!

**To Reproduce**
Never happened before, not sure I can reproduce other than steps above

**Expected behavior**
EFB/EFIS should match

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: Mac 10.12.6
 - X-Plane version 11.41r1
 - Version 1.5.1
![Screen Shot 2020-06-21 at 1 54 41 PM](https://user-images.githubusercontent.com/56449761/85239217-8ba6c080-b3e7-11ea-9e63-20317308adf6.png)
![Screen Shot 2020-06-21 at 2 02 47 PM](https://user-images.githubusercontent.com/56449761/85239220-91040b00-b3e7-11ea-84f7-812079a15990.png)
![Screen-Shot-2020-06-21-at-1 54 41-PM](https://user-images.githubusercontent.com/56449761/85239222-92cdce80-b3e7-11ea-8a23-d3fadce98651.jpg)
![Screen Shot 2020-06-21 at 2 01 18 PM](https://user-images.githubusercontent.com/56449761/85239223-93fefb80-b3e7-11ea-9970-5822dd1f9828.png)
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/4810642/Log.txt)

**Additional context**

**Comment by aeroniemi** [comment]
there is an issue that occurs when other plugins or the x-plane menu tries to edit weights or fuel, although no change expected due system replacement
