### ISSUE TITLE
AP doesn't work

### ISSUE THREAD

**Issue by Wizikii** [magknight/787aviatorsTracker#388]
**Describe the bug**
When i press the AP button nothing happening, but on the PFD i can see the AP indicator.

**To Reproduce**
-take off
-after 200ft gear up
-Press AP button (passing 1000-2000ft)

**Expected behavior**
I was flying between EDDF and LEBL, after passing 1000 or 2000ft i wanted to active the auto pilot.

**Screenshots**
[X-Plane 2020.06.30 - 17.57.50.01.zip](https://github.com/magknight/787aviatorsTracker/files/4853232/X-Plane.2020.06.30.-.17.57.50.01.zip)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.50b11]
 - Version [e.g. 1.5.0]

**Additional context**
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/4853217/Log.txt)

**Comment by DevonFly** [comment]
What did you what AP to do that it did not do ? Change heading or alt on manual settings, or follow FMC ?
