### ISSUE TITLE
Range switch misprogrammed

### ISSUE THREAD

**Issue by DevonFly** [magknight/787aviatorsTracker#389]
**Describe the bug**
On clicking on the + side, the range deceases. On the - side the range increases !

**To Reproduce**
Steps to reproduce the behavior: Click as above

**Expected behavior**
+ should mean increase, - decrease

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.2.0B1]

**Additional context**

**Comment by aeroniemi** [comment]
In my release copy, that's how it works? We switched the direction around some time in 1.5.0

**Comment by DevonFly** [comment]
Have tested this again since downloading and running 1.5.1
Clicking in the + direction decreases the range and - increases it. This is illogical and should be the other way around.
Am only pointing these things out to improve them. In general this is a lovely product !

**Comment by magknight1** [comment]
I've flipped the commands and now it's working correctly.
