### ISSUE TITLE
How to activate ADF

### ISSUE THREAD

**Issue by DevonFly** [magknight/787aviatorsTracker#390]
**Is your feature request related to a problem? Please describe.**
I have set 368 in ADF 1 (Whitegate near EGCC). Set the Mins to Radio, but the map/plan screen still shows INN, which appears to be on EGCC rwy even tho it is not on Skyvector and if it was it would be called MCT. I have switched VOR/LOC but it still does not change.

**Describe the solution you'd like**
The VOR L should change on the screen, when I input a new ADF freq on the FMC on the left side.

**Describe alternatives you've considered**

**Additional context**

**Comment by aeroniemi** [comment]
There is no adf for you to use - it's not a standard feature of a 787, although some airlines have it as an optional extra

**Comment by DevonFly** [comment]
ok thanks
