### ISSUE TITLE
MFD L & R lights

### ISSUE THREAD

**Issue by DevonFly** [magknight/787aviatorsTracker#391]
**Describe the bug**
The Pilot side shows the MFD lit on the right and the co-pilot's Left.
Is this significant and if so, how do I change it so that the Left switch is lit for the Pilot ?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.2.0B1]

**Additional context**

**Comment by aeroniemi** [comment]
That's how it is - you cannot move the NDs because default tech, so you cannot control the left upper segment. The button is able to work when a movable ND is released.
