### ISSUE TITLE
Slow climb speed, no speed control

### ISSUE THREAD

**Issue by dginn69** [magknight/787aviatorsTracker#392]
**Describe the bug**
I set up the plane from cold & dark. Payload per simbrief and 1 derated takeoff flaps 10. It seems every other flight of so once I lift off and raise landing gear speed stops at 150 kts. Bringing up flaps has no effect. It is the same if I use VNAV or not. If I can nurse it up to cruise altitude the max speed I can get is 240 kts, after level off. If I turn off AT & AP the throttle moves but the engines don't seem to respond. 

**To Reproduce**
Its hard to say, It seems to be happening more and more frequently (every other flight).  I set up the aircraft the same every time with the same checklist.

**Expected behavior**
Upon take off accelerate and maintain climb speed and cruise speed.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.2.0B1]
Windows 10
XP-11.41. 
787 v 1.5.1

**Additional context**
If I just let the plane try and climb & do not intervene it will kill the AP when it gets to 130 kts and then the plane becomes uncontrollable.

**Comment by aeroniemi** [comment]
what weights are you using?

**Comment by dginn69** [comment]
The plane had a ZFW of about 33000 lbs. Not overweight.
