### ISSUE TITLE
Engines do not flame out with crossfeed enabled.

### ISSUE THREAD

**Issue by genericpilot** [magknight/787aviatorsTracker#394]
**Describe the bug**
When the fuel crossfeed is on, neither engines nor the APU can flame-out, regardless of how little fuel there is.

**To Reproduce**
1. Start engines
2. Turn on fuel crossfeed
3. Expend all available fuel

**Expected behavior**
For the engines to flame-out.

**Screenshots**
https://imgur.com/a/czNlswC

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version: latest stable
- Version 1.5.0

**Additional context**

**Comment by aeroniemi** [comment]
Crossfeed isn't currently simulated, so the button is set to enable infinite fuel mode
