### ISSUE TITLE
FMC updated to latest airac, but still not working with a new airport/runway

### ISSUE THREAD

**Issue by DJ-STRE** [magknight/787aviatorsTracker#404]
**Describe the bug**
There is a new airport (LTFM Istanbul airport) and they added a new runway a weeks ago and the new runway
is in airac 2008. I updated the MK787 and the DEFAULT DATA to the latest airac, but for some reason, it says ''NO PROCEDURES'' i tested it with other airplanes in Xplane and it worked normally. (And yes, i did download the latest scenery for the airport,
or else it wouldnt work with other airplanes)

(Look at the screenshots below)

**To Reproduce**
import LTFM into the FMC (?)

**Expected behavior**
I expected the FMC to show me the new airport with the new runway because i updated to the latest airac.

**Screenshots**
![B7879 - 2020-07-27 01 54 20](https://user-images.githubusercontent.com/66440539/88493550-fed8bf00-cfb1-11ea-9ae8-0ce95f93fd30.png)
![B7879 - 2020-07-27 02 36 56](https://user-images.githubusercontent.com/66440539/88493562-0f893500-cfb2-11ea-91f4-2bcc503df845.png)

**Desktop (please complete the following information):**
 - OS: [ Windows 10]
 - X-Plane version [11.41]
 - Version [1.5.9Cygnus6]

**Comment by aeroniemi** [comment]
You're on 11.41 - it's never going to work, because the airport doesn't exist according to x-plane. update to 11.50
