### ISSUE TITLE
Arm speedbrakes by pressing "speedbrakes retract one"

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#407]
**Is your feature request related to a problem? Please describe.**
Something which seems to be common with every other plane is that you can arm the speedbrakes by pressing "speedbrakes retract one" when the speedbrakes are down. At the moment on the 787 you have to click "speedbrakes extend one" to arm them.

**Describe the solution you'd like**
If it's possible it'd be great to have the speedbrakes act the same way as every other plane as it's kind of annoying how it acts now. 

**Describe alternatives you've considered**
keeping it how it is, is fine but it's just one of those things which bugs me when I'm landing.

**Comment by aeroniemi** [comment]
released in 1.6.3
