### ISSUE TITLE
Holding fuel slider decreases the ZFW slider

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#409]
**Describe the bug**
if you click and hold the fuel slider in place on the overview page, the ZFW slider decreases by itself.

**To Reproduce**
set the ZFW slider to a value and then click and hold the fuel slider.

**Expected behaviour**
adjusting the fuel slider shouldn't affect the ZFW slider.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.50b15
 - Version 1.5.9cygnus11

**Additional context**
it also moves the zfw slider if you adjust the the fuel.

**Comment by aeroniemi** [comment]
That is kinda expected - if you push fuel to the max the permissable range of ZFW changes too

**Comment by OldGroof** [comment]
it just keeps decreasing by itself. It doesn't matter if the ZFW is particularly high or if the fuel is high. if you click and hold the slider the ZFW just starts decreasing.
