### ISSUE TITLE
Take-off performance page destroys FPS..

### ISSUE THREAD

**Issue by DJ-STRE** [magknight/787aviatorsTracker#415]
**Describe the bug**
In the Magknight, my fps on ground is around 50-60,  when i setup my ''AIRCRAFT CONFIG'' page, everything is fine
however... when i go to performance T/O page, my fps INSTANTLY goes down to 22-18 fps (shown on the screenshots) but,
when i enter the ICAO in the performance page, my fps goes back to normal..  i showed this to SpeedM! and he said that i should file a bug.
i did reinstall the plane, unfortunately that didnt help. 

**To Reproduce**
No idea.

**Expected behavior**
I expect the performance to be normal and not go down to 18 at the performance T/O page. 

**Screenshots**
![Aantekening 2020-08-06 111355](https://user-images.githubusercontent.com/66440539/89514468-31669100-d7d6-11ea-9a69-8536e077bd06.png)
![Aantekening 2020-08-06 111443](https://user-images.githubusercontent.com/66440539/89514473-33305480-d7d6-11ea-8ff4-2be69a990e50.png)
![Aantekening 2020-08-06 111520](https://user-images.githubusercontent.com/66440539/89514479-3592ae80-d7d6-11ea-922a-441e08e2f5d5.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - X-Plane version [11.41]
 - Version [1.5.9Cygnus11]

**Additional context**
The problem is only in the Peformance takeoff and landing page, all the other pages in the EFB are fine.
(Pay close attention at my frames on the left top when i go to the performance T/O page and when i enter the ICAO)

**Comment by aeroniemi** [comment]
log?

**Comment by DJ-STRE** [comment]
@aeroniemi   There u go:  
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/5033932/Log.txt)

**Comment by aeroniemi** [comment]
Is that log specifically from a situation where the performance has gone low? I can't see any issues, and the timers look fine

**Comment by DJ-STRE** [comment]
Yea i gave you the log after that problem happened, i didnt close down xplane first.  Also, ive seen quiete a few people posting the same problem that i have here on github and discord aswell..  so i guess it must be a bug?

**Comment by aeroniemi** [comment]
i can't see any evidence of anything that relates to the efb causing issues there - so i don't have any evidence of it.
Even on discord i've yet to see any reasonable evidence of any issues in this area

**Comment by DJ-STRE** [comment]
Give me a second,  ill start xplane and let that ''issue'' happen and give you the log after

**Comment by DJ-STRE** [comment]
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/5053524/Log.txt)
 There u go

**Comment by aeroniemi** [comment]
alright - now there is an actual issue that can be fixed - looks to be settings related

**Comment by DJ-STRE** [comment]
Nice, should i do anything now? or are you taking over the problem from now
