### ISSUE TITLE
787 librain crashes sim

### ISSUE THREAD

**Issue by illusorylol** [magknight/787aviatorsTracker#417]
**Describe the bug**
After a random amount of time in Vulkan (11.50b17), the plane crashes, with librain as the cause.

**To Reproduce**
Load into the plane version 1.6.0 cygnus 4. Attempt to fly the plane. After a certain amount of time, the sim will grash.

**Expected Behavior**
The sim will not crash.

**Desktop**
Windows 10
X-Plane 11.50b17
787 1.6.0 cygnus 4

[Log.txt](https://github.com/magknight/787aviatorsTracker/files/5049703/Log.txt)

**Comment by aeroniemi** [comment]
Resolved somewhere before v1.6.0-cygnus5
