### ISSUE TITLE
Speed brake not deploying on command

### ISSUE THREAD

**Issue by J-De-Vries** [magknight/787aviatorsTracker#42]
**Describe the bug**
Speed brake won't extent if I press the command that works for all other planes. I have to do this manually
**To Reproduce**
Just loading up the plane.

**Expected behavior**

It should extend when pressing the button.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.2.0B1]

Windows 10, XP11 11.33
**Additional context**

**Comment by aeroniemi** [comment]
not 100% sure on what's going on here, but i'll investigate
