### ISSUE TITLE
clock button not working

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#421]
**Describe the bug**
The clock button on the glareshield, with mic switch and map light, doesn't start the clock.

**To Reproduce**
Power up the aircraft and press clock on either the captain or first officer's side.

**Expected behavior**
It should start the clock visible on the PFDs.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.50b17
 - Version 1.6.0cygnus5

**Comment by magknight1** [comment]
Command assigned to button seems correct. Please confirm.

![image](https://user-images.githubusercontent.com/49568118/89834941-22ffd880-db3a-11ea-8db6-887958d95b6b.png)

**Comment by fafaldo** [comment]
Actually the clock looks started as the 'Elapsed time' counter starts working. But the needle of the 'analog' clock nevers starts moving.
