### ISSUE TITLE
F/O inbd displ knob keeps resetting to 100%

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#422]
**Describe the bug**
As you twist the F/O's inbd displ knob it'll reset to 100% by itself.

**To Reproduce**
Try adjusting the display brightness from the F/O side

**Expected behavior**
Should behave as the Captain's does.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.50b17
 - Version 1.6.0cygnus5

**Additional context**
Captain's sides works fine

**Comment by aeroniemi** [comment]
tis kinda expected - it's how it works in current release, because the right side inbd display has to be linked to the left due nd
i guess we could remove the manips for it

**Comment by OldGroof** [comment]
Yeah I knew the ND probably had something to do with the two displays being linked. I think removing the manipulator would be the easiest solution?

**Comment by aeroniemi** [comment]
i think we changed this with cygnus and mfd 7
