### ISSUE TITLE
ENG button inop

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#424]
**Describe the bug**
ENG button on glareshield doesn't work anymore

**To Reproduce**
Press ENG

**Expected behavior**
It should hide/show the additional engine information on the EICAS

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.50b17
 - Version 1.6.0cygnus5

**Comment by magknight1** [comment]
Problem solved on other issue.
