### ISSUE TITLE
manipulator similarities

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#425]
**Is your feature request related to a problem? Please describe.**
It would be good to have similar knobs work in the same way as each other. The ones I have in mind are the mins(baro/radio), baroset(in/hpa) and altitude(auto/1000)

**Describe the solution you'd like**
I think these knobs should work in the same way as they basically all manipulate the same way. The way baroset works is the best way in my opinion. How you just click to change the units then drag/scroll to adjust the subscale. If possible the mins and altitude knobs should work in the same way.

**Describe alternatives you've considered**
Or just change the baroset to the same as mins/altitude. 

**Additional context**
I can't get X-Plane to take a screenshot with my cursor visible so the only way you can see what I mean is to try it yourself.

**Comment by magknight1** [comment]
I will require commands for left and right or a dataref instead of a single command to be able to use mouse wheel. 

![image](https://user-images.githubusercontent.com/49568118/89834591-8c331c00-db39-11ea-95ff-ff01b4e410f3.png)

**Comment by aeroniemi** [comment]
i don't see why they wouldn't agree - they should both use the same tech because they are both almost identical
you can add mousewheel to datatrefs using 
ATTR_manip_wheel <delta>

**Comment by magknight1** [comment]
I tried, but this is a command not a dataref, and it doesn't seem to work with commands.

**Comment by aeroniemi** [comment]
datarefs are available too - just remove the C

**Comment by magknight1** [comment]
Done.
