### ISSUE TITLE
clicking map light dimmer sets it to 0%

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#427]
**Describe the bug**
if you click the map light dimmer knob it'll set the knob to 0%. And you can't click and drag that knob either.

**To Reproduce**
click the knob.

**Expected behavior**
shouldn't do that I believe. And you should be able to click and drag.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.50b17
 - Version 1.6.0cygnus5

**Comment by magknight1** [comment]
Solved by changing manipulators.
