### ISSUE TITLE
Mins reset button inop

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#428]
**Describe the bug**
Clicking the mins reset button doesn't seem to do anything.

**To Reproduce**
Set minimums to a value, say 200ft. then click reset.

**Expected behavior**
It should set the minimums value to 0.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.50b17
 - Version 1.6.0cygnus5

**Comment by magknight1** [comment]
Is this the correct command for the button?

![image](https://user-images.githubusercontent.com/49568118/89834182-afa99700-db38-11ea-860e-74c95e8fa41d.png)

**Comment by aeroniemi** [comment]
it is the correct cmd

**Comment by magknight1** [comment]
Then I don't know why doesn't work. It is the current command asociated with the button.

**Comment by magknight1** [comment]
The aero787/cockpit/decisionBaroRstButton given for this button doesn't seem to show on the simulator.
