### ISSUE TITLE
HUD makes windshield 'invisible'

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#429]
**Describe the bug**
Looking through the HUD makes the windshield 'invisible'.

**To Reproduce**
Look through the HUD in a way that you also look through the windshield.

**Expected behavior**
This shouldn't happen. The window tint should be visible through the HUD.

**Screenshots**
![B7879 - 2020-08-10 13 25 53](https://user-images.githubusercontent.com/39658757/89782463-3ea0ba00-db0d-11ea-882d-becd2985f982.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.50b17
 - Version 1.6.0cygnus5

**Comment by aeroniemi** [comment]
problem solved by disabling HUD - is kinda inevitable due to the way interior glass is drawn by the 11.50- render
