### ISSUE TITLE
Spoilers not showing externally

### ISSUE THREAD

**Issue by J-De-Vries** [magknight/787aviatorsTracker#43]
**Describe the bug**
Even when I manually move the speed brake, the spoilers externally aren't visible. The wing in other words remains flat. Flaps work perfectly.

**To Reproduce**
Out of the box.

**Expected behavior**

I would expect the spoilers to show. 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.2.0B1]

Windows 10, 11.33
**Additional context**

**Comment by aeroniemi** [comment]
It's a known issue, because I switched the 3d datarefs, but the code isn't there for them
