### ISSUE TITLE
APU particle effect missing

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#430]
**Describe the bug**
The APU's exhaust haze has gone AWOL.

**To Reproduce**
Start APU and observe it's exhaust, or lack thereof.

**Expected behavior**
There should be the haze effect like there was before.

**Screenshots**
![B7879 - 2020-08-10 13 28 59](https://user-images.githubusercontent.com/39658757/89782667-a3f4ab00-db0d-11ea-838c-912655d44b1d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.50b17
 - Version 1.6.0cygnus5

**Comment by aeroniemi** [comment]
seems to be working now
