### ISSUE TITLE
to/ga and a/t disconnect

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#431]
**Is your feature request related to a problem? Please describe.**
It would be good to have the a/t disconnect and to/ga buttons added to the throttle quadrants now they are properly modelled.

**Describe the solution you'd like**
The a/t disconnect switches are modelled and are on the sides of the throttle levers. The to/ga buttons are on the front of the levers above the reverser levers. Neither of these buttons have manipulators but they are both modelled. It would be useful for them to work.

**Describe alternatives you've considered**
Aren't really any alternatives.

**Additional context**
![B7879 - 2020-08-10 13 53 53](https://user-images.githubusercontent.com/39658757/89784960-7d387380-db11-11ea-9f98-21b6c8cb3b84.png)

**Comment by aeroniemi** [comment]
they won't be added - there's already too many different manips in the area, and they're both ones that you wouldn't accidentally want to hit - the two commands can be added to your joystick/keyboard in the x-plane settings
