### ISSUE TITLE
FPV Indicator 

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#435]
The flight path vector (FPV) is "a small circular symbol which, when the FPV button on the EFIS is depressed, superimposes over the Attitude Indicator (AI) part of the Primary Flight Display (PFD). The circular symbol represents the aircraft's axis in relation to the vertical and lateral movement referenced to the Earth's surface."

I'd like this feature to be implemented.

**Comment by aeroniemi** [comment]
already exists for a few modes (FPA mostly) - just needs linking to the button
