### ISSUE TITLE
Random Decrease in Speed and movement of the plane

### ISSUE THREAD

**Issue by jjscottypants** [magknight/787aviatorsTracker#438]
The plane during midlfight, if reached a certain speed, will rapidly fluctuate in speed and altitude, all while not following a LNAV flight plan. The plane will also toss and turn when this occurs.

**Comment by aeroniemi** [comment]
I imagine it's probably because you're at either the very top or very bottom of the allowable speed range - try moving to a more standard speed. The best range is 250/310/M082/M085
