### ISSUE TITLE
ENG Button for Captain's MFD

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#440]
**Describe the bug**
ENG button for captain's MFD not working. 

**To Reproduce**
Click the ENG button on captain's MFD. 

**Expected behavior**
Should hide/show secondary engine instruments. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.5
 - Version 1.6 I think

**Comment by aeroniemi** [comment]
duplicate of #424
