### ISSUE TITLE
Rudder moving tiller 

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#442]
**Describe the bug**
When moving the rudder (only tested with rudder axis) the tiller will move slightly. 

**To Reproduce**
While using rudder axis, move rudder. 

**Expected behavior**
The rudder should move nose wheel independently of the nose wheel tiller. 

**Desktop (please complete the following information):**
 - OS: W10
 - X-Plane 11.5
 - Version 1.6

**Comment by aeroniemi** [comment]
Tiller animation should be linked to the axis input from x-plane - the joystick array dataref

**Comment by magknight1** [comment]
Which one is the dataref? I can't find it.

**Comment by boeingguy84** [comment]
so here is the problem im having with 1.6.0 and xp11.50 is the rudder dont work on takeoff roll are landing ,
