### ISSUE TITLE
Cabin chime button not working

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#443]
**Describe the bug**
The cabin chime button does not work. No sound is heard. 

**To Reproduce**
Click "Cabin Chime" on the overhead panel. 

**Expected behavior**
Should hear a ding. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.5
 - Version 1.6

**Comment by magknight1** [comment]
Command and dataref fixed.
