### ISSUE TITLE
MFD (left/right) selector light not illuminated on FO's side

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#445]
**Describe the bug**
The MDF selector light for left/right display is not illuminated on the FO's side. 

**To Reproduce**
Launch aircraft and look at MFD selector buttons on FO side. 

**Expected behavior**
One of the lights should be illuminated. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.5
 - Version 1.6

**Comment by aeroniemi** [comment]
It's expected that you can't change the side that the light is on, but a light should be present on both sides

**Comment by magknight1** [comment]
Is this the correct dataref for the light? ATTR_light_level 0 1 aero787/cockpit/mfd/MFDcontrolsLeft/MFD4LightR
Can't seem to find any issues on my side.

**Comment by aeroniemi** [comment]
the FO side "L" light should be aero787/cockpit/mfd/MFDcontrolsLeft/MFD4LightL
the FO side "R" light should be aero787/cockpit/mfd/MFDcontrolsLeft/MFD4LightR

**Comment by magknight1** [comment]
Dataref was fine, but the exporter wasn't accepting two datarefs repeated. It's fixed.

**Comment by aeroniemi** [comment]
stuff was done to it, but it's still not working in the latest version you sent me  - dataref is changing state just fine, but the light isn't changing position - check MFDcontrolsRIght rather than MFDcontrolsLeft

**Comment by magknight1** [comment]
It was previously mapped to MFDcontrolsRight and it didn't work.

**Comment by aeroniemi** [comment]
the datarefs are fine - I've just made it work using mfd controls right by
editing the obj

**Comment by magknight1** [comment]
Can you show me how it looks in the .obj?

**Comment by magknight1** [comment]
Ok, it is done. Left MFD lights don't change though.
