### ISSUE TITLE
Stuck left aileron causes loss of effective control

### ISSUE THREAD

**Issue by illusorylol** [magknight/787aviatorsTracker#447]
**Describe the bug**
At somepoint random through a flight, the left aileron will get stuck fully deflected and cannot be reset using the yoke. This means the plane can only be flown straight using almost full right aileron and can only barely be turned to the right.

**To Reproduce**
this has happened to me twice, both times when I was not paying super close attention to my computer, so I am not entirely sure how to replicate it. However, it has happened at random intervals in flight. 

**Expected behavior**
The left aileron does not get stuck.

**Screenshots**
Video demonstrating the problem: https://youtu.be/CH3779mzvFg

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.50b17
 - Version 1.6.0 cygnus 5

**Additional context**
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/5055150/Log.txt)
Video demonstrating the problem: https://youtu.be/CH3779mzvFg

**Comment by aeroniemi** [comment]
Autoflight is on - if you want to use manual flight, you need to turn it off.  You also appear to be trimmed rudder left - so it's going to need to apply full aileron responce to maintain level flight
