### ISSUE TITLE
Beacon/nav/strobes all permanently on & battery not working unless....

### ISSUE THREAD

**Issue by DJ-STRE** [magknight/787aviatorsTracker#449]
**Describe the bug**
When you load into the MK787 for the first time after u start xplane,  the nav/beacon/strobes lights stay permanently on + the battery switch doesnt work, unless you change your livery to a different one and then back to the one you were using, that basically fixes the whole problem.  

(The picture with the battery ON is when i changed my livery)

**To Reproduce**
I have no clue how you could fix it.

**Expected behavior**
I expect the battery and lights just working fine without having to change the livery..

**Screenshots**
![B7879 - 2020-08-11 19 28 59](https://user-images.githubusercontent.com/66440539/89929475-873d9d80-dc09-11ea-9ea4-7de5f3b4f852.png)
![B7879 - 2020-08-11 19 29 20](https://user-images.githubusercontent.com/66440539/89929485-89076100-dc09-11ea-8fbc-c7dedca1a906.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - X-Plane version [11.41]
 - Version [1.6.0Cygnus 5]

**Comment by DJ-STRE** [comment]
(Im trying to add my log, but for some weird reason it says ''we dont support that file type'' even tho its a text file lol

**Comment by aeroniemi** [comment]
identical issue to #415, closed as duplicate
