### ISSUE TITLE
Landing Calculator major lag

### ISSUE THREAD

**Issue by CharlieAlphaLima** [magknight/787aviatorsTracker#450]
**Describe the bug**
This was a night flight from OMDB-EGLL and I noticed when I clicked on "Show Landing" I'd get hit with major performance issue down to 20fps from 60fps, once clicking on "Show takeoff" my fps returned to normal 

**To Reproduce**
Steps to reproduce the behaviour: Night flight during the cruise (No idea if same happens in the day haven't tested) head to EFB and click "show Landing" which is when you should be hit with minimal fps

**Expected behaviour**
A clear and concise description of what you expected to happen. A major decrease in fps. i.e stuttering until the takeoff calculator is clicked

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] windows 10
 -  X-Plane 11.50b17
 - Version] 1.6.0 Cygnus 3
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/5058958/Log.txt)
![X-Plane_2020-08-11_19-59-21](https://user-images.githubusercontent.com/57408399/89937610-3e87e380-dc0d-11ea-87bb-84dd51cf0e60.png)
![X-Plane_2020-08-11_19-59-28](https://user-images.githubusercontent.com/57408399/89937622-3fb91080-dc0d-11ea-9b29-7bc0b0447a34.png)

**Additional context**

**Comment by aeroniemi** [comment]
Identical issue to #415, closed as duplicate
