### ISSUE TITLE
a hole in the new cockpit on the right and left side of the ND 

### ISSUE THREAD

**Issue by DJ-STRE** [magknight/787aviatorsTracker#455]
**Describe the bug**
In the new cockpit, there are 2 holes,  one on the left and one on the right of the ND. 

**To Reproduce**
No idea

**Expected behavior**
I expected the new cockpit without any holes. But obviously mistakes happen :) 

**Screenshots**
![image](https://user-images.githubusercontent.com/66440539/90159074-21c7e900-dd90-11ea-8c4e-df64c7b19d3a.png)
![image](https://user-images.githubusercontent.com/66440539/90159198-53d94b00-dd90-11ea-9230-b0cbb641b4d7.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - X-Plane version [11.41]
 - Version [1.6.0Cygnus5]

**Comment by magknight1** [comment]
Needs more research. Can't find solution yet.

**Comment by magknight1** [comment]
The hole was two polys with flipped normals. Solved.
