### ISSUE TITLE
Many Buttons not working

### ISSUE THREAD

**Issue by Pavrilo** [magknight/787aviatorsTracker#457]
I just installed the new update for the 787 and when I start a new flight with cold and dark, many buttons arent working. When I try to press the Battery button, nothing happens, no clicking sound nothing.
I also use the newest version of Xplane.

**Comment by PVD07** [comment]
i have updated 789 from version 1.5.1 to 1.60 version . all is correct for the update process but many buttons  llke power on do not work.
can' you help me from this issue.
thanks  a lot.
PHILIPPE

**Comment by aeroniemi** [comment]
log? 
https://docs.magknight.org/troubleshooting/#someone_asked_for_my_log_-_what_is_it

**Comment by fafaldo** [comment]
Having the same issue, maybe mine will help.
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/5076726/Log.txt)

**Comment by aeroniemi** [comment]
closed as duplicate
