### ISSUE TITLE
White lines in the new cockpit

### ISSUE THREAD

**Issue by DJ-STRE** [magknight/787aviatorsTracker#459]
**Describe the bug**
White lines in the new cockpit on left and right side as shown on the screenshots..

**To Reproduce**
..

**Expected behavior**
I expected the cockpit without any weird lines.

**Screenshots**
![image](https://user-images.githubusercontent.com/66440539/90290992-2cad7700-de7f-11ea-98d7-90229b0d45a7.png)
![image](https://user-images.githubusercontent.com/66440539/90291011-346d1b80-de7f-11ea-9f44-6d683b4b557d.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - X-Plane version [11.41]
 - Version [1.6.0cygnus6]

**Comment by magknight1** [comment]
This is the edge of the pillars making visible the fuselage behind. The fuselage has prefill so it occludes the scenery. Now it's fixed.
