### ISSUE TITLE
CTD When Selecting New Approach

### ISSUE THREAD

**Issue by RCT747** [magknight/787aviatorsTracker#460]
**Describe the bug**
When an approach is already loaded into the sim and a new runway is selected with a different approach a CTD happens.

**To Reproduce**
When flying select your approach including STAR, Runway, and approach waypoint then select a brand new runway and approach.

**Expected behavior**
The sim will freeze and a CTD will happen.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.50 Beta
 - Version 1.60.0 Cygnus 6

**Comment by aeroniemi** [comment]
log?
