### ISSUE TITLE
CVR buttons

### ISSUE THREAD

**Issue by aeroniemi** [magknight/787aviatorsTracker#461]
aero787/cockpit/overhead/cvr/erase (erase manip, command)
aero787/cockpit/overhead/cvr/eraseD (erase animation)

aero787/cockpit/overhead/cvr/test (test manip, command)
aero787/cockpit/overhead/cvr/testD (test animation)
 
all overhead, top right

**Comment by magknight1** [comment]
Are this suppossed to trigger an audio warning? I've tested them and don't do anything.

**Comment by magknight1** [comment]
Commands and datarefs fixed.
