### ISSUE TITLE
Not sure if its a bug:  You can instantly change engines without reloading

### ISSUE THREAD

**Issue by DJ-STRE** [magknight/787aviatorsTracker#462]
**Describe the bug**
Hi, im not sure if this is a bug or a new thing, but when you try to change engines to the RR for example, they instantly change without asking you to reload the plane. (The engines are working fine, its just that they instantly change without having to reload the plane)

**To Reproduce**
No idea

**Expected behavior**
I think we need to reload the plane when changing engines like before, unless thats changed now.

**Screenshots**
(Screenshots wont explain the ''problem'' )

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - X-Plane version [11.41]
 - Version [1.6.0Cygnus6]

**Comment by aeroniemi** [comment]
this is how it's supposed to work
