### ISSUE TITLE
Pitch Brake

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#463]
**Describe the bug**
Pitch brake is enabled for some people upon pushback and does not allow them to push back. The issue can be easily resolved by turning the pitch brake off and back on or pulling back on the yoke. 

**To Reproduce**
'Accidentally' enable the pitch brake by pushing down. This will enable the brake until you pull back on the yoke. 

**Expected behaviour**
The pitch brake should operate in this way. 
1. Full nose down = Full braking
2. When yoke centred = no braking 

3. Upon requesting pushback or throttle advancement (while having pitch brake enabled) the brake should turn off. 

This will remove confusion and act as a fail-safe in case users 'accidentally' enable the pitch brake. 

**Screenshots**
https://youtu.be/km6i6TdmAW0

**Additional context**
This is the reason why DJ-STRE was having pushback and braking problems. 

I don't understand why the 'pitch brake' feature is implemented. But having a failsafe for people who do not know how to use it will be nice.

**Comment by aeroniemi** [comment]
Not a bug - it works how it's intended to. If you don't like it, don't turn it on
