### ISSUE TITLE
Switches and Screens are not working in cygnus7

### ISSUE THREAD

**Issue by AirbusA3559** [magknight/787aviatorsTracker#464]
Hi,
I just updated the Magknight 787 is cygnus7
After updating the screens are blank and the switches are not working.
I have attached my log.txt file below
Can you please look into this issue
Thank you

**To Reproduce**
Starting a new flight everytime from beginning

**Expected behavior**
inoperable aircraft .

**Screenshots**
![img1](https://user-images.githubusercontent.com/69742900/90326688-f8ce7080-dfa8-11ea-94a8-127fda4efa62.PNG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.50b17]
 - Version [e.g. 1.60cygnus7]

Additional info:
logtxt
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/5079999/Log.txt)

l

**Comment by aeroniemi** [comment]
closed as duplicate
