### ISSUE TITLE
787 stops descending after 4000ft on ALT HOLD mode.

### ISSUE THREAD

**Issue by esperez0802** [magknight/787aviatorsTracker#465]
**Describe the bug**
When on descent enroute to an airport, I manually select my altitudes and V/S speeds. I set my altitude to go down to 3000ft, as instructed by ATC but, the plane stops descending at 4000ft. I try re engaging V/S but after a second it levels back to 4000ft. This has happened to me 2 times already.
**To Reproduce**
Descend into an airport via radar vectors with manual altitude select and V/S speeds.

**Expected behavior**
The aircraft should have descended to 3000ft instead of leveling off at 4000ft.

**Screenshots**
I'll try to upload a video on my next flight.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.50b17
 - Version 1.6.0-cygnus7

**Additional context**

**Comment by aeroniemi** [comment]
it seems to be something that default tech is doing-  not much we can do about it before cdu2

**Comment by esperez0802** [comment]
what do you mean? how can i bypass this problem?
