### ISSUE TITLE
Vertical speed wheel animation occurs with no input during descent phase.

### ISSUE THREAD

**Issue by willhenwood** [magknight/787aviatorsTracker#466]
**Describe the bug**
V/S wheel on MFD has moving animations when not being used during descent phase.

**To Reproduce**
Steps to reproduce the behavior: Happens when VNAV descent mode in default FMC is active. Does not occur during climb phase of flight.

**Expected behavior**
Shouldn't move! But only the animation of the V/S wheel is occurring, there is no manipulation of the dataref in the simulator itself (i.e VNAV descent profile performs as expected).

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: W10 1909.
 - X-Plane version - 11.50RC1
 - Version - 1.6.0-cygnus8

**Additional context**
Nothing else so far, I'm happy with what you folks are doing with the 789 so far, great progress!

**Comment by aeroniemi** [comment]
That's how (default) VNAV works - it uses other modes to get what it needs. Not inherently a bug

**Comment by willhenwood** [comment]
Understood, many thanks for your prompt response.
