### ISSUE TITLE
Double click to move camera not working on EFB

### ISSUE THREAD

**Issue by fafaldo** [magknight/787aviatorsTracker#473]
**Describe the bug**
Double clicking of the right mouse button, which is used in X-Plane to move camera around freely (using mouse), does not work when pointed to the EFB.

**To Reproduce**
Try double clicking the right mouse button while pointer is above EFB screen to move camera.

**Expected behavior**
This movement mode can be started/ended also when clicking on the EFB.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.41
- Version1.6.0 cygnus8

**Comment by aeroniemi** [comment]
is this different to the way that cdu/comm work?

**Comment by fafaldo** [comment]
Actually I have to make one small correction to what I stated above: in X-Plane double click starts camera panning and single click stops it. If you start panning outside of the EFB you can stop it on the EFB. But you cannot start it here - double click does not work.

This is in fact different - all seems to be working in other displays and CDU.
