### ISSUE TITLE
787 still flies with center fuel tanks even without fuel in the center fuel tanks

### ISSUE THREAD

**Issue by esperez0802** [magknight/787aviatorsTracker#475]
**Describe the bug**
When the center fuel tanks run out of fuel and without disengaging the center fuel pumps, the plane continues flying without using the fuel from the wings, and continues to run on the center fuel tank, even if empty.

**To Reproduce**
Fill the center fuel tank and continue flying until the center fuel tanks run out of fuel. Don't disengage the center fuel pumps and notice that the fuel from the wings are not being used and the plane still continues to fly.

**Expected behavior**
Either the wing fuel pumps will be used and the fuel from the wings will decrease as the plane continues flying, or the plane will go in a dive since the lack of fuel being fed to the engines.

**Screenshots**
No screenshot, but the fuel tab in the flight display shows that the fuel from the center tanks are still feeding the engine. (The green lines are directed to the engines from the center fuel tank rather than the wing fuel tanks)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - X-Plane version 11.50
 - Version 1.6.0 cygnus-7

**Additional context**

**Comment by aeroniemi** [comment]
i can't replicate this, at least not directly - when the central tank gets to ~1500kg feed is switching to the outer tanks as expected

**Comment by esperez0802** [comment]
without having to turn of the center fuel pump switches?

**Comment by aeroniemi** [comment]
yes - when you turn them off it scavenges the fuel to the outer tanks, so they appear to not decrease in fuel until the central tank is actually empty

**Comment by esperez0802** [comment]
okay, i'll try with the new update.

**Comment by aeroniemi** [comment]
nothing has been changed with the new update, or any recently
