### ISSUE TITLE
Visiting GPWS tab of the radio stack causes a ~75% drop in FPS

### ISSUE THREAD

**Issue by christianh727** [magknight/787aviatorsTracker#479]
Description:
Switching to GPWS tab of the radio stack (captain side only) causes drop in fps from my average of 50fps to around 10-14fps. Log shows repeated errors in SASL, but fps normalizes in the exterior view.
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/5180853/Log.txt)

Reproduction:

Load into 787 anywhere and establish power (Or just start with engines running)
Go to the GPWS tab on the radio stack and check fps
Switch back to any other tab and check fps

Expected Behaviour
Visit the tab without ~75% drop in fps

Desktop:

Windows 10 (2004 Update)
X-Plane 11.50r2
1.6.0r2

**Comment by aeroniemi** [comment]
not able to replicate this - i'd guess that you've probably got outdated files somewhere that are being loaded

**Comment by christianh727** [comment]
yea it was my fault, didn't update to 1.5.1 before the beta. Only found out that you were supposed to update after i did and it seemed to work without it so i didn't bother until now.
