### ISSUE TITLE
Aero787 caused CTD when re-selecting STAR/VIA/Approach

### ISSUE THREAD

**Issue by frayedends** [magknight/787aviatorsTracker#481]
About halfway during a flight, the FMC was no longer showing the STAR fixes in the LEGS page.   The flight plan had been programmed as:
KDEN/17L BAYLR6 TEHRU DCT JASSE Q90 DNERO ANJLL4 KLAX/25L

The LEGS page was showing DNERO as the last waypoint.   I had verified the entire flight plan was entered, and checked it via steps on the PLAN menu on the ND prior to take off.

Enter the FMC arrival page, the Runway, STAR, VIA, and Transition were all showing selected at the top.
I unselected the runway, which cleared the transition.
I reselected the runway, then selected the DNERO transition.
Sim froze immediately, then CTD.

Log file and .dmp file from output/crash_reports is attached.

[f25cf8fe-8193-4114-ac45-5e51e59d4992.zip](https://github.com/magknight/787aviatorsTracker/files/5233885/f25cf8fe-8193-4114-ac45-5e51e59d4992.zip)
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/5233886/Log.txt)

**Comment by aeroniemi** [comment]
not able to reproduce this with given instructions - can you reliably reproduce it in the 787 or default 737?
