### ISSUE TITLE
Windshield shown through fuselage

### ISSUE THREAD

**Issue by Falsetax** [magknight/787aviatorsTracker#482]
**Describe the bug**
a small piece of the windshield  shows through the fuse

**To Reproduce**
load the sim and look at the windshield

**Expected behavior**
no windshield showing through the fuse

**Screenshots**
http://prntscr.com/uj2k16

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.50r3]
 - Version [e.g. 1.6.0-rc3]

**Additional context**
yeah please fix it.

**Comment by aeroniemi** [comment]
resolved by new fuselage
