### ISSUE TITLE
FMS 1.6 page number does not erase first digit

### ISSUE THREAD

**Issue by jengle53** [magknight/787aviatorsTracker#483]
**Describe the bug**
Enter or import a longer flight plan.  From LEGS scroll through the pages.  Once you past page 10 if you go back to page 1 it shows 11.  Move to page 2 and it shows 12, etc.

**To Reproduce**
Create or import longer flight plan.  Enter departure/arrival.  Go to legs to clean things up.  NEXT past page 9, then go back to page 1.

**Expected behavior**
correct page number should show.

**Screenshots**
Screenshot shows page 1 after scrolling through the flight plan.  It indicates that it is page 11.

![2020-09-21 Magknight Page Error FMC](https://user-images.githubusercontent.com/59061142/93840182-5444eb80-fc44-11ea-8117-4fc284eeec71.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.50
 - Version 1.6

**Additional context**

**Comment by aeroniemi** [comment]
bug report filed to laminar

**Comment by aeroniemi** [comment]
LR bug ID: XPD-11063
