### ISSUE TITLE
Flaps lever Issue

### ISSUE THREAD

**Issue by nic0l45** [magknight/787aviatorsTracker#484]
**Describe the bug**
Flaps get stucked at 2 deg, even I put the flap lever to 25 deg

**To Reproduce**
Flap lever

**Expected behavior**
Extend the flaps according the flaps lever
**Screenshots**

![image](https://user-images.githubusercontent.com/48603062/93880439-7e7dc400-fcab-11ea-8ba4-e4fe66c3b86b.png)

**Desktop (please complete the following information):**
 - OS: WIN 10
 - X-Plane version 11.50
 - Version RC3 Final

**Additional context**

**Comment by aeroniemi** [comment]
how long does "stuck" mean?

**Comment by nic0l45** [comment]
> how long does "stuck" mean?

About 10 minutes before landing

**Comment by aeroniemi** [comment]
Flaps and other flight control surfaces do not work in replay mode.

**Comment by nic0l45** [comment]
> Flaps and other flight control surfaces do not work in replay mode.

I was on flight when had the issue, even the screen shot it's not in replay mode

**Comment by aeroniemi** [comment]
I can't replicate this with the given instructions
