### ISSUE TITLE
Uncontrollable AP Sink rate

### ISSUE THREAD

**Issue by nic0l45** [magknight/787aviatorsTracker#485]
**Describe the bug**
When I was descending to 2,000 to capture the LOC the plane tried to level off and it goes up and down quite heavely. Had to fly it manual.

**To Reproduce**
Used FLCH to 2,000

**Expected behavior**
Level off at 2,000, not up and down at  uncontrollable Sink rate

**Screenshots**
![image](https://user-images.githubusercontent.com/48603062/93881743-4ecfbb80-fcad-11ea-929d-563d58afe0da.png)
*Replay mode* MCP was AP on, ATL Hold and A/T on

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.50
 - Version RC3

**Additional context**

**Comment by aeroniemi** [comment]
I can't really see what is the problem - don't use flch for small low speed
altitude changes.

**Comment by nic0l45** [comment]
> I can't really see what is the problem - don't use flch for small low speed altitude changes.

Ok I'm gonna use V/S for the next time
