### ISSUE TITLE
1.6 Des Now does not work

### ISSUE THREAD

**Issue by jengle53** [magknight/787aviatorsTracker#486]
**Describe the bug**
Select Descend Now from the VNAV page 3 - does not descend.  Speed reduces, but no descent.

**To Reproduce**
select Des Now from VNAV page 3

**Expected behavior**
Start early descent to intercept descent

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - X-Plane version 11.50
 - Version 1.6 current beta

**Additional context**

**Comment by aeroniemi** [comment]
duplicate of #657
