### ISSUE TITLE
Start IRS alignment does not initially indicate battery

### ISSUE THREAD

**Issue by jengle53** [magknight/787aviatorsTracker#487]
**Describe the bug**
In the past the 787-9 flashed a battery message before starting alignment.  1.6 released does not.

**To Reproduce**
Start plane cold and dark
Press battery button
connect GPU from EFB
connect ext. power
start IRS alignment

**Expected behavior**
It should flash Batt or Battery when starting alignment

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.50
 - Version 1.6 from org store

**Additional context**

**Comment by Delta-Lima** [comment]
I fully agree

**Comment by aeroniemi** [comment]
i'd imagine it's a art-dataref issue

**Comment by Delta-Lima** [comment]
I had the same issue but only at the beginnig using the 1.6 version (can't remember how often). I didn't change anything, and now I have again the indication "ON BATTERY" when starting the IRS alignment.
This is why I removed my initial comment on that.

**Comment by aeroniemi** [comment]
it does appear to do this - issue marked as resolved
