### ISSUE TITLE
Out of order waypoints from selections in Arr/Dep menu

### ISSUE THREAD

**Issue by frayedends** [magknight/787aviatorsTracker#489]
Synopsis:

After entering a flightplan, went to enter the arrival.   Clicking on the Dep/Arr button gets you to select the departure or arrival.  In this case, select arrival.   

The example I have uses KLAX as the arrival airport, the STAR to select is the ANJLL4, with the HAKMN transition and runway 25L.

If you select the runway first, then the STAR, then transition, the waypoints will show up in the FMS out of order, but you do get an error message on the FMS, but it still inserts them.   Your last fix before the 1st waypoint of the STAR will have a discon after it, then the waypoints HUNDA and LIMMA, which are the final two for 25L, then the go-around and hold waypoints, then another discon, then you'll see HAKMN and the rest of ANJLL4.   

I haven't tried it in the default FMS, but I did in the Zibo and the Zibo orders them correctly, even if I don't select them in that order.   It's reproduceable.   Just key up a flight to KLAX and try it.  

Sorry didn't snap a screenshot, but I spent 10 minutes entering and deleting this until I figured out the selection order was what was causing it.

**Comment by aeroniemi** [comment]
Can you reproduce this (preferably with video) in the default 737?

**Comment by frayedends** [comment]
Yeah, I'll do some recording today and see if I can capture it for you.   Also #481 as well.

**Comment by aeroniemi** [comment]
I'm surprised it doesn't error, as it should be star then transition then runway - it enforces that order with all of the airports i've tried
