### ISSUE TITLE
Calculated N1% is very low

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#49]
**Describe the bug**
When you do all the take off performance stuff on the EFB the calculated N1 % is very low, around 50%? Not sure if that's something I'm doing to produce this.

**To Reproduce**
Enter in any W&B values at any airport and in the ATM input box enter in a value around 55-70C and it will produce a very low N1 % after calculating.

**Expected behavior**
A value of around 90-95% N1?

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.32
 - Version 1.2.0(latest)

**Additional context**

**Comment by aeroniemi** [comment]
@OldGroof  Are you still seeing this with the latest betas (1.3.0b4+)?
