### ISSUE TITLE
F/O's altimeter reverts back to hPa after each X-Plane restart

### ISSUE THREAD

**Issue by Phil787-9** [magknight/787aviatorsTracker#491]
**Describe the bug**
I use the shared barometer option in the EFB and inches of mercury as a unit exclusively on both altimeters. However, each time I restart X-Plane and load into the 787, the F/O's altimeter reverts back to hPa as a default unit

**To Reproduce**
Use "Shared barometer" in the EFB and select inHg as default in the EFB

**Expected behaviour**
The altimeter should stick to the default unit inHg. (The Captain's altimeter works fine, only on the F/O side the switch is observable)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version: 11.50
 - Version: 1.6.0

**Additional context**

**Comment by aeroniemi** [comment]
Can't replicate that directly, although when you click the inhg/hpa switch on one side it doesn't automatically switch the other - won't fix that due to the way it's designed
