### ISSUE TITLE
Engine Fire Handle is turnable even if FH is not pulled

### ISSUE THREAD

**Issue by GhostGCR** [magknight/787aviatorsTracker#492]
**Describe the bug**
The Engine Fire Handle is turnable even it is not pulled prior turning.

**To Reproduce**
Just hover the fire handle with your mouse and turn the mouse wheel.

**Expected behavior**
I'm not familiar with the real 787, but it seems not real to me, that the fire handle is turnable without any protect mechanism like pull before turning.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.5
 - Version 1.6.0-2

**Additional context**

**Comment by aeroniemi** [comment]
i'm not entirely sure the fire handle does anything at all - it's mostly just there for show

**Comment by aeroniemi** [comment]
with the latest version of the cockpit it is just one state, so i think this has gone away in its original form
