### ISSUE TITLE
Fuel cut-off mid flight ~ 9+ hours

### ISSUE THREAD

**Issue by jengle53** [magknight/787aviatorsTracker#493]
**Describe the bug**
At just over 9 hours of flight I am put into a stall situation with fuel flow cut off.  I have to turn off A/T arm, and auto throttle, flip fuel control to cutoff, flip the start button on for the engines and turn fuel flow back on.  This has happened on 4 flight in a row.  I have re-installed from the store version of magknight.  It has happened both before and after center tanks are empty - but close to that point.

**To Reproduce**
Fly on a long flight, doing step climbs as proscribed. 

**Expected behavior**
Engines should not cutoff midflight 

**Screenshots**

![787_stall](https://user-images.githubusercontent.com/59061142/95454185-f4776180-0920-11eb-83e3-580bb781b824.jpg)

I'll do a video on the next flight later today.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] Windows 10
 - X-Plane version [e.g. 11.30r2] 11.50
 - Version [e.g. 1.2.0B1] 1.6 (store download)

**Additional context**

**Comment by jengle53** [comment]
2 shorter flights and 1 long flight, and it didn't happen.  However it happened again - 12 hrs  17 minutes into  flight this morning.  The only errors were fuel out on center tanks and they were down to about .2 tons.  Didn't catch it on video again though.  Will try again on video.  Fuel cuts out and both engines fail.  Getting pretty quick about engine restarts now though.  X-Plane log has no entries.

**Comment by aeroniemi** [comment]
does this still happen with 1.6.7?

**Comment by jengle53** [comment]
Good question. I’ll try a > 9 hr flight this weekend. 

Jeff

**Comment by jengle53** [comment]
I checked my log and I have flown at least 1 flight greater than 12 hours with no incident.  The last was March 1st NZAA to KLAX on the **current BETA at that time**; so it looks like the issue has been resolved.  _Several flights in the 6 hour frame, but the issue was with > 9 hours._  I think this can be closed now.  Thanks for following up!

Jeff

**Comment by aeroniemi** [comment]
That's good! Fuel sys changes were shipped as part of the 1.6.7 alpha a
while back, so hopefully the issue has now (permenantly) gone away
