### ISSUE TITLE
APU Generators

### ISSUE THREAD

**Issue by Delta-Lima** [magknight/787aviatorsTracker#494]
Whenever launching the version 1.6 in a cold and dark mode, the APU generator switches left and right are ON. In my opinion they should be OFF (as it was in previous versions).

**Comment by aeroniemi** [comment]
no - they should be left on between flights, and only turned off for long
term shutdown. we fixed this based on new data in 1.6.0

**Comment by Delta-Lima** [comment]
Thank you for quick reaction and information. So i will leave it ON when shutting down the aircraft.
