### ISSUE TITLE
NOTAM uplink from simbrief

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#496]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
On the performance pages of the EFB there is a notams button. Have that selectable and have it show the list of notams that simbrief gives you on the OFP

**Describe alternatives you've considered**
Not sure what the alternatives would be.

**Comment by aeroniemi** [comment]
need to find a way that is actually sensible to display these - unsure at present
