### ISSUE TITLE
TCAS icons are rendered underneath other elements and are impossible to read

### ISSUE THREAD

**Issue by Kahn** [magknight/787aviatorsTracker#497]
**Describe the bug**
TCAS icons are rendered underneath other ND elements

**To Reproduce**
1. Position aircraft for TCAS returns
2. Note the TCAS icons are both tiny and rendered **below** the heading, compass rose and aircraft icons

**Expected behavior**
TCAS icons should be clearly visible and on top of ND elements such as http://www.b737.org.uk/images/ndmap.jpg

**Screenshots**
https://steamcommunity.com/sharedfiles/filedetails/?id=2273773627
https://steamcommunity.com/sharedfiles/filedetails/?id=2273773679

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.50
 - Version 1.6.2

**Additional context**

**Comment by aeroniemi** [comment]
That's unfortunately how the default displays work - new ND, perhaps with TCAS will be added as part of ND2
