### ISSUE TITLE
ND waypoint time is blank

### ISSUE THREAD

**Issue by Kahn** [magknight/787aviatorsTracker#498]
**Describe the bug**
Waypoints displayed on the ND have a name, blank space, Z and range. The waypoint time is missing despite being available in the CDU

**To Reproduce**
1. Set a waypoint
1. Observe ND

**Expected behavior**
1. The ND waypoint display matches CDU data

**Screenshots**
https://steamcommunity.com/sharedfiles/filedetails/?id=2273829534

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.50
 - Version 1.6.2

**Comment by aeroniemi** [comment]
Tis an x-plane bug - not going to change due replacement by ND2
