### ISSUE TITLE
Loading A/C issues

### ISSUE THREAD

**Issue by tsftt27** [magknight/787aviatorsTracker#499]
**Describe the bug**
After a few seconds on loading the Airplane (787 Aviator edition) it crashes the simulator. Log mentions error on the plugin aero787 (SASL). V1.6.2 is the one used.

**To Reproduce**
Select any airport to spawn the plane in, livery not a factor.

**Expected behavior**
Simulator Crash.

**Screenshots**

Loaded: D:\X-Plane 11/Aircraft/Laminar Research/Magknight787/plugins/Librain/64/win.xpl (skiselkov.librain).

[AERO787 INFO]: Starting X-Plane SASL plugin v3.9.0+890d171 [Commercial Edition]
[AERO787 INFO]: aero787 | Aircraft | Start Full
[AERO787 INFO]: Loading cursors...
Loaded: D:\X-Plane 11/Aircraft/Laminar Research/Magknight787/plugins/SASL/64/win.xpl (1-sim aero787).

GRPAHICS LIBRARIES SUCCESFULLY INITED
[AERO787 INFO]: Enabling...
[AERO787 INFO]: Sound output device: OpenAL Soft
[AERO787 INFO]: Sound input device: OpenAL Soft on Conjunto de microfones (Realtek High Definition Audio)
[AERO787 INFO]: Initializing...
[AERO787 INFO]: Path to module: D:\X-Plane 11/Aircraft/Laminar Research/Magknight787/plugins/SASL/data/modules/main.key
[AERO787 INFO]: Loading module...
[AERO787 INFO]: [LUA]: loading	module
--=={This application has crashed because of the plugin: aero787 (SASL)}==--

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - X-Plane version: 11.50
 - Version: V1.6.2

**Additional context**
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/5484509/Log.txt)

**Comment by aeroniemi** [comment]
delete ``D:\X-Plane 11/Aircraft/Laminar Research/Magknight787/plugins/SASL/data/modules/main.key`` and reactivate - known SASL bug
