### ISSUE TITLE
V/S not working properly

### ISSUE THREAD

**Issue by Frantimir** [magknight/787aviatorsTracker#500]
**Describe the bug**
When A / P is on, V / S and FLCH do not work, while A / T is out or the game is paused, then V / S works and can be pressed. Does anyone know how to fix this?

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.50]
 - Version [e.g. 1.2.0B1]

**Additional context**

**Comment by aeroniemi** [comment]
i don't understand the problem - you can't use other vertical/speed modes when vnav is enabled.
