### ISSUE TITLE
Before Start/After Start checklist flaps

### ISSUE THREAD

**Issue by dreckiger0dan** [magknight/787aviatorsTracker#504]
The Before Start and After Start checklist contain the item "Flaps ............................................. Landing". AFAIK flaps are not only not contained in at least the before start checklist (I think first time they come up is the Before Takeoff checklist) but they certainly are not set for "landing". 

**To Reproduce**
Use the checklist and go through the items.

**Expected behavior**
Certainly not the flaps being set for landing before I even took off.

**Screenshots**
https://discordapp.com/channels/565054778036453381/633261384511127552/782566471531757598

**Desktop (please complete the following information):**
 - OS: W10
 - X-Plane version 11.51b2
 - Version v1.6.4

**Comment by aeroniemi** [comment]
it's just the before landing checklist - i've added new checklists for the two states in 1.6.6
