### ISSUE TITLE
Custom cursor visible, even if turned off

### ISSUE THREAD

**Issue by PeeWee-Sweden** [magknight/787aviatorsTracker#507]
**Describe the bug**
Despite having set "Custom Cursor" to "OFF" on the EFB, it's visible on the MFDs (not the ND part, but the other) as well as on the FMC displays. 

**To Reproduce**
Set "Custom Cursor" to "OFF" on the EFB, look at the MFD's and FMC displays and move your mouse over them. 

**Expected behavior**
I expect no custom cursor to be visible. 

**Screenshots**
https://i.imgur.com/NUuEOUm.png
https://i.imgur.com/OnAWd8c.png

**Desktop (please complete the following information):**
 - Win 10
 - X-Plane version 11.50r3
 - 1.6.6

**Comment by aeroniemi** [comment]
not sure that this is actually used that much, so it'll likely be removed when we do the other types of cursor in the near future

**Comment by aeroniemi** [comment]
has been fixed, although the option will likely be removed from UI in 1.7.0
