### ISSUE TITLE
ACARS not working

### ISSUE THREAD

**Issue by theduusK** [magknight/787aviatorsTracker#508]
**Describe the bug**
ACARS services does not seem to work for me.
Messages can be sent, but no messages can be received.
Also the "Paste" Button does not work to paste the copied code.

**To Reproduce**
Insert Hoppies ACARS Code into the COMM/Manager/ACARS page and enable the option.
Go to Flight Information and try to send ATIS / METAR / TAF requests for online and offline stations (VATSIM).
The message also doesn't appear in Hoppies log online (https://www.hoppie.nl/acars/system/log.html)

**Expected behavior**
Messages with the requested information should be received.

**Screenshots**
![Screenshot_143](https://user-images.githubusercontent.com/12185183/101095555-6507cb00-35be-11eb-8cb9-cb6bd71c8848.png)
![Screenshot_144](https://user-images.githubusercontent.com/12185183/101095557-65a06180-35be-11eb-99ba-24899ee851c7.png)
![Screenshot_141](https://user-images.githubusercontent.com/12185183/101095558-6638f800-35be-11eb-8409-4564131b9681.png)
![Screenshot_142](https://user-images.githubusercontent.com/12185183/101095560-66d18e80-35be-11eb-9922-0f5fe95b81c8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (v 20H2)
 - X-Plane version 11.50
 - Version v1.6.6

**Additional context**
I also checked the Hoppies Log page and couldn't find any kind of messages related to my callsign.
My code is still valid and working. Could it be related to case-sensitivity? My code has upper- and lower case signs,
but in the Sim I only can add uppercase.

The only error I was able to find in the X Plane log:
```
[AERO787 ERROR]: [STACK]:| IZxPl9S : [LUA]: "module"	HTTP response code said error
[AERO787 ERROR]: [STACK]:| [string ".../initMain.secured"]:0 in function <IZxPl9S>
[AERO787 ERROR]: [STACK]:| [string "acarsPoll"]:26 in function <?>
```

**Comment by aeroniemi** [comment]
The error message implies it's a hoppie-network issue, rather than a 787
one. I used ATIS request on my flight today without issue, so it's likely
just a intermittent server issue

**Comment by theduusK** [comment]
Hey,

I'm not sure about that. I checked the logs page of Hoppies and it doesn't seem to be an issue there.
Also I was able to sent manually created messages.

**Comment by theduusK** [comment]
Tried it today as well, but no chance. I simply get no response.
![Screenshot_146](https://user-images.githubusercontent.com/12185183/101220463-0017a800-3686-11eb-9fb0-281b24c933e1.png)
![Screenshot_147](https://user-images.githubusercontent.com/12185183/101220465-0148d500-3686-11eb-853e-89a049d38edd.png)

**Comment by aeroniemi** [comment]
are you sure your code is valid? try entering it in the settings file (787/globalSettings.json, acarsLogonCode)

**Comment by theduusK** [comment]
The code is definitely correct and valid. 
The only thing I'm wondering, you can only insert the code with upper-case letters, although my code as upper- and lower-case letters. The code is correct added into the globalSettings.json, but only with upper-case letters.
I will try to change the code in the json file to the correct "layout" upper- and lower case letters and see what happens.
Just have to wait a while cause I'm in a long-haul right now :)

**Comment by theduusK** [comment]
Hey again,

after I added the code manually into the globalSettings.json (**with the correct upper- and lowercase letters**) its working now!

But there still seem to be a bug or way to improve that function as there seems to be an issue with upper- and lowercase letters.

**Comment by aeroniemi** [comment]
How many chars is your hoppie code? the paste function is set up to only
allow valid codes - it's possible you've got a code that isn't classified
as 'valid' according to their docs

**Comment by theduusK** [comment]
My hoppie code has 8 chars, including upper-/lowercase letts and numbers.

**Comment by aeroniemi** [comment]
you can only enter upper-case by typing, although you can do lower/special using the paste button, which is how it's designed to be used really - didn't think it worth adding support for lower case for one single box

**Comment by CaptainAlex787** [comment]
Where can I get a Hoppies Code on Vatsim? And does the acars work in the 787 for requesting clearance etc?

**Comment by aeroniemi** [comment]
@CaptainAlex787 see the docs at https://docs.magknight.org/acars/
