### ISSUE TITLE
 Flaperons don't stay deployed after touch down.

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#51]
**Describe the bug**
The flaperons don't stay deployed after touch down.

**To Reproduce**
Land in normal config: spoilers armed, flaps full etc.

**Expected behavior**
They should stay fully deployed until the speed brakes are disarmed.

**Screenshots**
![B7879_4](https://user-images.githubusercontent.com/39658757/57659324-dd242f80-75d9-11e9-86cc-9048a4dd6607.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.32
 - Version 1.2.0(latest)

**Additional context**

**Comment by aeroniemi** [comment]
They go back to normal mode at something like 60kts, per the FCOM

**Comment by OldGroof** [comment]
I watched a few videos last night, and the flaperons stats deployed until the speed brakes are retracted. At the moment you get to about 100knts, they retract and then extend again around 40-50knts

**Comment by aeroniemi** [comment]
That might suggest that the logic for the droop on takeoff is overriding in that range, i'll investigate
