### ISSUE TITLE
Altimeter can't be set to values below 29.00 inHg

### ISSUE THREAD

**Issue by Phil787-9** [magknight/787aviatorsTracker#511]
**Describe the bug**
The main altimeter on both captain and FO side cannot be tuned to values below 29.00. The altimeter on the small PFD above the gear selector works fine and can be tuned to lower values.

**To Reproduce**
Try selecting an altimeter below 29.00 inHg

**Expected behavior**
As such low pressure numbers (below 29.00) do exist (e.g. at PAEN on the 02/01/2021), I expect them to be selectable via the aircraft's altimeter.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version: 11.51
 - Version: 1.6.6

**Comment by aeroniemi** [comment]
I've upped the range to meet SAE AS8009C, using 931-1067 (27.50-31.50)
