### ISSUE TITLE
FMC not work

### ISSUE THREAD

**Issue by cherrymx89** [magknight/787aviatorsTracker#512]
**Describe the bug**
SPANISH:
buenas, tengo un problema con el FMC al poner el destino pone "invalid entry" con los airac 2010 al 2014 y no carga el arhivo .fms y adjunto mi LOG.txt.

Tambien reinstale el avion con todo y los airac por default, y asi no quiere. porfavor ayuda me.

ENGLISH:
good, I have a problem with the FMC when putting the destination puts "invalid entry" with the airac 2010 to 2014 and does not load the .fms file and I attach my LOG.txt.

Also reinstall the plane with everything and will air them by default, and you don't want to. please help

**Screenshots**
![B7879 - 2021-01-05 22 03 37](https://user-images.githubusercontent.com/58763366/103727828-e24da380-4fa1-11eb-82fe-0a4f8530d97a.png)

 - OS: [e.g. Windows 10]
 - X-Plane version [11.51r1]- AIRAC 2013-2014
 - Version [1.6.6]
 
LOG:
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/5773861/Log.txt)

**Comment by aeroniemi** [comment]
X-plane is stating that it does not have navdata for MMMY - in other words,
it the airport does not exist. This isn't a 787 issue, it is likely to be
caused by your navdata not containing the airport. You may want to contact
your navigation data provider about this.
