### ISSUE TITLE
Alpha 4 - missing objects on upgrade

### ISSUE THREAD

**Issue by jengle53** [magknight/787aviatorsTracker#514]
**Describe the bug**
Failure to find ojbects/OBJ file is bad error message when starting

**To Reproduce**
start x-plane; select magknight 787

**Expected behavior**
no error message about missing objects
[Log_MagKnight.txt](https://github.com/magknight/787aviatorsTracker/files/5853624/Log_MagKnight.txt)
![magknight](https://user-images.githubusercontent.com/59061142/105447107-69e51480-5c28-11eb-8b43-33a897792f99.jpg)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - window 10
 - X-Plane version [e.g. 11.30r2]
 - 11.51r1
 - Version [e.g. 1.2.0B1]
v1.6.7-alpha4
**Additional context**
tried different liveries and that didn't make any difference

**Comment by aeroniemi** [comment]
expected behaviour - not missing, just not correctly defined
