### ISSUE TITLE
CTD after trying to select new STAR

### ISSUE THREAD

**Issue by Callero** [magknight/787aviatorsTracker#515]
**Describe the bug**
Having performed touch and go at ESMS rw17 with the airplane in AT/AP, I tried to go to the route page and select a new STAR/rw. The sim then crashed to desktop.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version: X-Plane 11.52r1 (build 115200 64-bit 3e2c383f64d2b13b450f03e946072b2008e4762b)
 - Version: Latest per Skunkcraft

Last lines of Log.txt

`[AERO787 DEBUG]: [LUA]: minimums
[AERO787 INFO]: [LUA]: "flightControlsCore"	put them away
[AERO787 DEBUG]: [LUA]: approaching minimums
--=={This application has crashed because of the plugin: aero787 (SASL)}==--`

**Comment by Callero** [comment]
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/6075524/Log.txt)

**Comment by Callero** [comment]
Reproduced
1. Perform touch and go
2. Load Coroute
3. On CDU Go to dep/arr
4. Click on STAR -> Crash to desktop

Will try to produce video

**Comment by aeroniemi** [comment]
I would guess from that log that it is either a bug related to the default FMS, or not actually affected by you doing stuff with the STAR - that's one of the few circumstances where you're interfacing directly with the default FMS, rather than one of our overlays
