### ISSUE TITLE
Invalid RWY/ARPT selection on EFB perf calulator

### ISSUE THREAD

**Issue by ZaccJacc** [magknight/787aviatorsTracker#516]
On the EFB perf calculator, it sometimes throws the invalid ARPT/RWY selection error even when it isn't wrong. (I got it on the takeoff perf calc, LFBO 32L)

It only happens at certain airports so I think it may be an error with the xp11 FMC more than anything, but when you press CALC after entering the departure details like QNH and WND/KTS it just doesn't take it.

It's supposed to just calculate happily.

I don't have any screenshots.

 - OS: Windows 10 Enterprise
 - X-Plane version 11.52r1
 - Version 1.6.7-alpha4

Only occasionally happens and it's never happened for the landing calc yet

**Comment by aeroniemi** [comment]
Right... Log? video?
It's likely caused by a mismatch in your GNS430 navdata, where it doesn't quite follow the published format (grr navigation providers)

**Comment by ZaccJacc** [comment]
Ha yeah actually, that makes sense. When i installed I ran the GNS installer and installed it to my custom data although I don't think that was the right place because it doesn't seem to think that's the nav data in the fmc... Where am I supposed to install the  GNS430 to in order for it to work properly?

**Comment by aeroniemi** [comment]
that is the correct way - navigraph (and others) parsers and data isn't
perfect

**Comment by ZaccJacc** [comment]
Ok... XP11 doesn't appear to have recognised the data though?
![X-Plane Screenshot 2021 03 08 - 17 30 04 39](https://user-images.githubusercontent.com/58274381/110358270-20178880-8034-11eb-8ae0-66b8aa0016c7.png)

It appears to still think the x plane default data is in use

**Comment by aeroniemi** [comment]
x-plane doesn't use it - it's only used by the EFB. x-plane uses the 11 dataset

**Comment by ZaccJacc** [comment]
ok so if I used the GNS installer provided with the 787... what is likely to be the problem with my NAV data? Is there an immediately obvious way I could fix this or will it take a bit longer?
