### ISSUE TITLE
Ailerons Don't deploy on touch down

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#52]
**Describe the bug**
The ailerons don't deploy on touch down as they should.

**To Reproduce**
Land the aircraft in normal config.

**Expected behavior**
They should deploy with the spoilers and stay deployed until speed brakes are disarmed.

**Screenshots**
![B7879_4](https://user-images.githubusercontent.com/39658757/57659540-98e55f00-75da-11e9-9039-ede292fa4c7c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.32
 - Version 1.2.0(latest)

**Additional context**

**Comment by aeroniemi** [comment]
That's expected, as trying to make it happen in the flight model makes some strange effects. It can be done in 3d though at some point

**Comment by OldGroof** [comment]
Yeah I wouldn’t have thought x-plane could handle something like that but it would be nice to have the visual effect
