### ISSUE TITLE
FLCH

### ISSUE THREAD

**Issue by tameraktasTU** [magknight/787aviatorsTracker#53]
**Describe the bug**
FLCH still illuminates when not engaged

**To Reproduce**
just start sim and see FLCH engaged

**Expected behavior**
Should not be illuminated when not engaged
**Screenshots**
//

**Desktop (please complete the following information):**
 - Windows 10
 - X-Plane version 11.33
 - Version 1.2.1

**Additional context**

**Comment by aeroniemi** [comment]
Duplicate of #48
