### ISSUE TITLE
Speedbrakes have a weird angle

### ISSUE THREAD

**Issue by zhouw9n** [magknight/787aviatorsTracker#531]
**Describe the bug**
Speedbrakes have a weird angle while being armed or fully extenden. Screenshot added below:

**Screenshots**
![B7879 - 2021-03-27 10 41 28](https://user-images.githubusercontent.com/76569752/112717042-479e9a00-8eea-11eb-8057-0227ba31582c.png)
![B7879 - 2021-03-27 10 41 57](https://user-images.githubusercontent.com/76569752/112717043-4a998a80-8eea-11eb-94c4-cb98c9578a97.png)
![B7879 - 2021-03-27 10 42 04](https://user-images.githubusercontent.com/76569752/112717050-52592f00-8eea-11eb-8d11-503996d99301.png)

 - OS: Windows 10
 - X-Plane version 11.41r1
 - Version [1.6.7-alpha 16

**Comment by aeroniemi** [comment]
Log? Using a new livery?

**Comment by zhouw9n** [comment]
Yes using v5 liveries

[Log.txt](https://github.com/magknight/787aviatorsTracker/files/6250985/Log.txt)

**Comment by magknight1** [comment]
There was an old angle configuration on the blender file for the spoilers. It has been addressed.
