### ISSUE TITLE
Spoilers deploy in air

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#54]
**Describe the bug**
The spoilers do not deploy far enough in air I think.
**To Reproduce**
Use the spoilers in air

**Expected behavior**
See screenshot. I didn't get a screenshot of in sim.

**Screenshots**
![ailerons](https://user-images.githubusercontent.com/39658757/57661509-1d3be000-75e3-11e9-8761-c2363139c8e3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.32
 - Version 1.2.0(latest)

**Additional context**

**Comment by aeroniemi** [comment]
Potentially set the value to 0.6
