### ISSUE TITLE
Rudder moving into wrong side.

### ISSUE THREAD

**Issue by Wujaszko** [magknight/787aviatorsTracker#541]
**Describe the bug**
Rudder is moving into wrong/opposite side.

**Screenshots**
Rudder should move into right.
![image](https://user-images.githubusercontent.com/66253402/113483064-dd659680-94a1-11eb-921d-792cab6258e8.png)
![image](https://user-images.githubusercontent.com/66253402/113483074-f1a99380-94a1-11eb-8368-7f74bd7b7b5f.png)
Rudder should move into left.
![image](https://user-images.githubusercontent.com/66253402/113483135-3b927980-94a2-11eb-9165-81fe7c7a42c6.png)
![image](https://user-images.githubusercontent.com/66253402/113483150-4c42ef80-94a2-11eb-9864-09863df99708.png)

**Desktop:**
 - OS: Windows 10
 - X-Plane version: 11.53r1
 - Version: v1,6.7-alpha17

**Comment by aeroniemi** [comment]
only an issue with v5 fuse, have shipped an update to fix it, although it needs fixing in the blender model

**Comment by magknight1** [comment]
Fixed.
