### ISSUE TITLE
Weird display information and flapping spoilers

### ISSUE THREAD

**Issue by CaptainAlex787** [magknight/787aviatorsTracker#542]
When I check my rudder the indication moves outside of the indication area.
![B7879 - 2021-04-07 18 35 45](https://user-images.githubusercontent.com/82121213/113932483-f3ea5580-97f3-11eb-949c-283286f1cc28.png)

When I set my flaps to a higher value than 5 the flaps indicator goes below the correct flap indication
![B7879 - 2021-04-07 18 37 53](https://user-images.githubusercontent.com/82121213/113932579-0fedf700-97f4-11eb-9df0-a9ce953251b8.png)

The spoilers moved up and down while I was taxiing. This happened when my spoilers were armed and even in the down position. The spoilers behave weird in general. They move downwards with the flaps and when they are up the angle is too steep.

**To Reproduce**
Steps to reproduce the behavior: Just check your rudder and set the flaps higher than 5 like 15 etc.

**Expected behavior**
A clear and concise description of what you expected to happen: No moving spoilers while taxiing, correct indications

**Screenshots**
![B7879 - 2021-04-06 22 40 22](https://user-images.githubusercontent.com/82121213/113933240-a02c3c00-97f4-11eb-8d70-3eed4bebb1e1.png)
![B7879 - 2021-04-06 22 40 37](https://user-images.githubusercontent.com/82121213/113933252-a3272c80-97f4-11eb-9243-53d20aa274a1.png)
![B7879 - 2021-04-07 18 35 45](https://user-images.githubusercontent.com/82121213/113933261-a5898680-97f4-11eb-8b76-d58e1ce6b138.png)
![B7879 - 2021-04-07 18 37 53](https://user-images.githubusercontent.com/82121213/113933267-a7534a00-97f4-11eb-8061-3b084a43f51a.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - X-Plane version 11.52
 - Version 1.6.7-alpha17

**Comment by aeroniemi** [comment]
partly a duplicate of #531, can't replicate the indicator issue though
