### ISSUE TITLE
Cockpit instrument light dimming

### ISSUE THREAD

**Issue by aeroniemi** [magknight/787aviatorsTracker#549]
Needs the instrument light switch on the lower overhead (the test/dim/brt one) to be mapped to aero787/cockpit/overhead/indLts (0 - test, 1 - dim, 2 - brt) with appropriate manip - might need making a bit bigger too?

**Comment by magknight1** [comment]
Ready for testing.

**Comment by aeroniemi** [comment]
finished and shipped
