### ISSUE TITLE
Spoilers deploy in air and flaps extended

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#55]
**Describe the bug**
The spoilers don't really extend much when you deploy the min the air with flaps extended.

**To Reproduce**
Extend flaps and extend spoilers

**Expected behavior**
They should extend the normal amount as if the flaps aren't extended.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.32
 - Version 1.2.0(latest)

**Additional context**

**Comment by aeroniemi** [comment]
I think the book says that spoilers can't be deployed with flaps extended, but i'll have a more detailled look

**Comment by OldGroof** [comment]
By the looks of things I think that should be the case.

**Comment by aeroniemi** [comment]
It says that they can be deployed with flaps, but it is not recomended due to a rather large loss of lift. I think this was fixed as a result of changing the spoilers detents
