### ISSUE TITLE
Rear Cargo Door

### ISSUE THREAD

**Issue by Viper787** [magknight/787aviatorsTracker#569]
**Describe the bug**
Clicking on the space defined to Open/Close rear cargo door not working.

**To Reproduce**
Click on area to open door, and it will not work

**Expected behavior**
Door should Open/Close

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 10.12.6
 - X-Plane version 11.50r3
 - Version 1.68beta2

**Additional context**

**Comment by aeroniemi** [comment]
Are you sure you are using a new (v5) fuselage livery?

**Comment by Viper787** [comment]
> Are you sure you are using a new (v5) fuselage livery?

Just checked, yes that was the problem. Thx
