### ISSUE TITLE
Controls twitching when AP is on

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#58]
**Describe the bug**
From what it looks like the AP is trying to make small adjustments. But it results in this glitchy effect. Maybe make the controls respond slightly slower might mitigate this?

**To Reproduce**
Just watch the flying surfaces during a flight

**Expected behavior**
Smoother movements/less corrections

**Screenshots**
https://gyazo.com/ec81ab0b3e92557c2178cd7b93e13bb4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.32
 - Version 1.2.0(latest)

**Additional context**

**Comment by aeroniemi** [comment]
Related to #46 - the controls already move really slowly, i think the autopilot just needs more tuning
Having said that, during turbulence I did see the flaperons moving rapidly on my last real flight, so it's not impossible, just not ideal

**Comment by OldGroof** [comment]
Maybe it’s not slowing down the controls. Maybe it’s just autopilot need tuning. I also saw the plane freaking out during turbulence.
