### ISSUE TITLE
Primary Flight Display is the wrong colors

### ISSUE THREAD

**Issue by magknight1** [magknight/787aviatorsTracker#585]
The colors of artificial horizon are incorrect in tone, making it difficult to read. The white lines also should be wider.

The colors depicted in several pictures of the real plane, documents of the aircraft and similar simulated aircraft show a closer color to the real plane.

![pfd](https://user-images.githubusercontent.com/49568118/115498526-1fcdf800-a244-11eb-9ff5-6197c091ca6a.jpg)

**Comment by aeroniemi** [comment]
they've been changed in 1.7.20-beta6
