### ISSUE TITLE
Hydraulic pressure

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#59]
**Describe the bug**
Not sure if bug but worth reporting:
The left hydraulic's pressure constantly changes and is significantly lower than the other systems

**To Reproduce**
Monitor the hydraulics whilst flying.

**Expected behavior**
Surely the value should twitch nor should it be lower than the other systems

**Screenshots**
https://gyazo.com/234b1cde77f0014ab1df0421c61cdc1b

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.32
 - Version 1.2.0(latest)

**Additional context**

**Comment by mob9221** [comment]
This is expected behaviour and the values of the reservoir are per sources we have. Too much sudden stress on a system causes an immediate dip in pressure.

**Comment by aeroniemi** [comment]
It's not expected behaviour, it is caused by still running my original hydraulics code at the same time as your new code. I've fixed it for next release
