### ISSUE TITLE
APU Start Switch Operation v1.7.7

### ISSUE THREAD

**Issue by Viper787** [magknight/787aviatorsTracker#593]
The APU Start switch is not automatically springing back to the ON position after start sequence is initiated.

**Comment by aeroniemi** [comment]
It did it fine for me in testing just now - the APU uses default tech, so i'd be surprised if it had decided to stop working
it does take a while after start-up though, probably 2-3 mins after turning it to start

**Comment by Viper787** [comment]
> It did it fine for me in testing just now - the APU uses default tech, so i'd be surprised if it had decided to stop working
> it does take a while after start-up though, probably 2-3 mins after turning it to start

oh okay, a bit closer to reality - thx! I'll check again today.
