### ISSUE TITLE
Overhead Button Lights not working

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#596]
**Describe the bug**
At Night the button lights on the overhead panel are not iluminated

**To Reproduce**
Set the SIM to nightime

**Expected behavior**
The light on the buttons should work just like they did in v1.7.7

**Screenshots**
![B7879 - 2021-06-18 20 55 58](https://user-images.githubusercontent.com/56799893/122606331-12cd5980-d079-11eb-9fc5-d00afc927053.png)
every light i could find cranked up to the max!

**Desktop (please complete the following information):**
 - Windows 10
 - X-Plane version X-Plane 11.53r1
 - Version 1.7.8

**Comment by aeroniemi** [comment]
Is this still an issue on the live channel?

**Comment by aeroniemi** [comment]
seems to have resolved itself
