### ISSUE TITLE
Terrain Radar not working anymore

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#597]
**Describe the bug**
Terrain Radar isnt working anymore

**To Reproduce**
Try to use Terrain Radar in v1.7.8

**Expected behavior**
Terrain Radar should work like it did before v1.7.8 its still working in 1.7.7

**Video**
https://www.youtube.com/watch?v=gQ7jUT6tcQ0

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - X-Plane version 11.53r1
 - Version 1.7.8

**Comment by aeroniemi** [comment]
it has been updated to use more realistic functionality, which requires the latest version of the terrainradar plugin.
