### ISSUE TITLE
Weird Engine Effect on Idle

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#60]
**Describe the bug**
When the plane descends with idle throttle you get this weird effect appear ahead of the engines

**To Reproduce**
Climb to FL380, then descend back down to FL100 using FLCH.

**Expected behavior**
I would imagine this effect should exist.

**Screenshots**
![B7879_3](https://user-images.githubusercontent.com/39658757/57780442-2e3e3b80-7720-11e9-81df-7df05f938882.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.32
 - Version 1.2.0(latest)

**Additional context**
I checked, engine smoke is off and using experimental flight model

**Comment by OldGroof** [comment]
Also as a part two, the engine effects (heat and contrails) seam to go really large when the engines are idling. Both on ground and in air.

**Comment by aeroniemi** [comment]
They're just the x-plane default effects at the moment, so not much we can do there

**Comment by KBNOtaku** [comment]
Isnt there a way to edit this effect for the Aircraft in Plane Maker?
Other planes are not showing this issue?
