### ISSUE TITLE
RESET/EXIT Buttons on LOGON/STATUS

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#601]
**Describe the bug**
Firstly, The 'RESET' button on the LOGON/STATUS page of comm doesn't actually reset the input, it closes the page.
Secondly, The 'EXIT' button, when pressed, closes the page but then navigates to the Flight Information tab. This produces a strange state where the navigation bar at the top says you're in ATC but the page is actually the Flight Information page.

**To Reproduce**
Navigate to the LOGON/STATUS page then click RESET and/or EXIT and it'll happen.

**Expected behaviour**
RESET should clear the input field and not close the page.
EXIT should close the page and open the ATC page. Or if the current behaviour is expected the navigation bar should highlight the Flight Information button.

**Screenshots**
After pressing 'EXIT':
![B7879 - 2021-07-08 14 29 17](https://user-images.githubusercontent.com/39658757/124930357-2aa15900-dff9-11eb-945c-e079824a8a54.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.5X - idk which one
 - Version 1.7.8

**Comment by aeroniemi** [comment]
resolved in 1.7.9
