### ISSUE TITLE
EFB calculators won't reset with new flight leg

### ISSUE THREAD

**Issue by Simleybob** [magknight/787aviatorsTracker#602]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
Fly a route with using the EFB calculators, like normal. Close the flight, and open a new one, go back to the performance calculators and you will see everything from your previous flight still there, the airport, wind, QNH etc. 

**Expected behaviour**
When you press 'CLOSE FLIGHT' on the main page in the EFB, the performance calculators (Take-off and Landing) reset all the info boxes to blank or empty, as it would be on the first flight in that sim session.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.55r2
 - Version 1.7.8

**Comment by aeroniemi** [comment]
this has been done now
