### ISSUE TITLE
Floating visible black clickspot when opening Overhead door

### ISSUE THREAD

**Issue by Simleybob** [magknight/787aviatorsTracker#603]
**Describe and how to Reproduce the bug**
When you open the emergency overhead door and go through it, and turn around you see this 
![image](https://user-images.githubusercontent.com/81443205/125485694-6026a330-88ca-4a20-8f86-8da603e3cc3e.png)

**Expected behaviour**
It shouldn't be there

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.55r2
 - Version 1.7.9

**Comment by magknight1** [comment]
All the hidden manipulators are mapped to the panel.png bottom left corner that has a small translucent part. It seems that the panel.png was changed to a solid image. It can be updated to this one:
![panel](https://user-images.githubusercontent.com/49568118/133947102-a1c7c8ef-2e2e-443f-be87-48d625527aee.png)

**Comment by aeroniemi** [comment]
fully fixed in b11
