### ISSUE TITLE
AviTab tablet holder/stand on the right side

### ISSUE THREAD

**Issue by Simleybob** [magknight/787aviatorsTracker#611]
**Describe the bug**
the stand is there without the tablet

**Expected behaviour**
Either remove the stand/holder or add the tablet to the holder.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.55r2
 - Version 1.7.14

**Comment by Jonathan06130** [comment]
BONJOUR MA TABLETTE NE S ALLUME PAS 
![B7879 - 2021-08-27 08 32 33](https://user-images.githubusercontent.com/89628467/131082833-871b3af8-bd8c-420e-8463-ffc736b0af83.png)
](url)

**Comment by Simleybob** [comment]
Update the plane again

**Comment by Jonathan06130** [comment]
bonjour j ai reinstaller l avion vec dernere mise  jour mais la tablette ne fonctionne toujours pas

**Comment by Simleybob** [comment]
Please chat in the discord server, not here

**Comment by aeroniemi** [comment]
is this still a thing in the latest cygnus version?

**Comment by Simleybob** [comment]
Yes

**Comment by aeroniemi** [comment]
apparently it's intentional, although i think it'd be better without the frame on the right as it doesn't do anything useful

**Comment by Simleybob** [comment]
Why would it be intentional, it doesn’t do anything?

**Comment by magknight1** [comment]
The excess of right stand wasn't the issue but the lack of right avitab. It's been addressed.

![X-System 7_3_2022 13_02_52](https://user-images.githubusercontent.com/49568118/157072370-5a441b27-4756-4ef6-880e-d66d7e279608.png)

**Comment by Simleybob** [comment]
Are you sure that won’t affect performance?

**Comment by magknight1** [comment]
We only plan to have one on at a time.

**Comment by Simleybob** [comment]
Great! I think that’s what I suggested to aero a while back, thanks.
