### ISSUE TITLE
'Dead pixels' on ipad only.

### ISSUE THREAD

**Issue by Simleybob** [magknight/787aviatorsTracker#612]
**Describe the bug**
https://cdn.discordapp.com/attachments/633261384511127552/876058373127274496/X-System_2021-08-14_11-45-10.mp4
The white specs/dots you see.

**To Reproduce**
Switch on the aircraft and iPad, move around and you will see them on the screen and ipad model

**Expected behaviour**
for them to not be there, it is quite annoying and obvious.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.55r2
 - Version 1.7.14

**Comment by magknight1** [comment]
That's the dome lights reflected on the tablet. We have yet to add a normal map to the tablet so the reflections are not so rude. If you turn off the dome light, you will see the dots dissapear.

**Comment by aeroniemi** [comment]
fixed in b8
