### ISSUE TITLE
When you press c in the cockpit, no buttons/switches are there

### ISSUE THREAD

**Issue by Simleybob** [magknight/787aviatorsTracker#613]
**Describe the bug**
![image](https://user-images.githubusercontent.com/81443205/129485532-513414a1-ff22-4f13-8b82-efbf52699248.png)

**To Reproduce**
Steps to reproduce the behaviour:
Go to shift+9 view (cockpit view) and press c to go to stationary view or something. And you will see the stuff referred to in the picture above.

**Expected behaviour**
For it to not be like that and for it to be normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/81443205/129485578-42ec74ae-ddf7-4695-99a2-db9091edf9a5.png)
![image](https://user-images.githubusercontent.com/81443205/129485588-ba2782d7-b5e5-4151-9ec0-3247501dbdcd.png)
![image](https://user-images.githubusercontent.com/81443205/129485593-cb76ff52-dc38-4f84-8872-f8b48e66438b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.55r2
 - Version 1.7.14

**Comment by aeroniemi** [comment]
That's expected - free cam is defined as an external view by x-plane, so for performance reasons interior stuff isn't shown.

**Comment by Simleybob** [comment]
Oh ok
