### ISSUE TITLE
wipers

### ISSUE THREAD

**Issue by r2splashy** [magknight/787aviatorsTracker#616]
**Describe the bug**
when i turn the wipers on it doesnt show in the cockpit but when i switch to the outside view i see them moving

**To Reproduce**
turning he wipers on
**Expected behaviour**
to see the window wipers animation inside the flight deck

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.6.10]

**Additional context**

**Comment by aeroniemi** [comment]
fixed in v1.7.16
