### ISSUE TITLE
Selecting without wanting to select

### ISSUE THREAD

**Issue by Coolebooster** [magknight/787aviatorsTracker#617]
**Describe the bug**
When clicking next to the checklist categories (doesn't matter which mouse button), and you hover over a checklist category, it selects that category. Happens also inside the checklist categories.

**To Reproduce**
Go to the checklist tab, click next to it, hover over a category.

**Screenshots**

**Desktop (please complete the following information):**

- Windows 20H2
- X-Plane version 11.55r2
- Version v1.7.17

**Additional context**

**Comment by Simleybob** [comment]
Can also confirm this, checklists aren't that stable!

**Comment by aeroniemi** [comment]
fixed in 1.7.18
