### ISSUE TITLE
Black screen in cockpit 

### ISSUE THREAD

**Issue by EcstaticAviator** [magknight/787aviatorsTracker#619]
**Describe the bug**
After a 10 hour flight, with 2 hours to go. The 3d cockpit went black. I could still see the plane in external view but it was crashing. I believe was in a stall. Sound was also still working

**To Reproduce**
Would be hard to reproduce other than flying for 10 hours. Was at cruise FL410

**Expected behaviour**
3d cockpit screen goes black and plane starts to stall

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - X-Plane version [11.55]
 - Version [1.7.5]

There hadn't been any changes in the xplane log for about 7 hours.

**Comment by aeroniemi** [comment]
I'd guess that you'd run out of fuel or something similar - doesn't sound like a 787-related issue

**Comment by EcstaticAviator** [comment]
Total black screen in cockpit due to low fuel. I highly doubt that….

**Comment by aeroniemi** [comment]
If you've not got the apu on and have a dual engine failure, you will be
down to minimum power which does mean most screens will be off

**Comment by aeroniemi** [comment]
closed as stale - impossible to reproduce, so practically impossible for us to fix
