### ISSUE TITLE
V-Speeds not showing in PFD

### ISSUE THREAD

**Issue by DLH9KA** [magknight/787aviatorsTracker#62]
Latest Version updated at May 18th 2019.

V-Speeds which have been calculated in the EFB are not showing up in PFD.
Instead it says, No V-Speeds.

![image](https://user-images.githubusercontent.com/50771419/57969831-6fca2300-797a-11e9-9aec-00d923f2d509.png)

**Comment by aeroniemi** [comment]
Potentially linked to #56
