### ISSUE TITLE
Black screen on the CDU

### ISSUE THREAD

**Issue by azou06** [magknight/787aviatorsTracker#622]
**Describe the bug**
After i updated the plane to V1.7.18 i have black screen on the CDU 
when i hit any button it's the same thing excepted for Thust LIM.

**To Reproduce**
Click on MCD button

**Expected behaviour**
should see the page linked to the button. If i hit for example LEGS, i should see the differents legs of my route. But the screen is completely black.

**Screenshots**
![image](https://user-images.githubusercontent.com/92452233/137159730-e520b56c-b929-4a3e-99dc-14752326d87c.png)
https://cdn.discordapp.com/attachments/633261384511127552/897827717830037544/2021-10-13_8-41-40.mp4 

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - X-Plane version 11.50

**Additional context**
Nothing to add

**Comment by azou06** [comment]
Hello guys i figure out what's causing the problem. It"s due to this plugins Xsaitekpanels.

**Comment by aeroniemi** [comment]
It m
