### ISSUE TITLE
When I want to use cinematic mode via xcamera it doesnt work

### ISSUE THREAD

**Issue by sclorious** [magknight/787aviatorsTracker#626]
The bug only occurs when using the XCamera GUI moving settings. When I go to Circle camera view (3rd person default xplane) it works. I cant save the camera in xcamera using that because I didn't move the camera via xcamera. This wasn't an issue in the previous version. I don't believe it is an livery issue
![Screenshot_16](https://user-images.githubusercontent.com/93557907/139755197-a1231bb5-1f24-4124-8a49-610649145284.png)
![Screenshot_17](https://user-images.githubusercontent.com/93557907/139755223-54fba24b-6b93-4b09-8cd0-877380f57c8a.png)

**Comment by aeroniemi** [comment]
You need to set the camera to external in xcamera, which forces the
external model to be shown at all times - having it off when it's not 'in
view' helps improve performance, and when using xcamera we don't actually
know where your camera is.
