### ISSUE TITLE
Wipers don't work

### ISSUE THREAD

**Issue by aeroniemi** [magknight/787aviatorsTracker#629]
not sure what doesn't work about them, but people seem to think they're broken on latest cygnus

**Comment by KBNOtaku** [comment]
Can confirm wipers don't work in 1.7.18-alpha6
The sound is played but no movement.

**Comment by Simleybob** [comment]
Same here, last time I tested

**Comment by aeroniemi** [comment]
i imagine the issue is that the art isn't all of the same version

**Comment by aeroniemi** [comment]
actually, if there is sound the issue probably is the cockpit switch datarefs/commands activating the default stuff, as the custom ones don't have sound

**Comment by aeroniemi** [comment]
fixed in a9
