### ISSUE TITLE
If starting airborne, hydraulics need to pressurise instantly

### ISSUE THREAD

**Issue by aeroniemi** [magknight/787aviatorsTracker#63]
This needs to happen if you select  to start on a 3nm or 10nm approach, or any of the airborne special starts

**Comment by mob9221** [comment]
I would need to know the dataref for such operation. I could do it when the system initializes on the first cycle but then we will have the same problem as the gear where the plane drops on starting on ground and the onGround dataref is 0 causing the entire system to initialize. We could do the wait 4 seconds then try to make sure the plane is on the ground.
