### ISSUE TITLE
Standby PFD only showing earth

### ISSUE THREAD

**Issue by Thomrade** [magknight/787aviatorsTracker#633]
Standy PFD only show the earth (brown part) on 1.17.18 alpha 6

**Comment by KBNOtaku** [comment]
Can confirm that, it shows full brown or full blue no Horizon
![X-Plane Screenshot 2021 11 23 - 16 22 18 54](https://user-images.githubusercontent.com/56799893/143080431-5487790f-8a49-4a7d-a926-eda0fb49620b.png)
![X-Plane Screenshot 2021 11 23 - 16 26 36 07](https://user-images.githubusercontent.com/56799893/143080439-c4147f28-ec99-4bf3-95d9-6b50e2a33fc2.png)
!

**Comment by aeroniemi** [comment]
it's been happening ever since we started using rendertargets for other stuff - check whether they are correctly reset, whether the render target it uses actually exists and isn't duplicated, and whether it is actually drawn

**Comment by aeroniemi** [comment]
has been fixed - seems to be related to the antialiasing stuff (which has now been removed)
