### ISSUE TITLE
CDU Input lag

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#638]
**Is your feature request related to a problem? Please describe.**
FMC Input lag is too strong, not constant, and sometimes I must click twice to get respond.

**Describe the solution you'd like**
Pleas tweak the FMC Input lag, and or pleas add the option to disable the input lag.

**Describe alternatives you've considered**
Remove the Input lag, or add the option to disable it.

**Additional context**
 - OS:  Windows 10 ]
 - X-Plane version [ 11.55r2 ]
 - Version [ 1.7.18-alpha6 ]

**Comment by aeroniemi** [comment]
there isn't any intentional input lag - it seems to be fine when i use it!

**Comment by KBNOtaku** [comment]
Here is a short Video so you can see what I am talking about:
https://drive.google.com/file/d/1GtWCgoM9lyHHcqa02ZR8_st21kDvrgCt/view?usp=sharing

**Comment by aeroniemi** [comment]
https://user-images.githubusercontent.com/13006900/143235394-fab546c8-c056-4e49-8f1b-773feb2ba913.mp4

that just isn't a thing when I try it in my release version!

**Comment by KBNOtaku** [comment]
As you can see in my Video switching between the pages is also no Problem on my side!
The delay is clearly noticeable when putting something into the FMC, like the DEP and ARR Airport, choosing SID an STAR, changing things on the LEG page or in RADNAV. Also going through the VNAV pages has a big delay?
When I first want to go into RTE page I also need to press it twice, this also can be seen in the Video!
This inst the case in the last stable Version!?

**Comment by KBNOtaku** [comment]
In the pop out FMC the delay do not happen!
When using it side by side you see the delay very clearly.

https://user-images.githubusercontent.com/56799893/143269016-69f7a0d0-2988-4330-bebc-1ee20eb150e6.mp4

**Comment by aeroniemi** [comment]
it wouldn't surprise me if that happened when you use the pop-up as input, as the input there bypasses our commands, so the screen doesn't know it needs to redraw (it redraws only when there is input, or once every second, whichever is sooner)

**Comment by KBNOtaku** [comment]
Yeah but it has the same behavior as if I would use the CDU direct, as can be seen in the first Video.
So is it also bypassing when I use the CDU in the Aircraft?
This does not happen in the last stable version?

**Comment by aeroniemi** [comment]
i can't actually reproduce this, but i've added a force redraw to all button presses now, so theoretically that should fix it

**Comment by KBNOtaku** [comment]
The Issue seams solved within ALPHA-10.
The only thing I am wondering is, when first time using the CDU after loading the Aircraft, I need to press 2 times on an page to get an respond?
