### ISSUE TITLE
PLAN mode not working 1.7.18-alpha6 

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#639]
**Describe the bug**
PLAN mode is not working.
I can not change and use PLAN mode anymore. I can not change into PLAN mode via the knob or the ND Touchscreen.
When I change into PLAN mode vie key, STEP is not working?!

**To Reproduce**
Use PLAN mode and check the route.

**Expected behaviour**
PLAN mode be able to use, it worked fine in the last stable version.

**Desktop (please complete the following information):**
 - OS:  Windows 10 ]
 - X-Plane version [ 11.55r2 ]
 - Version [ 1.7.18-alpha6 ]

**Comment by aeroniemi** [comment]
it's not planned to be added in the near future
