### ISSUE TITLE
No Terrain Radar

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#640]
**Describe the bug**
Terrain Radar does not work
Also Weather is shown on both ND´s when its only set on the Pilot side.

**To Reproduce**
Use Terrain Radar

**Expected behaviour**
When terrain radar is on it should display the Terrain on the ND

**Screenshots**
![X-Plane Screenshot 2021 11 23 - 16 58 48 33](https://user-images.githubusercontent.com/56799893/143086074-d6cf9d60-c107-449f-8b22-62427fd5cd97.png)
![X-Plane Screenshot 2021 11 23 - 16 58 40 92](https://user-images.githubusercontent.com/56799893/143082618-c47cebca-1034-4a31-bf24-c91b9ab93159.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 ]
 - X-Plane version [ 11.55r2 ]
 - Version [ 1.7.18-alpha6 ]

**Comment by aeroniemi** [comment]
this isn't something we control - terrain radar is an external product, so it won't be added until after this stuff goes stable

**Comment by aeroniemi** [comment]
It's now available in both the -8 and -9 using the development version of terrain radar - will become stable soon.
