### ISSUE TITLE
COMM page not implemented

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#641]
**Describe the bug**
COMM Page doesn't work anymore, so some features are missing and PA control isn't possible anymore?

**To Reproduce**
Use COMM

**Expected behaviour**
It should work like in last stable version

**Screenshots**
![X-Plane Screenshot 2021 11 23 - 15 52 13 02](https://user-images.githubusercontent.com/56799893/143083164-5dae5020-822e-46d5-885c-cf7ec1afa6ee.png)
![X-Plane Screenshot 2021 11 23 - 16 38 07 84](https://user-images.githubusercontent.com/56799893/143083169-ad257c1b-3ac6-43e0-a03e-2afccd0c47a3.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 ]
 - X-Plane version [ 11.55r2 ]
 - Version [ 1.7.18-alpha6 ]

**Comment by aeroniemi** [comment]
very much does need adding, but it's kinda a problem because it needs the ui replacing really

**Comment by aeroniemi** [comment]
all of the non-cpdlc comm stuff should now work, cpdlc isn't going to be fixed for this version as it needs entirely re-writing using better tech
