### ISSUE TITLE
EFIS Door closing UI

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#642]
**Describe the bug**
Doors only close when using beacon light.

**To Reproduce**
Close the doors manual on the doors page

**Expected behaviour**
able to close the doors manual like in the last stable version

**Desktop (please complete the following information):**
 - OS:  Windows 10 ]
 - X-Plane version [ 11.55r2 ]
 - Version [ 1.7.18-alpha6 ]

**Comment by aeroniemi** [comment]
door UI needs replacing now that right click has been removed (design) - probably the solution is to make it a left-click only toggle
should probably replace the door control thing
