### ISSUE TITLE
THR LIM page missing

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#645]
**Is your feature request related to a problem? Please describe.**
There is no Thrust Limit option anymore

**Describe the solution you'd like**
Implement a realistic thrust limit.

**Describe alternatives you've considered**
Bring back the Thrust Limit option in the FMC.

**Additional context**
 - OS:  Windows 10 ]
 - X-Plane version [ 11.55r2 ]
 - Version [ 1.7.18-alpha6 ]

**Comment by aeroniemi** [comment]
this needs me to finish the -8 data stuff, which will probably happen before christmas
so i guess the page can be finished being added then- it exists, just doesn't work
