### ISSUE TITLE
Traffic missing on NDs

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#646]
**Describe the bug**
When using Traffic Global no traffic is displayed in the ND

**To Reproduce**
Display traffic in the ND

**Expected behaviour**
The Aircraft should be able to display traffic in the ND like it did in the last stable version.

**Screenshots**
![X-Plane Screenshot 2021 11 23 - 19 05 10 63](https://user-images.githubusercontent.com/56799893/143086566-6553f179-6f98-4271-9bcb-aff6d6f40705.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 ]
 - X-Plane version [ 11.55r2 ]
 - Version [ 1.7.18-alpha6 ]

**Comment by aeroniemi** [comment]
are you sure it's not working when airborne? as per reality, it won't show anything on the ground!

**Comment by KBNOtaku** [comment]
On my Test flight from RJBB to RJTT I also could not see any traffic on the ND ,and there was a lot of traffic?
The Screenshot was just for testing because in the stable version I could see traffic even when on ground.

**Comment by KBNOtaku** [comment]
Did a new Test flight today and still no traffic in the ND?
Even with an Aircraft directly in front of me?
![X-Plane Screenshot 2021 11 24 - 16 10 23 37](https://user-images.githubusercontent.com/56799893/143266626-856eace9-0345-4b1d-a3ed-aa1716728d5f.png)
![X-Plane Screenshot 2021 11 24 - 16 12 42 28](https://user-images.githubusercontent.com/56799893/143266521-38f37b80-a540-4436-b997-490a505c28b1.png)
?

**Comment by aeroniemi** [comment]
![image](https://user-images.githubusercontent.com/13006900/143324369-80ea2322-48d8-45cd-8f36-be2bad755e20.png)
it's very definitely working, both with vatsim and default AI!

**Comment by KBNOtaku** [comment]
Will test it further more!
Maybe Alpha isn´t supporting TrafficGlobal anymore?
