### ISSUE TITLE
Pop-up CDU has default graphics

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#649]
**Describe the bug**
Unlikely in the last stable version the pop out FMC now looks like the default one.

**To Reproduce**
Use the pop out FMC

**Expected behaviour**
It should look like the 787 one, same as in the last stable version

**Screenshots**
![X-Plane Screenshot 2021 11 24 - 15 53 07 70](https://user-images.githubusercontent.com/56799893/143267586-9fd3b41b-5b33-41e7-882a-66833bc10e61.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 ]
 - X-Plane version [ 11.55r2 ]
 - Version [ 1.7.18-alpha6 ]

**Comment by aeroniemi** [comment]
it's intentional, to allow me to check the difference between the two - the old style pop-out CDU is gonna be replaced by the pop-out MFD screens, which will probably be controlled using a new command/UI.

**Comment by aeroniemi** [comment]
CDU popups replaced by screen popups in 1.7.20-beta6
