### ISSUE TITLE
Hide past waypoints

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#650]
**Describe the bug**
Way points do not get removed after passing them

**To Reproduce**
Fly a programmed route with LNAV

**Expected behaviour**
After reaching/passing a way point when using AP/LNAV etc..
The way point should no longer be visible on the ND or Minimap.

**Screenshots**
![X-Plane Screenshot 2021 11 24 - 16 07 41 32](https://user-images.githubusercontent.com/56799893/143270910-581ff986-d31b-46f2-acc0-0716330dc830.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 ]
 - X-Plane version [ 11.55r2 ]
 - Version [ 1.7.18-alpha6 ]

**Comment by aeroniemi** [comment]
need to work out what the remove conditions should be - a lot of the waypoints in the past should be kept if they are part of a procedure etc

**Comment by aeroniemi** [comment]
i've set it to remove everything before the last point, so we'll see how that goes
