### ISSUE TITLE
ND Distance Rings

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#655]
**Describe the bug**
Missing distance rings in the ND

**To Reproduce**
Doesn't matter what mode is selected. no distance rings are shown?

**Expected behaviour**
I don't know exactly in which mode but in WXR and or TFC mode shouldn't there be distance rings displayed in the ND?

**Desktop (please complete the following information):**
 - OS:  Windows 10 ]
 - X-Plane version [ 11.55r2 ]
 - Version [ 1.7.18-alpha10 ]

**referents picture**
(https://c7.alamy.com/compde/2ad5692/die-instrumente-im-cockpit-einer-boeing-787-dreamliner-auf-der-paris-air-show-eine-messe-fur-unternehmen-der-luft-und-raumfahrt-findet-jedes-jahr-in-le-2ad5692.jpg)

**Comment by aeroniemi** [comment]
i seem to remember the range rings being more associated with the ND mode than the layers - check the conditions for it

**Comment by aeroniemi** [comment]
resolved in b1
