### ISSUE TITLE
TFC Button not working

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#656]
**Describe the bug**
TFC Button does not work

**To Reproduce**
Try activating TFC with the button

**Expected behaviour**
With the TFC Button it should be possible to activate or deactivate TFC mode.
Just like it worked within the ND menu.

**Video**
https://user-images.githubusercontent.com/56799893/143683142-90d56408-8469-457e-a35b-b5aaaffaff38.mp4

**Desktop (please complete the following information):**
 - OS:  Windows 10 ]
 - X-Plane version [ 11.55r2 ]
 - Version [ 1.7.18-alpha10 ]
 
 **Additional Info**
 WXR and TERR Buttons do work fine.

**Comment by aeroniemi** [comment]
it's a similar thing to the wxr/terr buttons - need to find a way to make the button toggle every single display rather than just the minimap
