### ISSUE TITLE
Route waypoints still off line

### ISSUE THREAD

**Issue by Simleybob** [magknight/787aviatorsTracker#660]
![image](https://user-images.githubusercontent.com/81443205/146454077-e83fecde-6a7d-45b0-9045-ffd153d1d054.png)
Latest cygnus alpha 10

**Comment by aeroniemi** [comment]
it looks like it's working fine to me in that image?

**Comment by Simleybob** [comment]
That is quite off considering the route line is underneath the middle line

**Comment by aeroniemi** [comment]
I don't think it's drawing the line at all, rather than it just being under the ranging line

**Comment by Simleybob** [comment]
![image](https://user-images.githubusercontent.com/81443205/147659853-c2ea025b-67cf-440a-8aab-712c4dba20c3.png)
it's much worse here

**Comment by Simleybob** [comment]
![image](https://user-images.githubusercontent.com/81443205/147660661-0d4694ac-6814-4978-aa8d-e7ba611eac16.png)
On a route from KDFW to KDEN
https://www.simbrief.com/ofp/flightplans/KDFWKDEN_PDF_1640773321.pdf
you can't release into stable like this, it needs to either be fixed, or not released at all and stay in the alpha branch.

**Comment by aeroniemi** [comment]
it only seems to happen on high wind, but i think it's fixed now
