### ISSUE TITLE
Ventilation Button Cover 

### ISSUE THREAD

**Issue by Viper787** [magknight/787aviatorsTracker#664]
Current release - 1.7.18 
Button Cover graphics issue - cover is floating on an upper layer and blocking the button (transparency?)
![Screen Shot 2021-12-24 at 2 17 11 PM](https://user-images.githubusercontent.com/56449761/147390990-9a4d9f5a-c8dd-4993-84d4-0d135bdc5e3b.png)

**Comment by aeroniemi** [comment]
it's the same thing as #644, caused by the manips being erroneously mapped to the panel texture
