### ISSUE TITLE
Font clipping box on PFD

### ISSUE THREAD

**Issue by ZaccJacc** [magknight/787aviatorsTracker#665]
The font on the alt sel box on the PFD is a little too big for the big numbers (e.g. FL XX0, where X is the problematic numbers) so the number gets pressed against the side of the box in a bit of a weird way.

You can see with the number 3 below:
![image_2021-12-26_165638](https://user-images.githubusercontent.com/58274381/147415054-1d5c3324-b720-4176-b7dc-90969fd973c9.png)

thanks :)

**Comment by aeroniemi** [comment]
ig the solution is to move the 38 like 2px to the right - it's still in the box, but just near the edge

**Comment by aeroniemi** [comment]
it's been moved right by 1px in a16
