### ISSUE TITLE
Connecting GPU does things it shouldn't

### ISSUE THREAD

**Issue by ZaccJacc** [magknight/787aviatorsTracker#669]
When you're connecting the GPU, as soon as you connect a second, (regardless of location, and with the buses off for them on the overhead) the integrity lights turn on surrounding all the panels, they go as soon as you disconnect the second GPU. Fairly sure the lights shouldn't come on until you turn on the GPU switches on the overhead?

**Comment by aeroniemi** [comment]
there's a list of things the gpu should power before you turn it on on the overhead, which is basically everything that normally runs on battery plus the next lighting state, so i think it's probably working properly
