### ISSUE TITLE
CLR button causes a crash to desktop

### ISSUE THREAD

**Issue by vitormaroso** [magknight/787aviatorsTracker#673]
Clicking the clear button causes a CTD in the cygnus version of the plane, both with the plane turned on or in cold and dark

**To Reproduce**
Click the CLR button on the CDU

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - X-Plane version 11.55
 - Version 1.7.19-alpha16

**Comment by aeroniemi** [comment]
Please fill out the bug report form - it's not entirely clear what the issue is, and more specifically how to reproduce it.

**Comment by aeroniemi** [comment]
I've tried to reproduce this but I'm unable to do so - i've just released a update that does fix the CDU screen going black for ~1 second when you click CLR though
