### ISSUE TITLE
EFB perf calc error is not functional (no landing weight error anymore)

### ISSUE THREAD

**Issue by Simleybob** [magknight/787aviatorsTracker#674]
EFB performance calculators can still calculate (with no error) when landing weight = 0kg. 

This arose on my flight yesterday in alpha 16, wondering why the speeds were like 160kt! (https://youtu.be/OZxBQ8zWntc?t=7794)

You need to add the error back in.

Thanks.

**Comment by aeroniemi** [comment]
There actually hasn't ever been a error message for this, but i'll add one. All of the errors that exist are working properly though!

**Comment by Simleybob** [comment]
Oh lol
