### ISSUE TITLE
Java helper fails to set when path > 1024 char

### ISSUE THREAD

**Issue by aeroniemi** [magknight/787aviatorsTracker#68]
**Describe the bug**
Java helper fails to set to path when path > 1024 char
Gives error (WARNING: The data being saved is truncated to 1024 characters.)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version: 11.34
 - Version: 1.3.0b1

**Comment by aeroniemi** [comment]
Caused by setx being limited to 1024 char

**Comment by mob9221** [comment]
Has been fixed in the latest commit
