### ISSUE TITLE
Static crackling sound when Idle Throttle when I use Rolls Royce Engine

### ISSUE THREAD

**Issue by Fakhri787** [magknight/787aviatorsTracker#680]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - X-Plane version [e.g. 11.55]
 - Version [e.g. 1.6.10]

**Additional context**

**Comment by Fakhri787** [comment]
- [ ]

**Comment by aeroniemi** [comment]
Please fill out the bug report form fully - it is not clear what the issue is.
