### ISSUE TITLE
Character limit 

### ISSUE THREAD

**Issue by Simleybob** [magknight/787aviatorsTracker#683]
![image](https://user-images.githubusercontent.com/81443205/152576777-f7f019d2-8b81-47da-ba5e-d4d8c7ad128d.png)
Beta8

**Comment by aeroniemi** [comment]
I mean, the max permitted is 34 so it is technically working - given that
the text has to look like that I'm not sure I'd want to change that

**Comment by aeroniemi** [comment]
i've just put it back to 28 now so we can see if anything actually requires more
