### ISSUE TITLE
IRS HDG

### ISSUE THREAD

**Issue by kprema123** [magknight/787aviatorsTracker#686]
the bug is where the hdg on the autopilot isnt corresponding with the one on the screen

just flying

heading to match on the screen

![image](https://user-images.githubusercontent.com/96954042/152697990-896f0b20-1c78-42cd-a822-10bd49ed83c5.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.6.10]

**Additional context**

**Comment by KBNOtaku** [comment]
I can confirm that the Speedbugs on the ND and Minimap do not work correct with the AP HDG
![X-Plane Screenshot 2022 02 07 - 12 41 49 22_LI](https://user-images.githubusercontent.com/56799893/152782167-6dacbd61-4146-4f62-8f20-584ee226f479.jpg)
!

**Comment by aeroniemi** [comment]
was fixed in b10
