### ISSUE TITLE
Flickering descent/climb arc when parked

### ISSUE THREAD

**Issue by fafaldo** [magknight/787aviatorsTracker#694]
**Describe the bug**
After latest patch, the arc is now randomly flickering, appearing and disappearing in various distances on ND when parked on ground. It's difficult to catch on screenshot but I can record a video if that helps. The problem disappears when aircraft starts moving (even when still on ground).

**To Reproduce**
Start the flight, turn power on and align IRS to get the NDs working.

**Expected behaviour**
Arc is not present on ground.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.55
 - Version 1.7.20-beta11

**Comment by aeroniemi** [comment]
fixed for b12
