### ISSUE TITLE
Descent/climb arc appears when aircraft is not changing it's altitude

### ISSUE THREAD

**Issue by fafaldo** [magknight/787aviatorsTracker#695]
**Describe the bug**
When keeping constant flight parameters (GS, V/S, ALT) sometimes the arc just sits there, very close to the aircraft. It might be that some very small changes to the GS or V/S or ALT are present, which cause the arc to be rendered (even at correct distance), but maybe a throshold value should be added to V/S (for example) so that the arc won't show if V/S is below that? 

**Expected behaviour**
When keeping level flight, with no observable changes to flight parameters the arc should not be shown.

**Screenshots**
![Capture-3](https://user-images.githubusercontent.com/63355317/153561686-03eec607-076b-49c7-b274-90b9056e51e6.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.55
 - Version 1.7.20-beta11

**Comment by aeroniemi** [comment]
fixed in b12
