### ISSUE TITLE
Error in next waypoint time estimation

### ISSUE THREAD

**Issue by fafaldo** [magknight/787aviatorsTracker#696]
**Describe the bug**
Next waypoint time calculated is clearly wrong.

**Screenshots**
![Capture-4](https://user-images.githubusercontent.com/63355317/153562004-fc69367f-5c9b-4d87-ba78-84e75abb1205.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.55
 - Version 1.7.20-beta11

**Comment by aeroniemi** [comment]
Are you sure? that seems reasonable to me

**Comment by aeroniemi** [comment]
i've added a leading zero in b12

**Comment by fafaldo** [comment]
Oh, right, I haven't thought this might be a 07:30z. Maybe because it was different than the value shown in CDU (even minutes were different at the same point in time). But there is clearly a problem with time zone calculation. I didn't take a screenshot showing both ND and CDU at the same time, but these 2 screenshots were taken during the same flight. Even if we assume minutes are matching (although I remember that minutes were also off) there is still a 1 hour difference here :)

![Capture-5](https://user-images.githubusercontent.com/63355317/153724142-f26e90cf-9c88-49f4-b129-c6ab3b5692dc.PNG)
![Capture-6](https://user-images.githubusercontent.com/63355317/153724145-7406b9a4-1e71-41a3-a259-c313b6b7e9e4.PNG)

**Comment by aeroniemi** [comment]
it's using whatever your computer has said is utc, so if that isn't correct
there isn't much we can do about it unfortunately - it comes back to the
same issue happening with xplane and its utc detection

**Comment by fafaldo** [comment]
Hmm ok, but it's custom drawing done by you that is showing actual time on the CDU, right? CDU is showing correct UTC time when I was flying (0810Z) and gave correct estimation at ARTOR (0828Z). Why would ND time (which is probably also drawn by you (as you are able to add the leading 0 as you said) be showing 0730Z?
