### ISSUE TITLE
Projection of ND route line when range >= 320nm

### ISSUE THREAD

**Issue by fafaldo** [magknight/787aviatorsTracker#697]
**Describe the bug**
There are some bug in ND drawing at different ranges. Please see below screenshots. 
- when 160nm range (or below) is selected, it appears that 'old' ND is drawn in the background (please see how headings are duplicated)
- when 320nm range (or above) is selected, 'old' map disappears but a random line appears to be drawn on screen (to the left, please see screenshot - it's not a part of current route).

**Screenshots**
![Capture-5](https://user-images.githubusercontent.com/63355317/153562563-aca7e23a-29c4-4a0e-b337-3e3a547bf186.PNG)
![Capture-4](https://user-images.githubusercontent.com/63355317/153562571-7a9a8ce0-7eb4-4baa-b77c-451c26a9e43f.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.55
 - Version 1.7.20-beta11

**Comment by aeroniemi** [comment]
The old ND stuff showing is caused by you not having up to date art assets - delete the 787/cockpit_3d folder and get the updater to replace it. The line on 320+ should be your route line

**Comment by aeroniemi** [comment]
projection issue fixed for b12

**Comment by fafaldo** [comment]
Ok, I've done a complete fresh reinstall of beta10, then applied an update to beta11 and got this. So there is something wrong with Skuncrafts Updater I believe. I will remember to always do fresh installs in that case.
