### ISSUE TITLE
V/S not changable

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#699]
**Describe the bug**
when activating V/S I am not able to change the value

**To Reproduce**
In this case I climbed with VNAV after reaching T/D, VNAV did get disabled automatically, when I wanted to set the V/S manual I wasn´t able to change it?!

**Expected behaviour**
Be able to change the value vor V/S and FPA so I can do descend and climp!

**Video**
https://youtu.be/5yLVfrdZSr4

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [11.55r2]
 - Version [e.g. 1.7.21]

**Comment by cajunjosh** [comment]
Just out of curiosity,  my click spot on the 3D cockpit is broken as well but I can still manipulate the VS knob via the keybind "Autopilot VVI down" and "Autopilot VVI up"

Perhaps that work around will work for you until they fix the click spot?

**Comment by aeroniemi** [comment]
fixed in 1.7.22
