### ISSUE TITLE
Modeling - Flap Selection Cockpit Object Not Aligned

### ISSUE THREAD

**Issue by cajunjosh** [magknight/787aviatorsTracker#700]
**Describe the bug**
The flaps indicator does not match up with the actual flaps selection.  When selecting flaps 30 the flaps knob is all the way out of the flaps bracket.

**To Reproduce**
Load in the 787 1.7.21 or 1.7.20 Beta 12 and just keep selecting additional flaps.  The lever will phase right out of the selection bracket.

**Expected behaviour**
Flaps selector should stop at flaps 30 and each flap selection should align properly with the marker.  

**Screenshots**

**Desktop (please complete the following information):**
Windows 10
XP 11.53 or whatever version is the most current.

**Additional context**
![unknown](https://user-images.githubusercontent.com/75854551/153782502-d9883869-64fc-4f61-9951-360d61c9bf2a.png)

**Comment by aeroniemi** [comment]
fixed in 1.7.22 - showing -8 settings
