### ISSUE TITLE
Cabin doors unable for MANUAL

### ISSUE THREAD

**Issue by Delta-Lima** [magknight/787aviatorsTracker#701]
Since version 1.7.22 I'm unable to switch the doors from "Automatic" to "Manual" (or vice versa when they are by "fortune" on M). I used version 1.7.18 before where it was working (left mouse click A->M->open; right mouse click opposite way).

**Comment by aeroniemi** [comment]
The controls were changed during the 1.7.20 beta run - it is now left click only, with the state going armed-disarmed-open-closed - to arm the doors turn on the beacon.
