### ISSUE TITLE
MCP bug -> works without any power

### ISSUE THREAD

**Issue by CaptainJankez** [magknight/787aviatorsTracker#702]
MCP and Autothrottle systems work without battery power

Started the plane in cold and dark, turned on both flight directors, all mcp lights, except AP lights highlighted

MCP and A/T shouldnt activate without any power

I have a video of this situation, but can't post it here

 - OS: Windows 10
 - X-Plane version 11.55
 - Version 1.7.22 beta

**Comment by aeroniemi** [comment]
this is slightly more complicated than it sounds - there are circumstances that with the battery button off you'd expect the autoflight to be powered (as the button can be overriden by systems, but working out exactly the boundary is a somewhat big task, probably for a v2 of the electrical systems (if we do that)

**Comment by aeroniemi** [comment]
Fixed in 1.7.28, just forced them all off with low power
