### ISSUE TITLE
Fuselage after DOOR NO 2 does not show in interior view

### ISSUE THREAD

**Issue by CaptainJankez** [magknight/787aviatorsTracker#703]
**Describe the bug**
Fuselage does not show correctly in the interior view, went to the left wing view and went outside the plane, the fuselage was invisible, the only thing that I could see was the cabin, wings, engines, landing gear, but the middle fuselage disappeared

I should see the whole fuselage while entering the exterior view

 - OS: Win 10
 - X-Plane version 11.55
 - Version 1.7.22
![image](https://user-images.githubusercontent.com/91334772/154532364-a48cb773-245a-4887-973d-d46664237822.png)

**Comment by Simleybob** [comment]
this is expected, use the exterior view to look outside!

**Comment by aeroniemi** [comment]
Expected behavior - this reduces the amount of art that is in use at any one time - there are no circumstances where you should be able to see the exterior aft of the forward section from an inside view - switch your view to an exterior one if you want to do that.
