### ISSUE TITLE
ISFD pressure setting/STD

### ISSUE THREAD

**Issue by CaptainJankez** [magknight/787aviatorsTracker#704]
I pressed the STD button on the standby gyro while passing the transition altitude, but after I did it i manipulated the pressure wheel on the gyro, and I couldnt bring back the STD mode by pressing the button

Press the STD button on the standby gyro, manipulate the pressure wheel on the standby gyro, and try to bring STD mode back, it's impossible

the STD mode should turn on back normally, but it's impossible

not able to make a screenshot with this

 - OS: Windows 10
 - X-Plane version 11.55
 - Version 1.7.22

**Comment by aeroniemi** [comment]
fixed in 1.7.23
