### ISSUE TITLE
ND range on startup

### ISSUE THREAD

**Issue by ZaccJacc** [magknight/787aviatorsTracker#705]
The ND range on startup is not what the dialogue says it should be. It makes the route drawn look screwed. It's resolved after adjusting the range once, but currently it looks as though the track line on the ND is drawn for the correct range, but all the waypoints are drawn as if the map range is way further out than it is... Not entirely sure if I explained that well but fingers crossed!

**Comment by ZaccJacc** [comment]
![image](https://user-images.githubusercontent.com/58274381/154794831-a10408d7-0a2f-4e7f-8748-9393a2100870.png)


heres a screenshot of it when its bugged^^^

![image](https://user-images.githubusercontent.com/58274381/154794861-210c6a0d-5ffa-4cce-a9ba-c8937267d9dc.png)


and then here it is after a quick readjustment^^^

**Comment by KBNOtaku** [comment]
I can confirm this!
After moving the range for the first time it shows correct.
![X-Plane Screenshot 2022 02 19 - 13 05 00 98](https://user-images.githubusercontent.com/56799893/154802326-cb4e6331-9da3-4ca7-80af-88264e149acb.png)

https://user-images.githubusercontent.com/56799893/154802547-5acd5459-c5e8-4caa-b398-8a4cdc6262d6.mp4

**Comment by aeroniemi** [comment]
I can't actually replicate this - when I load it up the range is what you'd expect (and the same as the ND says it should be - do you have any further guidance on how to replicate this?

**Comment by ZaccJacc** [comment]
So the times I've had this issue I be completely planned and input the route into the FMC, SIDs STARs and all, whilst the IRS have been in align / they finished aligning partway through the process. Don't know if the IRS would affect it, but maybe to do with how the screen initially draws idk

**Comment by aeroniemi** [comment]
ok, i've been able to replicate it under specific conditions; it seems to happen only when the datarefs aren't initialised ahead of time (ie first run of x-plane) - should be fixed in 1.7.24
