### ISSUE TITLE
Steering moving in Air

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#706]
**Describe the bug**
The steering handle is moving on its own when in the Air?

**To Reproduce**
to a flight

**Expected behaviour**
Should´t it be not moving at all when in the air?

**Video**

https://user-images.githubusercontent.com/56799893/154796890-9148ca2f-1e80-4b48-bd79-2f649ed80f34.mp4

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.55r2]
 - Version [e.g. 1.7.22]

**Additional context**

**Comment by aeroniemi** [comment]
the tiller appears to be linked to the actual nosewheel position which definitely isn't right.
the nosewheel also shouldn't move when the wheels aren't on the ground
we probably need to decide whether we want the tiller to move when people are using say roll to control it

**Comment by aeroniemi** [comment]
i've disabled NWS when the wheels aren't on the ground now, it'll kinda fix this issue but probably a better solution should be made as part of a longer term FR
