### ISSUE TITLE
Able to switch to default plan view using commands

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#707]
**Describe the bug**
The Traffic Icons and almost all other Icons in the ND a way to small

**To Reproduce**
Look at the ND

**Expected behaviour**
For better visibility the Icons should appear bigger on the ND

**Screenshots**
![X-Plane Screenshot 2022 02 15 - 16 51 27 51_LI](https://user-images.githubusercontent.com/56799893/154796965-7cae7f15-c5cf-45f0-9e4d-b64f8e915cb0.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.55r2]
 - Version [e.g. 1.7.22]

**Additional context**

**Comment by aeroniemi** [comment]
they are the default icons - they should be disabled if you update the aircraft properly (delete 787/cockpit_3d and reupdate)

**Comment by KBNOtaku** [comment]
I did what you say deleted Cockpit_3d and updated again with Skunkcraft, started XP11 again.
Problem is still there! Traffic even shows when TFC is turned off?
![X-Plane Screenshot 2022 02 19 - 11 51 56 83](https://user-images.githubusercontent.com/56799893/154798093-86cb872b-0023-43ef-bb22-d25d62c7f9d4.png)
![X-Plane Screenshot 2022 02 19 - 11 51 15 89](https://user-images.githubusercontent.com/56799893/154798110-4f637f53-e36b-492d-827e-fc9c090f0e86.png)
![X-Plane Screenshot 2022 02 19 - 11 51 38 90](https://user-images.githubusercontent.com/56799893/154798112-2dd0bad2-6d6c-4970-b933-a147ebfec036.png)

**Comment by aeroniemi** [comment]
you're in plan view, so i'm not able to help you really
the main bug here is that you are ale to switch to plan view like that, which will be fixed in 1.7.23

**Comment by KBNOtaku** [comment]
Just did a complete clean installation of the Aircraft!
Now I don´t see any Traffic at all anymore?
![X-Plane Screenshot 2022 02 19 - 13 26 08 18](https://user-images.githubusercontent.com/56799893/154802249-407203ba-d4da-4b68-ad09-e99d5c93a550.png)
![X-Plane Screenshot 2022 02 19 - 13 27 29 73](https://user-images.githubusercontent.com/56799893/154802251-cb91a48f-438d-4e69-a397-5a6382690b0e.png)
![X-Plane Screenshot 2022 02 19 - 13 43 02 23](https://user-images.githubusercontent.com/56799893/154802253-275b8202-bd61-492f-a4fd-77204af41932.png)
![X-Plane Screenshot 2022 02 19 - 13 44 58 58](https://user-images.githubusercontent.com/56799893/154802262-b6e7167c-ed0c-45c0-ac7b-84390203627e.png)

**Comment by aeroniemi** [comment]
issue fixed in 1.7.23
