### ISSUE TITLE
Waypoint Icons always visible

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#708]
**Describe the bug**
The Waypoint Icons are visible on the ND even when turned off?

**To Reproduce**
Try to turn off WPT ICON´s on the ND

**Expected behaviour**
When turning off WPT ICON´s for ND they should not be shown on the ND!

**Screenshots**
![X-Plane Screenshot 2022 02 15 - 16 42 49 75](https://user-images.githubusercontent.com/56799893/154797011-8e4901e7-9205-4adb-9350-4ac8914ed371.png)

![X-Plane Screenshot 2022 02 19 - 11 49 54 44](https://user-images.githubusercontent.com/56799893/154798018-673865bd-8b62-488a-a87d-13e5b5f5fd88.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.55r2]
 - Version [e.g. 1.7.22]

**Additional context**

**Comment by aeroniemi** [comment]
you're still showing the default ND overlays, so they must still exist somewhere, either in cockpit_3d or cockpit

**Comment by KBNOtaku** [comment]
Just did a complete clean installation of the Aircraft, now it seams to be fixed.
