### ISSUE TITLE
Scratchpad Info issue

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#709]
**Describe the bug**
When entering something into the FMC, when going to INIT/REF page the last entered value appears again in the Scratchpad?

**To Reproduce**
Look at the Video

**Expected behaviour**
After entering input into the FMS scratchpad should keep empty.

**Video**

https://user-images.githubusercontent.com/56799893/154798205-d046ddf2-8ce9-4a55-be38-e0998f29ad5b.mp4

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.55r2]
 - Version [e.g. 1.7.22]

**Comment by aeroniemi** [comment]
fixed for 1.7.23
