### ISSUE TITLE
Xplane 11 Crashes when i when i Start a flight with the 787-9

### ISSUE THREAD

**Issue by SundryOregon** [magknight/787aviatorsTracker#71]
I bought myself the Magknight 787 Aviator Edition, but everytime i lauch it in Xplane the whole sim crashes with no Message.

I started the sim and loaded up the 787 but it crashed instant. Same happend when i startet in a diffrent Plane and then switched to the 787.

These are my Versions:
 - OS: Windows 10
 - X-Plane version 11.34
 - Version Magknight787 1.2.0
 - Java 8 SE Runtime 1.8.0_211

**Comment by aeroniemi** [comment]
I assume that you've fixed this, so am closing it.
