### ISSUE TITLE
New reflections flickering

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#710]
**Describe the bug**
The new Reflections are flickering constantly

**To Reproduce**
See Video

**Expected behaviour**
No flickering!

**Videos**

https://user-images.githubusercontent.com/56799893/154802575-f068b8bd-45c6-44bf-88b1-b026f79fb478.mp4

https://user-images.githubusercontent.com/56799893/154802580-32a324ca-9fa9-4110-ac74-75cb155b6b2b.mp4

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.55r2]
 - Version [e.g. 1.7.22]

**Additional context**
When there are no Reflections on the Display´s the issue does not happen!

**Comment by Simleybob** [comment]
I can also confirm this

**Comment by 27MikeDelta** [comment]
affirm

**Comment by aeroniemi** [comment]
it only happens with cinema verite on, although i'll pass it on to art

**Comment by KBNOtaku** [comment]
> it only happens with cinema verite on, although i'll pass it on to art

As you can see in my Videos Cinema Verite isn't turned on and the flickering also happens?

**Comment by Simleybob** [comment]
Good point lol

**Comment by aeroniemi** [comment]
Reflections have been reverted to the old ones - this still happens, but is less noticable (and nobody seemed to care before)
