### ISSUE TITLE
LNAV Disconnecting ramdomly

### ISSUE THREAD

**Issue by hazlamahedich** [magknight/787aviatorsTracker#715]
**Describe the bug**
Updated via skunkcrafts to the latest version 1.7.22. Have done two flight KEWR to KSFO and KSFO to KIAH. On both those flights the LNAV just diasconnects automatically on random points in the flight

**To Reproduce**
fly the 787 and wait for a couple of minutes and LNAV disconnects automatically

**Expected behaviour**
LNAV doesnt disconnect automatically unless LNAV button is deactivated

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] Widows 10
 - X-Plane version [e.g. 11.30r2] 11.5 latest version
 - Version [e.g. 1.6.10] 1.7.22

**Additional context**

**Comment by hazlamahedich** [comment]
ok just noticed when i press right alt it disconnects lnav but i dont have this button mapped to anything. I only use the right alt button with tab to change windows/programs on the taskbar. Did not have this issue with the previous version

**Comment by hazlamahedich** [comment]
LNAV also disengages when i press right shift button

**Comment by aeroniemi** [comment]
if it didn't happen with the previous version then it's definitely not something that is occurring as a result of the plane - it'll be something else (flywithlua?)
