### ISSUE TITLE
NAV RAD Input logic issue

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#718]
**Describe the bug**
When Entering ADF FRQ. into the left FMC the incorrect Format error pops up every time?
On the Right side it is ok.
Also Scratchpad do not get emptied after entering.

**To Reproduce**
Enter ADF FRQ. into on NV RAD Page on the left FMC.

**Expected behaviour**
If entered correct info message should not show.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/56799893/155510502-07926f17-7102-48f0-a8cd-aff0c046002e.png)

Video:
https://www.youtube.com/watch?v=OzHmFnxCe8I

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.55r2]
 - Version [e.g. 1.7.24]

**Comment by aeroniemi** [comment]
two different issues here:
the help window doesn't show the first message
ADF wasn't producing an error message
both fixed for 1.7.26
