### ISSUE TITLE
2 Heading lines on right ND

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#719]
**Describe the bug**
on the FO/Right ND there is always a second fixed heading line visible?

**To Reproduce**
Just use the aircraft.

**Expected behaviour**
The heading line not showing current heading, should not be there!

**Screenshots**
![X-Plane Screenshot 2022 02 24 - 10 44 09 74](https://user-images.githubusercontent.com/56799893/155511900-e5aedf88-9114-4606-9c83-17c055a25c65.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.55r2]
 - Version [e.g. 1.7.24]

**Comment by aeroniemi** [comment]
That's the default heading line, which shouldn't exist if all of your cockpit_3d files are up to date - it appears to be fine for the majority of users!

**Comment by aeroniemi** [comment]
Closed as stale
