### ISSUE TITLE
Avitab is not working, looks transparent after update

### ISSUE THREAD

**Issue by davidmerak** [magknight/787aviatorsTracker#731]
**Describe the bug**
Avitab is transparent
**To Reproduce**
Steps to reproduce the behaviour:
Enable the avatar in settings
**Expected behaviour**
Avitab is not working

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.6.10]

**Additional context**

**Comment by aeroniemi** [comment]
Fixed in 1.7.32
