### ISSUE TITLE
windows plugged

### ISSUE THREAD

**Issue by Thomrade** [magknight/787aviatorsTracker#734]
The windows of the 787-8 are plugged, version 1.7.31

![B788 - 2022-03-08 15 41 15](https://user-images.githubusercontent.com/94917220/157270190-8ae5ce13-2868-4f04-8365-1fd89e96096e.png)

**Comment by aeroniemi** [comment]
not really sure what's going on with that - it works fine sometimes, and other times it doesn't. the same thing can be seen with the cockpit windows

**Comment by aeroniemi** [comment]
Fixed in 1.7.33 - was missing a texture
