### ISSUE TITLE
wing nav light and strobes are in the incorrect place

### ISSUE THREAD

**Issue by CaptainJankez** [magknight/787aviatorsTracker#735]
strobe lights for the B787-8 in the position of the B787-9

Loaded up the B787-8 with strobes and wing nav lights in the wrong place

strobes and wings nav lights should be on the wingtips, not in the back

![B788 - 2022-03-08 16 53 39](https://user-images.githubusercontent.com/91334772/157282752-cae8f790-8e83-4ba5-a3bd-86fbface0a0f.png)
![B788 - 2022-03-08 17 10 00](https://user-images.githubusercontent.com/91334772/157282777-bcd54159-e2bf-473e-ad24-185053ba4821.png)

 - OS: Win 10
 - X-Plane version 11.55
 - Version 1.7.31

**Comment by cajunjosh** [comment]
With 1.7.35 the lights are much closer to their original positions but still slightly off.

![image](https://user-images.githubusercontent.com/75854551/157344087-b3e901e3-014b-497c-b84f-f2e4d909af1a.png)

![image](https://user-images.githubusercontent.com/75854551/157344138-8f34bb43-b591-405e-a651-03d295523eae.png)

![image](https://user-images.githubusercontent.com/75854551/157344220-c33d6924-060d-461e-a0e3-c0d3119696ca.png)

**Comment by cajunjosh** [comment]
Also looks like one of the wing lights might have gotten moved inside of the wing.

![image](https://user-images.githubusercontent.com/75854551/157344324-0b3a78c5-59fd-417a-9c21-904d36bb252e.png)

**Comment by aeroniemi** [comment]
The remaining tail/beacon lights have been moved, any further light changes would be a feature request
