### ISSUE TITLE
FMOD sound not loading

### ISSUE THREAD

**Issue by cajunjosh** [magknight/787aviatorsTracker#737]
On the interior & exterior the engine startup and operating sounds are very different.  It almost sounds like it's only one sound file that the pitch is being changed on by xplane.

On the 800 it also sounds like the exterior sounds might be missing as the sound output doesn't change from interior to exterior view nor does it change from exterior front to back as the 787-9 does.  If I didn't explain clearly I can make a video comparison but hopefully devs can replicate.

**Comment by aeroniemi** [comment]
Are you sure you're using the latest version? That sounds rather like it's not loading the FMOD pack, which was fixed in 1.7.31. To check, see if there is a 787/fmod/B788.snd file present!

**Comment by cajunjosh** [comment]
After the .31 update I was missing the 788.snd file.  When skunkscraft pulled the .32 update it downloaded the file and t hings are working properly.  Thank you for the help!
