### ISSUE TITLE
No animation on the park brake switch in the 8 version

### ISSUE THREAD

**Issue by CaptainJankez** [magknight/787aviatorsTracker#739]
no animation on the park brake switch in the 8 version

the animation should exist, the smooth one from the previous versions

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.55
 - Version 1.7.31

https://user-images.githubusercontent.com/91334772/157287798-5cdb1736-a03f-42b1-9a49-d48a29634785.mp4

**Comment by aeroniemi** [comment]
fixed in 1.7.35
