### ISSUE TITLE
Flap switch goes too far when using keyboard keys

### ISSUE THREAD

**Issue by CaptainJankez** [magknight/787aviatorsTracker#740]
flap lever goes off it;s position when pressing keyboard keys instead of manipulating it with my cursor

click your key assignated to flaps deploy, and see how it goes off it's position

the flap lever should stay in its limits

 - OS: Windows 10
 - X-Plane version 11.55
 - Version 1.7.31

check it out here https://youtu.be/9MTuCgbDXvo

**Comment by aeroniemi** [comment]
Fixed in 1.7.33
