### ISSUE TITLE
laggy screens in both 8 and 9 new planes

### ISSUE THREAD

**Issue by CaptainJankez** [magknight/787aviatorsTracker#741]
the screens in our dreamliners are so damn laggy, even if I have 50 frames per second, it shouldnt happen

**Comment by aeroniemi** [comment]
The screen redraw rate isn't linked to your framerate - it's fixed at 10FPS, but that shouldn't be noticable on any screens other than EICAS

**Comment by aeroniemi** [comment]
i've added high rate to 1.7.41 so that'll change this
