### ISSUE TITLE
Missing magenta line in the map

### ISSUE THREAD

**Issue by gusram5** [magknight/787aviatorsTracker#743]
**Describe the bug**
The magenta line is missing on the ND display

**To Reproduce**
Steps to reproduce the behaviour: create a flight plan with several way points and set the ND to MAP

**Expected behaviour**
A magenta linea should be visible following each wp 

**Screenshots**

![B788 - 2022-03-08 11 57 21](https://user-images.githubusercontent.com/101215086/157316102-2775faa2-945b-46c0-9e7f-76b586df3f6f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.55r2]

**Comment by aeroniemi** [comment]
I assume you're in the -8?

**Comment by aeroniemi** [comment]
Fixed in 1.7.33
