### ISSUE TITLE
Flaps stick doens't match with detents

### ISSUE THREAD

**Issue by gusram5** [magknight/787aviatorsTracker#744]
**Describe the bug**
The flap stick should match with the detents
**To Reproduce**
Pull down flaps and you will see is not matching

**Screenshots**
![B788 - 2022-03-08 12 56 12](https://user-images.githubusercontent.com/101215086/157316725-8f896e92-cde4-4961-a1bc-8e6a649fc089.png)

**Comment by aeroniemi** [comment]
duplicate of #740
