### ISSUE TITLE
Nose goes down when plane try to gain speed

### ISSUE THREAD

**Issue by gusram5** [magknight/787aviatorsTracker#745]
**Describe the bug**
The plane dive down when trying to gain speed

**To Reproduce**
With plane at 200kts for example and try to increase speed to 250kts the plane dive the nose too abruptly 

**Expected behaviour**
The plane should lower the nose to gain speed but not diving neither loosing altitude

**Comment by Simleybob** [comment]
#defaultvnav issues

**Comment by aeroniemi** [comment]
This is expected behavior - it's just what it does unfortunately.
