### ISSUE TITLE
Left flaperon deflects in level flight/on ground

### ISSUE THREAD

**Issue by PopFizzelz** [magknight/787aviatorsTracker#75]
**Describe the bug**
Left flaperon deflects a few degrees up in straight and level flight/on the ground when controls are centered.

**Expected behavior**
Flaperon should move to neutral position when roll controls are centered (see right flaperon on attached image of FCTL page).

**Screenshots**
![image](https://user-images.githubusercontent.com/51883928/59566025-8e473b00-905a-11e9-821e-d1af032dbf19.png)
FCTL MFD page

![image](https://user-images.githubusercontent.com/51883928/59566030-ad45cd00-905a-11e9-94c3-e1192f3cbdac.png)
Left flaperon

![image](https://user-images.githubusercontent.com/51883928/59566048-db2b1180-905a-11e9-8aa7-509ca5bd300a.png)
Right flaperon in neutral position for reference

**Desktop:**
 - OS: Windows 10
 - X-Plane version: 11.34r1
 - Version: 1.3.0rc1

**Comment by aeroniemi** [comment]
Resolved in 1.3.9
