### ISSUE TITLE
PFD/MFD PopOuts blank

### ISSUE THREAD

**Issue by MueA320** [magknight/787aviatorsTracker#750]
**Describe the bug**
Pop Outs of the PFDs and MFDs are blank and when I resize the window breaks.

**To Reproduce**
Steps to reproduce the behaviour:
Open the PopOut

**Expected behaviour**
The PFDs and MFDs to show on the pop outs

**Screenshots**
![Screen_Shot_2022-03-08_at_5 03 07_PM](https://user-images.githubusercontent.com/89539583/157347775-3d28e5a6-4c66-46de-9822-19e06e62674a.png)
![Screen_Shot_2022-03-08_at_5 03 21_PM](https://user-images.githubusercontent.com/89539583/157347780-39855f2d-d67a-4965-8005-6c1dfbf13ae0.png)
![Screen_Shot_2022-03-08_at_5 03 47_PM](https://user-images.githubusercontent.com/89539583/157347781-fef334a3-4551-4101-a423-a62568c5042b.png)

**Desktop (please complete the following information):**
 - OS: [Mac OS 12.2.1]
 - X-Plane version [e.g. 11.55]

**Comment by aeroniemi** [comment]
somehow the contextwindows just aren't getting any kind of inheritance from the usual runtime now, likely related to the sasl version. unsure what can be done about that tbh

**Comment by MueA320** [comment]
Ok that’s a shame.  I hope you are able to find a solution in the future. At least it’s not a vital function of the add on.

**Comment by aeroniemi** [comment]
Fixed in 1.7.41
