### ISSUE TITLE
EFB performance page flap 10

### ISSUE THREAD

**Issue by gusram5** [magknight/787aviatorsTracker#752]
**Describe the bug**
In the 787-8 the EFB show flap 10 but the plane has not flap 10, it goes from flap 5 to 15
![B788 - 2022-03-08 19 13 30](https://user-images.githubusercontent.com/101215086/157349409-7f33a07d-baf4-4c5e-bd5f-b5ac6122c433.png)

**Comment by aeroniemi** [comment]
fixed in 1.7.36 - the efb is missing a few -8 specific weights, but for now they'll just be unavailable. We'll re-do the performance values with v12, so aren't too worried about this for now
