### ISSUE TITLE
Lower MFD blacked out in cruise

### ISSUE THREAD

**Issue by lucapilot** [magknight/787aviatorsTracker#753]
**Describe the bug**
after hitting cruise altitude (same altitude as in vnav plan) the lower MFD blacks out....

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - X-Plane version 11.30
 - Version 1.7.35
![X-Plane_Screenshot_2022 03 09_-_12 15 59 62](https://user-images.githubusercontent.com/101266159/157451499-ba3d7916-e7ab-4662-a41f-b81279ea8714.png)

**Additional context**

**Comment by aeroniemi** [comment]
log?

**Comment by aeroniemi** [comment]
Closed due to lacking info
