### ISSUE TITLE
Avitab on F/O seat

### ISSUE THREAD

**Issue by AeroChamzi** [magknight/787aviatorsTracker#754]
**Is your feature request related to a problem? Please describe.**
Please if it is possible to add an avitab by the officer seat 

**Describe the solution you'd like**
Avitab on both sides

**Describe alternatives you've considered**

**Additional context**

**Comment by AeroChamzi** [comment]
duplicate

**Comment by Simleybob** [comment]
#611

**Comment by aeroniemi** [comment]
duplicate of #611
