### ISSUE TITLE
Too shiny interior Cabin 787-8

### ISSUE THREAD

**Issue by arnaumj** [magknight/787aviatorsTracker#756]
**Describe the bug**
Interior is too shiny
**To Reproduce**
Steps to reproduce the behaviour:
Load up the 787-8
**Expected behaviour**
The cabin is not as reflective and is made of something other than plastic

**Screenshots**
![X-Plane 2022-03-09 18-31-46](https://user-images.githubusercontent.com/59321668/157556981-6847ad6e-336c-4b23-9f99-2f42eec9f6d2.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.55r2]  11.55
 - Version v1.7.35

**Additional context**

**Comment by Simleybob** [comment]
same here, although I have missing floor in the first part of the cabin 
![image](https://user-images.githubusercontent.com/81443205/157735722-d44c6a5a-a454-488f-9740-4afe247083af.png)
The normals need resetting or something.

**Comment by arnaumj** [comment]
Yeah simley that's another thing

**Comment by aeroniemi** [comment]
i think this was fixed in 1.7.36
