### ISSUE TITLE
Elevator Sticks

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#76]
**Describe the bug**
Unable to control elevator, it sticks into one position after leaving the ground.

**To Reproduce**
Not really sure what's causing this as you can take off just fine but as soon as you leave the ground the elevator stops responding.

**Expected behavior**
It should behave as expected and respond to joystick inputs.

**Screenshots**
![B7879 - 2019-06-17 18 01 22](https://user-images.githubusercontent.com/39658757/59622756-5a3b4b00-912a-11e9-8d80-aee5f938b318.png)
![uups](https://user-images.githubusercontent.com/39658757/59622798-80f98180-912a-11e9-9b80-9a934906db05.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.35b2
 - Version 1.3.0rc1

**Comment by OldGroof** [comment]
Forgot to add this screenshot.
![B7879 - 2019-06-17 18 01 27](https://user-images.githubusercontent.com/39658757/59622889-b7370100-912a-11e9-9769-dd0e060679a5.png)

**Comment by aeroniemi** [comment]
Not repeatable in rc1
