### ISSUE TITLE
TO config warning works without battery power

### ISSUE THREAD

**Issue by CaptainJankez** [magknight/787aviatorsTracker#761]
TO config warning works without battery power

moved throttle above 50% of power, and the TO config warning worked without it

it shouldnt happen

 - OS: Windows 10
 - X-Plane version 11.55
 - Version 1.7.36

Check it out here https://youtu.be/EQWqmzhqIvg

**Comment by aeroniemi** [comment]
fixed in 1.7.37, added the stab trim condition too
