### ISSUE TITLE
TA/RA does no activate TFC on ND

### ISSUE THREAD

**Issue by Simleybob** [magknight/787aviatorsTracker#762]
**Describe the bug**
This is why people were/are complaining about traffic not showing on the ND. Surely when TA/RA transponder mode is activated, TFC should automatically be checked in the ND's settings, making TFC appear on the ND.

**To Reproduce**
Activate TA/RA and have a look at the ND settings.

**Comment by aeroniemi** [comment]
no? that's not what happens in reality

**Comment by Simleybob** [comment]
ok, nvm then
