### ISSUE TITLE
Leading Edge Slats tilt angle is not correct

### ISSUE THREAD

**Issue by kadirkurt** [magknight/787aviatorsTracker#764]
**Describe the bug**
B787-9 The Leading Edge slat tilt angle is not correct.

**Expected behaviour**
![26650_1613266633](https://user-images.githubusercontent.com/15309087/158065243-703b06f3-0f27-4a39-b34e-8360980e04f1.png)

**Screenshots**
![2022-03-13 17_41_00-X-System](https://user-images.githubusercontent.com/15309087/158064840-4d4668c1-7c21-4a36-a98d-ed3630a7ef1b.png)

**Desktop**
 - OS: [e.g. Windows 11]
 - X-Plane version [e.g. 11.55]
 - Version [e.g. 1.7.35]

**Comment by aeroniemi** [comment]
I don't think it's actually the angle, more the actual movement distance (which is limited by animations) - it'll be fixed in the new wings
