### ISSUE TITLE
TO config warning works in the air, after takeoff with stab trim, flaps not set into the cdu

### ISSUE THREAD

**Issue by CaptainJankez** [magknight/787aviatorsTracker#766]
TO config warning works in the air, after takeoff with stab trim, flaps not set into the cdu

hot start on the -9 version, set flaps to 5, dont touch the stab trim and take off

to warning should "shut up" in the air

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.55
 - Version 1.7.38

**Comment by aeroniemi** [comment]
I've added a condition to this effect in .39 - in reality this wouldn't be an issue because you just wouldn't takeoff with the horn operating.
