### ISSUE TITLE
Cannot enter digits on Simbrief Username

### ISSUE THREAD

**Issue by SquawkModeCharlie** [magknight/787aviatorsTracker#769]
**Describe the bug**
When setting up the simbrief username on the ACARS page, it is not possible to enter numbers. E.x "Hanoodi191", would be limited to "Hanoodi". Instead, you must type out the username with the numbers elsewhere and then paste it into the box. 

**To Reproduce**
Go to the ACARS page and try entering any username with a number in it, albeit you can paste it into the box. 

**Expected behaviour**
You must be able to enter numbers alongside a string of characters, E. x "Magknight123".

**Desktop (please complete the following information):**
 - OS: Windows 11
 - X-Plane version: 11.55
 - Version : 1.7.38

**Comment by aeroniemi** [comment]
Fixed in 1.7.40
