### ISSUE TITLE
MCP Goes Blank When Selecting DOORS

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#77]
**Describe the bug**
When you select the DOOR page on the EICAS/EFIS (I can't remember what it's called.) the MCP goes blank as well as some other screens.

**To Reproduce**
Select the DOOR page on the EICAS/EFIS

**Expected behavior**
Not this.

**Screenshots**
![B7879 - 2019-06-17 18 07 56](https://user-images.githubusercontent.com/39658757/59623071-27de1d80-912b-11e9-93ed-624382339529.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.35b2
 - Version 1.3.0rc1

**Comment by aeroniemi** [comment]
Identified and resolved for rc3
