### ISSUE TITLE
fuel instrument panel

### ISSUE THREAD

**Issue by kadirkurt** [magknight/787aviatorsTracker#770]
Separate display of the amount of fuel in the tanks on the fuel panel.

In my latest version controls, the fuel levels in the tanks do not appear separately on the fuel instrument panel. It may be as in the attached image.

original :
![fuel](https://user-images.githubusercontent.com/15309087/158620139-8d1f9bf3-5699-4885-ae31-b0e4a312bb4e.jpg)

magknight / 787-9
![fuel](https://user-images.githubusercontent.com/15309087/158620838-659f22cf-d779-404c-85c1-3e20e41593b3.png)

**Comment by aeroniemi** [comment]
This is expected behavior - the per-tank display is only shown when something requires attention.
