### ISSUE TITLE
Init page numbers

### ISSUE THREAD

**Issue by ZaccJacc** [magknight/787aviatorsTracker#771]
Setting up the RTE pages, and at the top it says 1/3 pages, I go to the next page and it goes to 2/2.
![image](https://user-images.githubusercontent.com/58274381/158667782-b06d0de7-83d8-4508-8594-2ec9c61953f5.png)
![image](https://user-images.githubusercontent.com/58274381/158667854-006c2cbc-b434-4a2b-adba-e982a71fa0f5.png)

**Comment by aeroniemi** [comment]
it's an x-plane bug, i think it's fixed in v12 though
