### ISSUE TITLE
Stab trim working without battery power

### ISSUE THREAD

**Issue by CaptainJankez** [magknight/787aviatorsTracker#772]
Stab trim working without battery power

spawn and try to manipulate with stab trim, it works without battery power

stab trim should work only with hydraulic power

 - OS: Windows 10
 - X-Plane version 11.55
 - Version 1.7.39

see it here ---> https://youtu.be/tXxBtuzTWTY

**Comment by aeroniemi** [comment]
The stabilizer trim is electric, so doesn't require hydraulics - i've added a power condition to the commands in 1.7.40, although we won't add one to the axis to keep compatability
