### ISSUE TITLE
*fixed* basic canva seen on the GE3 fanblades

### ISSUE THREAD

**Issue by CaptainJankez** [magknight/787aviatorsTracker#775]
*fixed* basic canva seen on the GE3 fanblades

just fixed it, replace the file with my fix
![GE3_NML](https://user-images.githubusercontent.com/91334772/159172229-f53d0e6a-5fea-488e-85da-812397e711c7.png)

 - OS: Windows 10
 - X-Plane version 11.55
 - Version 1.7.40

**Comment by aeroniemi** [comment]
@Sp33dM

**Comment by aeroniemi** [comment]
Fixed in 1.7.42
