### ISSUE TITLE
PFD Popouts don't work but MFD pop outs do.

### ISSUE THREAD

**Issue by MueA320** [magknight/787aviatorsTracker#777]
**Describe the bug**
PFD Popouts show a black screen.

**To Reproduce**
Open PFD Popouts
**Expected behaviour**
PFD popouts to show 

**Screenshots**
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/8312822/Log.txt)
![Screen Shot 2022-03-20 at 10 56 27 PM](https://user-images.githubusercontent.com/89539583/159200007-cb0db6e2-4393-4d49-bfb8-ceae25c1b2da.png)
the PFD

**Desktop (please complete the following information):**
 - OS: [Mac OS 12.3]
 - X-Plane version [e.g. 11.55r2]
 - Version [e.g. 1.7.42]

**Additional context**
Thanks for fixing the MFDs, I hope you are able to fix the PFDs

**Comment by Simleybob** [comment]
The PFDs didn’t work before.

They have yet to have the MFD treatment.

**Comment by MueA320** [comment]
Oh, ok I am dumb
