### ISSUE TITLE
Electric spoilers not working

### ISSUE THREAD

**Issue by kadirkurt** [magknight/787aviatorsTracker#779]
Spoiler panels 4,5,10,11 of type 787-9 are supposed to work electrically, but they do not.

![spoilers](https://user-images.githubusercontent.com/15309087/159714786-9f8f41cb-6d02-410b-8ab9-9c2994350c9e.png)

 - OS: [e.g. Windows 11]
 - X-Plane version [e.g. 11.55]
 - Version [e.g. 1.7.42]

**Comment by aeroniemi** [comment]
what circumstances are you in that you want to use them on electrical power only?

**Comment by kadirkurt** [comment]
I don't use it but it might be good for getting the aircraft closer to reality.

**Comment by aeroniemi** [comment]
As far as I'm aware there isn't really a use for them outside of failures (which we don't support, and have no intention to), so we probably won't modify them

**Comment by kadirkurt** [comment]
Yes true.it could be good for reality.your choice.Thanks.
