### ISSUE TITLE
CDU(comm  page)

### ISSUE THREAD

**Issue by kprema123** [magknight/787aviatorsTracker#782]
When I try enter anything on COMM page nothing

let me type

be able to type on it with no problems

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.6.10]

**Additional context**

https://user-images.githubusercontent.com/96954042/160237131-5ca7ba14-f614-40cd-8658-5ae0839efee4.mp4

**Comment by aeroniemi** [comment]
It only supports entry using your physical keyboard rather than the 3d one - it's somewhat intentional as other ways of deciding what entry to use would be kinda confusing to users
