### ISSUE TITLE
Outside view

### ISSUE THREAD

**Issue by kprema123** [magknight/787aviatorsTracker#783]
When I look out the external view the planes body disappears briefly AND happens on the -8 model too

stop disappearing

Plane body should just be normal

![image](https://user-images.githubusercontent.com/96954042/160237210-2deec492-7299-4f1c-99db-850e729bfe32.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.6.10]

**Additional context**

https://user-images.githubusercontent.com/96954042/160237272-24474485-a158-45b9-ae81-e37893e48c94.mp4

**Comment by aeroniemi** [comment]
I think this is probably expected behavior - the exterior fuselage is hidden on internal views to save performance, and it looks like your external view is classified as internal (such as due to xcamera etc)

**Comment by aeroniemi** [comment]
closed as stale - if you have more info about this, feel free to reopen it
