### ISSUE TITLE
Changing camera position 

### ISSUE THREAD

**Issue by PiLOTseq123** [magknight/787aviatorsTracker#784]
When mouse is over screens I can't change my camera by clicking numbers on the numpad, and when mouse is e.g. on the window I can change camera by clicking numbers on numpad. Even if the screens are off. 

I propose that camera won't change if you click on the screen, and if not screen is not clicked camera would change.

**Comment by aeroniemi** [comment]
This is expected behavior - it makes keyboard entry much more sensible than the old scheme, as it now means that it is only captured when you're on the screen, and always captured whilst on the screen - if you want to change view, just move your mouse off the screen
