### ISSUE TITLE
-8 Disappearing heading line past 360 degrees

### ISSUE THREAD

**Issue by Simleybob** [magknight/787aviatorsTracker#785]
There should be the line here, past 000 degrees.

https://1drv.ms/v/s!Ahk-fanHsrwDqrQvXzX5k-2ay_0RfA?e=9gu5hh

**Comment by Simleybob** [comment]
-8 btw

**Comment by aeroniemi** [comment]
Are you sure it's directly related to 360/0? it's supposed to go off at like 60 deg around so I would expect it to do something like that

**Comment by Simleybob** [comment]
Def, bc earlier in the flight when I was facing around north, it was the same

**Comment by Simleybob** [comment]
Another test: https://1drv.ms/v/s!Ahk-fanHsrwDqrR31kaC4ykjDT3SBw?e=18NBDG

**Comment by aeroniemi** [comment]
fixed in 1.7.43
