### ISSUE TITLE
Weight discrepancy 788 (EFB / MFD)

### ISSUE THREAD

**Issue by 0AlphaGhost0** [magknight/787aviatorsTracker#786]
**Describe the bug**
After loading the Aircraft via the Simbrief uplink there is a discrepancy in the weights between the EFB and the MFD of about 5 t. The minimal or emptyweight for the Aircraft is also wrong i guess.

**To Reproduce**
Just load the 788 via the Simbrief Uplink f.eg. 

**Expected behaviour**
EFB and MFD should have the Same GW or TOW.

**Screenshots**
![image](https://user-images.githubusercontent.com/62098544/161540246-6fd1717b-0569-4ba9-b860-d74cadfa66a9.png)

**Desktop (please complete the following information):**
 - OS: e.g. Windows 11
 - X-Plane version e.g. 11.55
 - Version e.g. 1.7.43

**Additional context**

**Comment by aeroniemi** [comment]
fixed in 1.7.44
