### ISSUE TITLE
Fuel pumps are freaking out when engines off

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#79]
**Describe the bug**
According the the EICAS/EFIS the fuel pumps keep flicking between on and off very quickly.

**To Reproduce**
Just watch the fuel pumps on the EICAS/EFIS

**Expected behavior**
They should just remain in one position

**Screenshots**
https://gyazo.com/50d3d3afa2476fbaad89aacb2f4edc0f

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.35b2
 - Version 1.3.0rc3

**Comment by OldGroof** [comment]
Wait I mean fuel shut offs

**Comment by aeroniemi** [comment]
https://i.imgur.com/oyuGsJu.jpg
i'm not seeing that happen replicating the conditions i can see in that image
it might happen with some very specfic circumstances, but I haven't been able to find those

**Comment by aeroniemi** [comment]
@OldGroof still happening?
