### ISSUE TITLE
Shared texture near horizontal stabilizer

### ISSUE THREAD

**Issue by joeycao2004** [magknight/787aviatorsTracker#812]
I encountered this issue twice when making four liveries for the MK787. This area (and the one on the opposite side) shares the paintkit with another area on the fuselage. To make matters worse, it is not taken from the same level of the area, which makes it impossible to align if there is a stripe going through.
Will this ever be changed? Or will it be left like this? I strongly hope it could be dealt with for two of my three livery designs cannot meet their full potential due to the displaced texture.
Images of the problem attached.

![B7879 - 2022-04-20 16 55 56](https://user-images.githubusercontent.com/57905565/164194313-9c3a63a3-22cc-410d-8f71-c59d8eee1e44.png)
![B7879 - 2022-04-20 16 58 23](https://user-images.githubusercontent.com/57905565/164194499-e5445777-1858-4206-beaa-3ba72c28b275.png)

**Comment by aeroniemi** [comment]
Are you making liveries for the dash8 or the dash9? This has definitely been reported before on the -9 and was marked as fixed

**Comment by joeycao2004** [comment]
> Are you making liveries for the dash8 or the dash9? This has definitely been reported before on the -9 and was marked as fixed

-9. I'll check if my aircraft is the latest version... perhaps I've missed an update. Will return with new information asap.

**Comment by joeycao2004** [comment]
> Are you making liveries for the dash8 or the dash9? This has definitely been reported before on the -9 and was marked as fixed

I'm flying with 1.7.0. Is there any update afterwards?

**Comment by aeroniemi** [comment]
> I'm flying with 1.7.0. Is there any update afterwards?

the latest version is 1.7.49 - see https://docs.magknight.org/faq/#how_do_i_update_my_787

**Comment by joeycao2004** [comment]
> > I'm flying with 1.7.0. Is there any update afterwards?
> 
> the latest version is 1.7.49 - see https://docs.magknight.org/faq/#how_do_i_update_my_787

Wasn't aware of that! I'll check it right now. Thanks!

**Comment by joeycao2004** [comment]
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/57905565/164231821-c0d8e986-2fb1-44f9-b952-4deef00c6132.png">
I... don't really think this is what should happen after the update... I think it's an activation issue. Any fix on that? Should I reinstall the model?

**Comment by joeycao2004** [comment]
<img width="495" alt="image" src="https://user-images.githubusercontent.com/57905565/164232776-1fd42ab5-d274-468c-ac7a-f1ca69268fc6.png">
<img width="364" alt="image" src="https://user-images.githubusercontent.com/57905565/164233933-13a63ffc-5729-4d4b-b1ee-c745a126edf0.png">

Everytime I try to update with Skunkcraft my SASL file goes missing. After repair with Skunkcraft, the file comes back, but once I launch the plane again the file goes missing again.

**Comment by aeroniemi** [comment]
delete 787/plugins - see the guidance in the #general-troubleshooting channel on Discord

**Comment by joeycao2004** [comment]
> delete 787/plugins - see the guidance in the #general-troubleshooting channel on Discord

Unfortunately Discord was not always accessible to me. I apologize for the extra time you've taken to answer my question. The problem is now solved. Thank you so much for the help!

**Comment by aeroniemi** [comment]
so is that no longer an issue in the latest version?

**Comment by joeycao2004** [comment]
> so is that no longer an issue in the latest version?

That is correct. Thanks for the help!
