### ISSUE TITLE
B788 still depicting B789 Runway Turnoff Lights when activated

### ISSUE THREAD

**Issue by oceanboi89** [magknight/787aviatorsTracker#814]
Please refer to the picture. The Runway Turnoff Light is highlighted in Yellow.
![Screenshot (42)](https://user-images.githubusercontent.com/98982429/164356138-f74e1490-649f-4e38-a0b8-1c6223b448e6.jpg)

**Comment by aeroniemi** [comment]
it looks like the issue is actually that there's two runway turnoff lights

**Comment by aeroniemi** [comment]
Fixed in 1.7.50
