### ISSUE TITLE
Discrepancy between PFD clock and waypoint clock

### ISSUE THREAD

**Issue by ZaccJacc** [magknight/787aviatorsTracker#815]
After one of the updates pushed introduced the clock operating on "real" zulu time, there's now an issue between the time the clock shows and the time the waypoint arrival estimate shows, you can see it here:
![image](https://user-images.githubusercontent.com/58274381/164690504-d75f2000-e9e4-42a4-8a10-9f62f5c28215.png)

I'm not sure what "real" zulu means (is it sim time or real world time) so I don't know which one is wrong, but the PFD clock is showing sim time, and the minimap thingy is showing real world time+ETE.

**Comment by ZaccJacc** [comment]
oh and also, the prog page timings agree with the PFD clock so it might just be the minimap that is wrong

**Comment by Simleybob** [comment]
(is it sim time or real world time)

Real world time

**Comment by aeroniemi** [comment]
is the issue that there it is using x-plane's time for calculation, or that the time it is displaying is just wrong?

**Comment by ZaccJacc** [comment]
It's using x-plane's time

**Comment by aeroniemi** [comment]
the issue is that the PFD clock was using x-plane time rather than real time, so i've adjusted that - looks like the waypoint clock is working fine.
