### ISSUE TITLE
787-8 & -9 MFD Range dial only usable with mouse wheel, clicking the dial sets the range to 2.5nm.

### ISSUE THREAD

**Issue by nikolaaaaaaaaaaaaaaaaaaaaaaa** [magknight/787aviatorsTracker#822]
**Describe the bug**
The MFD range dial does not turn with clicks, only with mousewheel movement. Clicking the dial sets the MFD range to 2.5nm.

**To Reproduce**
Steps to reproduce the behaviour:
Make sure the IRS is aligned and set in the FMC
Click the MFD range dial once while the range is set above the minimum. 

**Expected behaviour**
There should be 2 different arrows there, one left and one right, to turn the MFD dial as opposed to just mousewheel motion.

**Desktop (please complete the following information):**
 - OS: Windows 10 (latest)
 - X-Plane version: 11.55 (latest)
 - Version: 1.7.50

**Comment by aeroniemi** [comment]
Fixed in 1.7.51
