### ISSUE TITLE
ND Options not able to activate

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#832]
**Describe the bug**
When I want to activate Waypoints, Airports, VOR1, VOR2 etc.. via the Menu on the ND it is not possible, only deactivating is possible? I can switch on WXR,TERR and TFC via the buttons on the MCDU but not in the ND Menu? So after deactivating VOR L and VOR R it was not possible to activate it again?

**To Reproduce**
try to activate ND options

**Expected behaviour**
to be able to activate and deactivate different ND options

**Video**

https://user-images.githubusercontent.com/56799893/169663533-279aa852-54d0-452e-a149-282156df7202.mp4

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.55r2]
 - Version [e.g. 1.8.0 RC5]

**Comment by aeroniemi** [comment]
will be fixed in store version/1.8.1
