### ISSUE TITLE
-8 always loading default GE3 instead of GE2

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#833]
**Describe the bug**
When using the -8 it is always loading the default GE3 instead of GE3? No GE3 Folder is in the livery. on the -9 it is loading correct.
RR are loaded correct!

**To Reproduce**
Load a 787-8 livery with GE2 but no GE3 Folder

**Expected behaviour**
instead of the default GE3 the GE2 in the livery should be loaded.

**Screenshots**

![ge3issue AA](https://user-images.githubusercontent.com/56799893/169668205-484d8127-8b3d-4fb0-a8f4-1e8ed9d96daa.png)
![ge3issue](https://user-images.githubusercontent.com/56799893/169668206-b39c6548-92ed-4056-9b45-e3f55199a251.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.55r2]
 - Version [e.g. 1.8.0 RC5]

**Comment by aeroniemi** [comment]
Expected, the dash8 only supports GE3
