### ISSUE TITLE
Changing speed and altitude by holding down LMB doesnt work

### ISSUE THREAD

**Issue by tameraktasTU** [magknight/787aviatorsTracker#86]
**Describe the bug**
Can't change speed knob and altitude knob by holding down left mouse button (LMB)
**To Reproduce**
Try to change speed and altitude by holding down LMB

**Expected behavior**
Should be able to change speed and altitude by holding down LMB

**Screenshots**
N.A.

**Desktop (please complete the following information):**
 - OS: W10 1903
 - X-Plane version 11.34
 - Version 1.3.1 + Sounds

**Additional context**

**Comment by aeroniemi** [comment]
Has this changed from 1.3.0?

**Comment by tameraktasTU** [comment]
I didnt fly the plane since a month or so, cant comment on that sadly
