### ISSUE TITLE
Control stability is on when on ground

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#87]
**Describe the bug**
When taxying around you can see the ailerons and flaperons moving as if they are counteracting the bumps the plane rolls over on the ground.

**To Reproduce**
Taxi around, watch the flying surfaces, maybe wack in some sharp turns to exaggerate the issue.

**Expected behavior**
This shouldn't happen. Looking a videos of the real plane, the controls don't move.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.35b5(?) - Not the latest release but the release before
 - Version 1.3.1(with ABXP sounds)

**Additional context**

**Comment by aeroniemi** [comment]
@OldGroof Is it still happening with the most recent 1.3.8?

**Comment by OldGroof** [comment]
Still happening.
https://gyazo.com/c3631d2917e44c19e4fd25b11c5d3363

**Comment by aeroniemi** [comment]
I think it's acting as expected, because from the fctl check of the aircraft the flaperons do deflect with yaw, it's just appearing exaggerated as most people use the yaw axis for ground steering, so it's moving even during taxi

**Comment by OldGroof** [comment]
It’s not responding to rudder inputs though. I’m using a roller axis on the ground so the rudder is not being used. As you steering around on the ground the plane sways about and that’s what the flaperons are responding to.

**Comment by aeroniemi** [comment]
Yeah, can see this is what's happening, but don't think we'll fix it, at least not before our own autoflight system

**Comment by aeroniemi** [comment]
Fixed in 1.3.9
