### ISSUE TITLE
No "start with motors up ", as in the v1.3.0 / 1.3.1 ...  

### ISSUE THREAD

**Issue by MoysesTorres** [magknight/787aviatorsTracker#93]
I am in v1.3.5 , and no start with motors up...

OS Windows 10 64 bits
XP 11.35
B787-9 v 1.3.5

**Comment by axhx15** [comment]
Same problem i dont know why once i installe the skunkcraft updater starts problems===?????

**Comment by aeroniemi** [comment]
Identified and fixed in local copy, probably out for 1.3.6

**Comment by MoysesTorres** [comment]
Very thanks !

Enviado do Email para Windows 10

De: Alex Beavil
Enviado:quarta-feira, 28 de agosto de 2019 05:07
Para: magknight/787aviatorsTracker
Cc:MoysesTorres; Author
Assunto: Re: [magknight/787aviatorsTracker] No "start with motors up ", as inthe v1.3.0 / 1.3.1 ... (#93)

Identified and fixed in local copy, probably out for 1.3.6
