### ISSUE TITLE
New proporsal for new updates

### ISSUE THREAD

**Issue by rubencaldas** [magknight/787aviatorsTracker#94]
**I  have some proporsals for improve the proyect:**

- RAT system, available for emergencys when the engines switch off on flight (due to both engine fire, problem on the fuel system and empty the fuel), and you have a minimal control over the hydraulics system.

- Can open the doors (passangers + cargo + bulk)

- Autoland system on Aproach ILS CAT II / III

- The name of waypoint from FMS (route) on EICAS, could read, because now are ver very small.

- Arcs of range on EICAS and move these when you roll the knob RANGE

**Comment by aeroniemi** [comment]
Most of these things are added/fixed in 1.4.0
