### ISSUE TITLE
Problem with the AUTOPILOT and DESCEND PATH

### ISSUE THREAD

**Issue by rubencaldas** [magknight/787aviatorsTracker#95]
**Describe the bug**
When you are on CRUISE, and you fly over the TOD (Top of descent) and you put on ALT the FL o Heigh to descend, the aircraft don't descend, and showed on FPM rate selector -4000, but it mantein the cruise level

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version  11.35]
 - Version  1.3.5]

**Comment by aeroniemi** [comment]
To descend on VNAV, you need to click FLCH at top of descent to activate descent mode
