### ISSUE TITLE
Switching to a different aircraft causes controls to stop working

### ISSUE THREAD

**Issue by SamPoulton** [magknight/787aviatorsTracker#97]
**Describe the bug**
If you change aircraft after flying the magknight without completely restarting the sim, the newly loaded aircraft has some unusual issues. These include flight controls having no effect, engines shutting down/not starting and unusual light behaviour.
**To Reproduce**

1) load 787
2) change aircraft through main menu
3) attempt to fly aircraft

**Expected behavior**

Both aircraft function as expected

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 19.04
 - X-Plane version 11.35
 - Version Latest (auto updates, reproduced on the most recent as of 15 minutes ago)

**Comment by aeroniemi** [comment]
Should be fixed for 1.3.11, but it's probably still a good idea to restart x-plane between using different aircraft
