### ISSUE TITLE
Horizontal Deviation indicator disappears when using LNAV navigation

### ISSUE THREAD

**Issue by PopFizzelz** [magknight/787aviatorsTracker#99]
![image](https://user-images.githubusercontent.com/51883928/64434882-d4dc8c80-d0c1-11e9-95ca-6825e4eb203e.png)

Newly implemented HDEV indicator goes away sometime after departure (not sure when exactly) and gets replaced by LOC indicator despite not having a signal to any VOR/LOC

EDIT: As it turns out, the HDEV indicator disappears whenever LNAV engages, and returns when going to any other mode of lateral navigation except for LOC.

Aircraft version: 1.3.10
X-Plane Version: 11.36r2
OS: Windows 10

**Comment by aeroniemi** [comment]
Resolved for 1.4.0b1
